// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:nav_msgs/msg.dart' as nav_msgs;

class IsPathValidRequest extends RosMessage<IsPathValidRequest> {
  nav_msgs.Path path;

  static IsPathValidRequest $prototype = IsPathValidRequest();

  // Constructor
  IsPathValidRequest({nav_msgs.Path? path}) : path = path ?? nav_msgs.Path();

  @override
  String get fullType => 'nav2_msgs/srv/IsPathValid_Request';

  @override
  String get messageDefinition => '''nav_msgs/Path path''';

  @override
  int getMessageSize() {
    return (path.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'path': path.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  IsPathValidRequest fromJson(Map<String, dynamic> jsonMap) {
    return IsPathValidRequest(
        path:
            nav_msgs.Path().fromJson(jsonMap['path'] as Map<String, dynamic>));
  }
}

class IsPathValidResponse extends RosMessage<IsPathValidResponse> {
  bool is_valid;
  List<int> invalid_pose_indices;

  static IsPathValidResponse $prototype = IsPathValidResponse();

  // Constructor
  IsPathValidResponse({bool? is_valid, List<int>? invalid_pose_indices})
      : is_valid = is_valid ?? false,
        invalid_pose_indices = invalid_pose_indices ?? const [];

  @override
  String get fullType => 'nav2_msgs/srv/IsPathValid_Response';

  @override
  String get messageDefinition => '''bool is_valid
int32[] invalid_pose_indices''';

  @override
  int getMessageSize() {
    return (1 + 4 + (invalid_pose_indices.length * 4)).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'is_valid': is_valid, 'invalid_pose_indices': invalid_pose_indices};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  IsPathValidResponse fromJson(Map<String, dynamic> jsonMap) {
    return IsPathValidResponse(
        is_valid: jsonMap['is_valid'] as bool,
        invalid_pose_indices:
            (jsonMap['invalid_pose_indices'] as List).cast<int>());
  }
}

class IsPathValid
    extends RosServiceMessage<IsPathValidRequest, IsPathValidResponse> {
  @override
  IsPathValidRequest get request => IsPathValidRequest();

  @override
  IsPathValidResponse get response => IsPathValidResponse();

  @override
  String get fullType => 'nav2_msgs/srv/IsPathValid';

  @override
  String get messageDefinition =>
      '''#Determine if the current path is still valid

nav_msgs/Path path
---
bool is_valid
int32[] invalid_pose_indices''';
}
