// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ManageLifecycleNodesRequest
    extends RosMessage<ManageLifecycleNodesRequest> {
  int command;

  static ManageLifecycleNodesRequest $prototype = ManageLifecycleNodesRequest();

  // Constructor
  ManageLifecycleNodesRequest({int? command}) : command = command ?? 0;

  @override
  String get fullType => 'nav2_msgs/srv/ManageLifecycleNodes_Request';

  @override
  String get messageDefinition => '''uint8 command''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'command': command};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ManageLifecycleNodesRequest fromJson(Map<String, dynamic> jsonMap) {
    return ManageLifecycleNodesRequest(command: jsonMap['command'] as int);
  }
}

class ManageLifecycleNodesResponse
    extends RosMessage<ManageLifecycleNodesResponse> {
  bool success;

  static ManageLifecycleNodesResponse $prototype =
      ManageLifecycleNodesResponse();

  // Constructor
  ManageLifecycleNodesResponse({bool? success}) : success = success ?? false;

  @override
  String get fullType => 'nav2_msgs/srv/ManageLifecycleNodes_Response';

  @override
  String get messageDefinition => '''bool success''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'success': success};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ManageLifecycleNodesResponse fromJson(Map<String, dynamic> jsonMap) {
    return ManageLifecycleNodesResponse(success: jsonMap['success'] as bool);
  }
}

class ManageLifecycleNodes extends RosServiceMessage<
    ManageLifecycleNodesRequest, ManageLifecycleNodesResponse> {
  @override
  ManageLifecycleNodesRequest get request => ManageLifecycleNodesRequest();

  @override
  ManageLifecycleNodesResponse get response => ManageLifecycleNodesResponse();

  @override
  String get fullType => 'nav2_msgs/srv/ManageLifecycleNodes';

  @override
  String get messageDefinition => '''uint8 STARTUP = 0
uint8 PAUSE = 1
uint8 RESUME = 2
uint8 RESET = 3
uint8 SHUTDOWN = 4
uint8 CONFIGURE = 5
uint8 CLEANUP = 6

uint8 command
---
bool success''';
}
