// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ActionTypeRequest extends RosMessage<ActionTypeRequest> {
  late String action;

  static ActionTypeRequest $prototype = ActionTypeRequest();

  ActionTypeRequest({String? action}) : action = action ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ActionType_Request';

  @override
  String get messageDefinition => '''string action''';

  @override
  int getMessageSize() {
    return 4 + action.length;
  }

  @override
  Map<String, dynamic> toJson() => {'action': action};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionTypeRequest fromJson(Map<String, dynamic> jsonMap) {
    return ActionTypeRequest(action: jsonMap['action'] as String);
  }
}

class ActionTypeResponse extends RosMessage<ActionTypeResponse> {
  late String type;

  static ActionTypeResponse $prototype = ActionTypeResponse();

  ActionTypeResponse({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ActionType_Response';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionTypeResponse fromJson(Map<String, dynamic> jsonMap) {
    return ActionTypeResponse(type: jsonMap['type'] as String);
  }
}

class ActionType
    extends RosServiceMessage<ActionTypeRequest, ActionTypeResponse> {
  @override
  ActionTypeRequest get request => ActionTypeRequest();

  @override
  ActionTypeResponse get response => ActionTypeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ActionType';

  @override
  String get messageDefinition => '''
string action
---
string type''';
}
