// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class DeleteParamRequest extends RosMessage<DeleteParamRequest> {
  late String name;

  static DeleteParamRequest $prototype = DeleteParamRequest();

  DeleteParamRequest({String? name}) : name = name ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/DeleteParam_Request';

  @override
  String get messageDefinition => '''string name''';

  @override
  int getMessageSize() {
    return 4 + name.length;
  }

  @override
  Map<String, dynamic> toJson() => {'name': name};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DeleteParamRequest fromJson(Map<String, dynamic> jsonMap) {
    return DeleteParamRequest(name: jsonMap['name'] as String);
  }
}

class DeleteParamResponse extends RosMessage<DeleteParamResponse> {
  late bool successful;
  late String reason;

  static DeleteParamResponse $prototype = DeleteParamResponse();

  DeleteParamResponse({bool? successful, String? reason})
      : successful = successful ?? false,
        reason = reason ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/DeleteParam_Response';

  @override
  String get messageDefinition => '''bool successful
string reason''';

  @override
  int getMessageSize() {
    return 1 + 4 + reason.length;
  }

  @override
  Map<String, dynamic> toJson() => {'successful': successful, 'reason': reason};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DeleteParamResponse fromJson(Map<String, dynamic> jsonMap) {
    return DeleteParamResponse(
        successful: jsonMap['successful'] as bool,
        reason: jsonMap['reason'] as String);
  }
}

class DeleteParam
    extends RosServiceMessage<DeleteParamRequest, DeleteParamResponse> {
  @override
  DeleteParamRequest get request => DeleteParamRequest();

  @override
  DeleteParamResponse get response => DeleteParamResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/DeleteParam';

  @override
  String get messageDefinition => '''
string name
---
bool successful
string reason''';
}
