// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GetParamNamesRequest extends RosMessage<GetParamNamesRequest> {
  static GetParamNamesRequest $prototype = GetParamNamesRequest();

  GetParamNamesRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/GetParamNames_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetParamNamesRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetParamNamesRequest();
  }
}

class GetParamNamesResponse extends RosMessage<GetParamNamesResponse> {
  late List<String> names;

  static GetParamNamesResponse $prototype = GetParamNamesResponse();

  GetParamNamesResponse({List<String>? names}) : names = names ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/GetParamNames_Response';

  @override
  String get messageDefinition => '''string[] names''';

  @override
  int getMessageSize() {
    return 4 + (names.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'names': names};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetParamNamesResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetParamNamesResponse(
        names: (jsonMap['names'] as List<dynamic>).cast<String>().toList());
  }
}

class GetParamNames
    extends RosServiceMessage<GetParamNamesRequest, GetParamNamesResponse> {
  @override
  GetParamNamesRequest get request => GetParamNamesRequest();

  @override
  GetParamNamesResponse get response => GetParamNamesResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/GetParamNames';

  @override
  String get messageDefinition => '''

---
string[] names''';
}
