// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GetParamRequest extends RosMessage<GetParamRequest> {
  late String name;
  late String default_value;

  static GetParamRequest $prototype = GetParamRequest();

  GetParamRequest({String? name, String? default_value})
      : name = name ?? '',
        default_value = default_value ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/GetParam_Request';

  @override
  String get messageDefinition => '''string name
string default_value''';

  @override
  int getMessageSize() {
    return 4 + name.length + 4 + default_value.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'name': name, 'default_value': default_value};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetParamRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetParamRequest(
        name: jsonMap['name'] as String,
        default_value: jsonMap['default_value'] as String);
  }
}

class GetParamResponse extends RosMessage<GetParamResponse> {
  late String value;
  late bool successful;
  late String reason;

  static GetParamResponse $prototype = GetParamResponse();

  GetParamResponse({String? value, bool? successful, String? reason})
      : value = value ?? '',
        successful = successful ?? false,
        reason = reason ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/GetParam_Response';

  @override
  String get messageDefinition => '''string value
bool successful
string reason''';

  @override
  int getMessageSize() {
    return 4 + value.length + 1 + 4 + reason.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'value': value, 'successful': successful, 'reason': reason};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetParamResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetParamResponse(
        value: jsonMap['value'] as String,
        successful: jsonMap['successful'] as bool,
        reason: jsonMap['reason'] as String);
  }
}

class GetParam extends RosServiceMessage<GetParamRequest, GetParamResponse> {
  @override
  GetParamRequest get request => GetParamRequest();

  @override
  GetParamResponse get response => GetParamResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/GetParam';

  @override
  String get messageDefinition => '''
string name
string default_value
---
string value
bool successful
string reason''';
}
