// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GetROSVersionRequest extends RosMessage<GetROSVersionRequest> {
  static GetROSVersionRequest $prototype = GetROSVersionRequest();

  GetROSVersionRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/GetROSVersion_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetROSVersionRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetROSVersionRequest();
  }
}

class GetROSVersionResponse extends RosMessage<GetROSVersionResponse> {
  late int version;
  late String distro;

  static GetROSVersionResponse $prototype = GetROSVersionResponse();

  GetROSVersionResponse({int? version, String? distro})
      : version = version ?? 0,
        distro = distro ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/GetROSVersion_Response';

  @override
  String get messageDefinition => '''uint8 version
string distro''';

  @override
  int getMessageSize() {
    return 1 + 4 + distro.length;
  }

  @override
  Map<String, dynamic> toJson() => {'version': version, 'distro': distro};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetROSVersionResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetROSVersionResponse(
        version: jsonMap['version'] as int,
        distro: jsonMap['distro'] as String);
  }
}

class GetROSVersion
    extends RosServiceMessage<GetROSVersionRequest, GetROSVersionResponse> {
  @override
  GetROSVersionRequest get request => GetROSVersionRequest();

  @override
  GetROSVersionResponse get response => GetROSVersionResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/GetROSVersion';

  @override
  String get messageDefinition => '''

---
uint8 version
string distro''';
}
