// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class GetTimeRequest extends RosMessage<GetTimeRequest> {
  static GetTimeRequest $prototype = GetTimeRequest();

  GetTimeRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/GetTime_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetTimeRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetTimeRequest();
  }
}

class GetTimeResponse extends RosMessage<GetTimeResponse> {
  late builtin_interfaces.Time time;

  static GetTimeResponse $prototype = GetTimeResponse();

  GetTimeResponse({builtin_interfaces.Time? time})
      : time = time ?? builtin_interfaces.Time();

  @override
  String get fullType => 'rosapi_msgs/srv/GetTime_Response';

  @override
  String get messageDefinition => '''builtin_interfaces/Time time''';

  @override
  int getMessageSize() {
    return time.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {'time': time.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetTimeResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetTimeResponse(
        time: builtin_interfaces.Time()
            .fromJson(jsonMap['time'] as Map<String, dynamic>));
  }
}

class GetTime extends RosServiceMessage<GetTimeRequest, GetTimeResponse> {
  @override
  GetTimeRequest get request => GetTimeRequest();

  @override
  GetTimeResponse get response => GetTimeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/GetTime';

  @override
  String get messageDefinition => '''

---
builtin_interfaces/Time time''';
}
