// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class InterfacesRequest extends RosMessage<InterfacesRequest> {
  static InterfacesRequest $prototype = InterfacesRequest();

  InterfacesRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/Interfaces_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  InterfacesRequest fromJson(Map<String, dynamic> jsonMap) {
    return InterfacesRequest();
  }
}

class InterfacesResponse extends RosMessage<InterfacesResponse> {
  late List<String> interfaces;

  static InterfacesResponse $prototype = InterfacesResponse();

  InterfacesResponse({List<String>? interfaces})
      : interfaces = interfaces ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Interfaces_Response';

  @override
  String get messageDefinition => '''string[] interfaces''';

  @override
  int getMessageSize() {
    return 4 + (interfaces.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'interfaces': interfaces};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  InterfacesResponse fromJson(Map<String, dynamic> jsonMap) {
    return InterfacesResponse(
        interfaces:
            (jsonMap['interfaces'] as List<dynamic>).cast<String>().toList());
  }
}

class Interfaces
    extends RosServiceMessage<InterfacesRequest, InterfacesResponse> {
  @override
  InterfacesRequest get request => InterfacesRequest();

  @override
  InterfacesResponse get response => InterfacesResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Interfaces';

  @override
  String get messageDefinition => '''

---
string[] interfaces''';
}
