// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class NodesRequest extends RosMessage<NodesRequest> {
  static NodesRequest $prototype = NodesRequest();

  NodesRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/Nodes_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NodesRequest fromJson(Map<String, dynamic> jsonMap) {
    return NodesRequest();
  }
}

class NodesResponse extends RosMessage<NodesResponse> {
  late List<String> nodes;

  static NodesResponse $prototype = NodesResponse();

  NodesResponse({List<String>? nodes}) : nodes = nodes ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Nodes_Response';

  @override
  String get messageDefinition => '''string[] nodes''';

  @override
  int getMessageSize() {
    return 4 + (nodes.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'nodes': nodes};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NodesResponse fromJson(Map<String, dynamic> jsonMap) {
    return NodesResponse(
        nodes: (jsonMap['nodes'] as List<dynamic>).cast<String>().toList());
  }
}

class Nodes extends RosServiceMessage<NodesRequest, NodesResponse> {
  @override
  NodesRequest get request => NodesRequest();

  @override
  NodesResponse get response => NodesResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Nodes';

  @override
  String get messageDefinition => '''

---
string[] nodes''';
}
