// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class NodeDetailsRequest extends RosMessage<NodeDetailsRequest> {
  late String node;

  static NodeDetailsRequest $prototype = NodeDetailsRequest();

  NodeDetailsRequest({String? node}) : node = node ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/NodeDetails_Request';

  @override
  String get messageDefinition => '''string node''';

  @override
  int getMessageSize() {
    return 4 + node.length;
  }

  @override
  Map<String, dynamic> toJson() => {'node': node};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NodeDetailsRequest fromJson(Map<String, dynamic> jsonMap) {
    return NodeDetailsRequest(node: jsonMap['node'] as String);
  }
}

class NodeDetailsResponse extends RosMessage<NodeDetailsResponse> {
  late List<String> subscribing;
  late List<String> publishing;
  late List<String> services;

  static NodeDetailsResponse $prototype = NodeDetailsResponse();

  NodeDetailsResponse(
      {List<String>? subscribing,
      List<String>? publishing,
      List<String>? services})
      : subscribing = subscribing ?? const [],
        publishing = publishing ?? const [],
        services = services ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/NodeDetails_Response';

  @override
  String get messageDefinition => '''string[] subscribing
string[] publishing
string[] services''';

  @override
  int getMessageSize() {
    return 4 +
        (subscribing.length * 0) +
        4 +
        (publishing.length * 0) +
        4 +
        (services.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {
        'subscribing': subscribing,
        'publishing': publishing,
        'services': services
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NodeDetailsResponse fromJson(Map<String, dynamic> jsonMap) {
    return NodeDetailsResponse(
        subscribing:
            (jsonMap['subscribing'] as List<dynamic>).cast<String>().toList(),
        publishing:
            (jsonMap['publishing'] as List<dynamic>).cast<String>().toList(),
        services:
            (jsonMap['services'] as List<dynamic>).cast<String>().toList());
  }
}

class NodeDetails
    extends RosServiceMessage<NodeDetailsRequest, NodeDetailsResponse> {
  @override
  NodeDetailsRequest get request => NodeDetailsRequest();

  @override
  NodeDetailsResponse get response => NodeDetailsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/NodeDetails';

  @override
  String get messageDefinition => '''
string node
---
string[] subscribing
string[] publishing
string[] services''';
}
