// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ServicesRequest extends RosMessage<ServicesRequest> {
  static ServicesRequest $prototype = ServicesRequest();

  ServicesRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/Services_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServicesRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServicesRequest();
  }
}

class ServicesResponse extends RosMessage<ServicesResponse> {
  late List<String> services;

  static ServicesResponse $prototype = ServicesResponse();

  ServicesResponse({List<String>? services}) : services = services ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Services_Response';

  @override
  String get messageDefinition => '''string[] services''';

  @override
  int getMessageSize() {
    return 4 + (services.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'services': services};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServicesResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServicesResponse(
        services:
            (jsonMap['services'] as List<dynamic>).cast<String>().toList());
  }
}

class Services extends RosServiceMessage<ServicesRequest, ServicesResponse> {
  @override
  ServicesRequest get request => ServicesRequest();

  @override
  ServicesResponse get response => ServicesResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Services';

  @override
  String get messageDefinition => '''

---
string[] services''';
}
