// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ServicesForTypeRequest extends RosMessage<ServicesForTypeRequest> {
  late String type;

  static ServicesForTypeRequest $prototype = ServicesForTypeRequest();

  ServicesForTypeRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServicesForType_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServicesForTypeRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServicesForTypeRequest(type: jsonMap['type'] as String);
  }
}

class ServicesForTypeResponse extends RosMessage<ServicesForTypeResponse> {
  late List<String> services;

  static ServicesForTypeResponse $prototype = ServicesForTypeResponse();

  ServicesForTypeResponse({List<String>? services})
      : services = services ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/ServicesForType_Response';

  @override
  String get messageDefinition => '''string[] services''';

  @override
  int getMessageSize() {
    return 4 + (services.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'services': services};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServicesForTypeResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServicesForTypeResponse(
        services:
            (jsonMap['services'] as List<dynamic>).cast<String>().toList());
  }
}

class ServicesForType
    extends RosServiceMessage<ServicesForTypeRequest, ServicesForTypeResponse> {
  @override
  ServicesForTypeRequest get request => ServicesForTypeRequest();

  @override
  ServicesForTypeResponse get response => ServicesForTypeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ServicesForType';

  @override
  String get messageDefinition => '''
string type
---
string[] services''';
}
