// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ServiceProvidersRequest extends RosMessage<ServiceProvidersRequest> {
  late String service;

  static ServiceProvidersRequest $prototype = ServiceProvidersRequest();

  ServiceProvidersRequest({String? service}) : service = service ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceProviders_Request';

  @override
  String get messageDefinition => '''string service''';

  @override
  int getMessageSize() {
    return 4 + service.length;
  }

  @override
  Map<String, dynamic> toJson() => {'service': service};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceProvidersRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServiceProvidersRequest(service: jsonMap['service'] as String);
  }
}

class ServiceProvidersResponse extends RosMessage<ServiceProvidersResponse> {
  late List<String> providers;

  static ServiceProvidersResponse $prototype = ServiceProvidersResponse();

  ServiceProvidersResponse({List<String>? providers})
      : providers = providers ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceProviders_Response';

  @override
  String get messageDefinition => '''string[] providers''';

  @override
  int getMessageSize() {
    return 4 + (providers.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'providers': providers};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceProvidersResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServiceProvidersResponse(
        providers:
            (jsonMap['providers'] as List<dynamic>).cast<String>().toList());
  }
}

class ServiceProviders extends RosServiceMessage<ServiceProvidersRequest,
    ServiceProvidersResponse> {
  @override
  ServiceProvidersRequest get request => ServiceProvidersRequest();

  @override
  ServiceProvidersResponse get response => ServiceProvidersResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceProviders';

  @override
  String get messageDefinition => '''
string service
---
string[] providers''';
}
