// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/TypeDef.dart';

class ServiceResponseDetailsRequest
    extends RosMessage<ServiceResponseDetailsRequest> {
  late String type;

  static ServiceResponseDetailsRequest $prototype =
      ServiceResponseDetailsRequest();

  ServiceResponseDetailsRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceResponseDetails_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceResponseDetailsRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServiceResponseDetailsRequest(type: jsonMap['type'] as String);
  }
}

class ServiceResponseDetailsResponse
    extends RosMessage<ServiceResponseDetailsResponse> {
  late List<TypeDef> typedefs;

  static ServiceResponseDetailsResponse $prototype =
      ServiceResponseDetailsResponse();

  ServiceResponseDetailsResponse({List<TypeDef>? typedefs})
      : typedefs = typedefs ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceResponseDetails_Response';

  @override
  String get messageDefinition => '''TypeDef[] typedefs''';

  @override
  int getMessageSize() {
    return 4 + typedefs.fold(0, (sum, item) => sum + item.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'typedefs': typedefs.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceResponseDetailsResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServiceResponseDetailsResponse(
        typedefs: (jsonMap['typedefs'] as List<dynamic>)
            .map((item) => TypeDef().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class ServiceResponseDetails extends RosServiceMessage<
    ServiceResponseDetailsRequest, ServiceResponseDetailsResponse> {
  @override
  ServiceResponseDetailsRequest get request => ServiceResponseDetailsRequest();

  @override
  ServiceResponseDetailsResponse get response =>
      ServiceResponseDetailsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceResponseDetails';

  @override
  String get messageDefinition => '''
string type
---
TypeDef[] typedefs''';
}
