// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ServiceNodeRequest extends RosMessage<ServiceNodeRequest> {
  late String service;

  static ServiceNodeRequest $prototype = ServiceNodeRequest();

  ServiceNodeRequest({String? service}) : service = service ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceNode_Request';

  @override
  String get messageDefinition => '''string service''';

  @override
  int getMessageSize() {
    return 4 + service.length;
  }

  @override
  Map<String, dynamic> toJson() => {'service': service};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceNodeRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServiceNodeRequest(service: jsonMap['service'] as String);
  }
}

class ServiceNodeResponse extends RosMessage<ServiceNodeResponse> {
  late String node;

  static ServiceNodeResponse $prototype = ServiceNodeResponse();

  ServiceNodeResponse({String? node}) : node = node ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceNode_Response';

  @override
  String get messageDefinition => '''string node''';

  @override
  int getMessageSize() {
    return 4 + node.length;
  }

  @override
  Map<String, dynamic> toJson() => {'node': node};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceNodeResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServiceNodeResponse(node: jsonMap['node'] as String);
  }
}

class ServiceNode
    extends RosServiceMessage<ServiceNodeRequest, ServiceNodeResponse> {
  @override
  ServiceNodeRequest get request => ServiceNodeRequest();

  @override
  ServiceNodeResponse get response => ServiceNodeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceNode';

  @override
  String get messageDefinition => '''
string service
---
string node''';
}
