// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class SetParamRequest extends RosMessage<SetParamRequest> {
  late String name;
  late String value;

  static SetParamRequest $prototype = SetParamRequest();

  SetParamRequest({String? name, String? value})
      : name = name ?? '',
        value = value ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/SetParam_Request';

  @override
  String get messageDefinition => '''string name
string value''';

  @override
  int getMessageSize() {
    return 4 + name.length + 4 + value.length;
  }

  @override
  Map<String, dynamic> toJson() => {'name': name, 'value': value};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SetParamRequest fromJson(Map<String, dynamic> jsonMap) {
    return SetParamRequest(
        name: jsonMap['name'] as String, value: jsonMap['value'] as String);
  }
}

class SetParamResponse extends RosMessage<SetParamResponse> {
  late bool successful;
  late String reason;

  static SetParamResponse $prototype = SetParamResponse();

  SetParamResponse({bool? successful, String? reason})
      : successful = successful ?? false,
        reason = reason ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/SetParam_Response';

  @override
  String get messageDefinition => '''bool successful
string reason''';

  @override
  int getMessageSize() {
    return 1 + 4 + reason.length;
  }

  @override
  Map<String, dynamic> toJson() => {'successful': successful, 'reason': reason};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SetParamResponse fromJson(Map<String, dynamic> jsonMap) {
    return SetParamResponse(
        successful: jsonMap['successful'] as bool,
        reason: jsonMap['reason'] as String);
  }
}

class SetParam extends RosServiceMessage<SetParamRequest, SetParamResponse> {
  @override
  SetParamRequest get request => SetParamRequest();

  @override
  SetParamResponse get response => SetParamResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/SetParam';

  @override
  String get messageDefinition => '''
string name
string value
---
bool successful
string reason''';
}
