// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class TopicsRequest extends RosMessage<TopicsRequest> {
  static TopicsRequest $prototype = TopicsRequest();

  TopicsRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/Topics_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsRequest fromJson(Map<String, dynamic> jsonMap) {
    return TopicsRequest();
  }
}

class TopicsResponse extends RosMessage<TopicsResponse> {
  late List<String> topics;
  late List<String> types;

  static TopicsResponse $prototype = TopicsResponse();

  TopicsResponse({List<String>? topics, List<String>? types})
      : topics = topics ?? const [],
        types = types ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Topics_Response';

  @override
  String get messageDefinition => '''string[] topics
string[] types''';

  @override
  int getMessageSize() {
    return 4 + (topics.length * 0) + 4 + (types.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'topics': topics, 'types': types};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsResponse fromJson(Map<String, dynamic> jsonMap) {
    return TopicsResponse(
        topics: (jsonMap['topics'] as List<dynamic>).cast<String>().toList(),
        types: (jsonMap['types'] as List<dynamic>).cast<String>().toList());
  }
}

class Topics extends RosServiceMessage<TopicsRequest, TopicsResponse> {
  @override
  TopicsRequest get request => TopicsRequest();

  @override
  TopicsResponse get response => TopicsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Topics';

  @override
  String get messageDefinition => '''

---
string[] topics
string[] types''';
}
