// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class TopicTypeRequest extends RosMessage<TopicTypeRequest> {
  late String topic;

  static TopicTypeRequest $prototype = TopicTypeRequest();

  TopicTypeRequest({String? topic}) : topic = topic ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/TopicType_Request';

  @override
  String get messageDefinition => '''string topic''';

  @override
  int getMessageSize() {
    return 4 + topic.length;
  }

  @override
  Map<String, dynamic> toJson() => {'topic': topic};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicTypeRequest fromJson(Map<String, dynamic> jsonMap) {
    return TopicTypeRequest(topic: jsonMap['topic'] as String);
  }
}

class TopicTypeResponse extends RosMessage<TopicTypeResponse> {
  late String type;

  static TopicTypeResponse $prototype = TopicTypeResponse();

  TopicTypeResponse({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/TopicType_Response';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicTypeResponse fromJson(Map<String, dynamic> jsonMap) {
    return TopicTypeResponse(type: jsonMap['type'] as String);
  }
}

class TopicType extends RosServiceMessage<TopicTypeRequest, TopicTypeResponse> {
  @override
  TopicTypeRequest get request => TopicTypeRequest();

  @override
  TopicTypeResponse get response => TopicTypeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/TopicType';

  @override
  String get messageDefinition => '''
string topic
---
string type''';
}
