// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class TopicsForTypeRequest extends RosMessage<TopicsForTypeRequest> {
  late String type;

  static TopicsForTypeRequest $prototype = TopicsForTypeRequest();

  TopicsForTypeRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsForType_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsForTypeRequest fromJson(Map<String, dynamic> jsonMap) {
    return TopicsForTypeRequest(type: jsonMap['type'] as String);
  }
}

class TopicsForTypeResponse extends RosMessage<TopicsForTypeResponse> {
  late List<String> topics;

  static TopicsForTypeResponse $prototype = TopicsForTypeResponse();

  TopicsForTypeResponse({List<String>? topics}) : topics = topics ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsForType_Response';

  @override
  String get messageDefinition => '''string[] topics''';

  @override
  int getMessageSize() {
    return 4 + (topics.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'topics': topics};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsForTypeResponse fromJson(Map<String, dynamic> jsonMap) {
    return TopicsForTypeResponse(
        topics: (jsonMap['topics'] as List<dynamic>).cast<String>().toList());
  }
}

class TopicsForType
    extends RosServiceMessage<TopicsForTypeRequest, TopicsForTypeResponse> {
  @override
  TopicsForTypeRequest get request => TopicsForTypeRequest();

  @override
  TopicsForTypeResponse get response => TopicsForTypeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsForType';

  @override
  String get messageDefinition => '''
string type
---
string[] topics''';
}
