// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class TopicsAndRawTypesRequest extends RosMessage<TopicsAndRawTypesRequest> {
  static TopicsAndRawTypesRequest $prototype = TopicsAndRawTypesRequest();

  TopicsAndRawTypesRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsAndRawTypes_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsAndRawTypesRequest fromJson(Map<String, dynamic> jsonMap) {
    return TopicsAndRawTypesRequest();
  }
}

class TopicsAndRawTypesResponse extends RosMessage<TopicsAndRawTypesResponse> {
  late List<String> topics;
  late List<String> types;
  late List<String> typedefs_full_text;

  static TopicsAndRawTypesResponse $prototype = TopicsAndRawTypesResponse();

  TopicsAndRawTypesResponse(
      {List<String>? topics,
      List<String>? types,
      List<String>? typedefs_full_text})
      : topics = topics ?? const [],
        types = types ?? const [],
        typedefs_full_text = typedefs_full_text ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsAndRawTypes_Response';

  @override
  String get messageDefinition => '''string[] topics
string[] types
string[] typedefs_full_text''';

  @override
  int getMessageSize() {
    return 4 +
        (topics.length * 0) +
        4 +
        (types.length * 0) +
        4 +
        (typedefs_full_text.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {
        'topics': topics,
        'types': types,
        'typedefs_full_text': typedefs_full_text
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TopicsAndRawTypesResponse fromJson(Map<String, dynamic> jsonMap) {
    return TopicsAndRawTypesResponse(
        topics: (jsonMap['topics'] as List<dynamic>).cast<String>().toList(),
        types: (jsonMap['types'] as List<dynamic>).cast<String>().toList(),
        typedefs_full_text: (jsonMap['typedefs_full_text'] as List<dynamic>)
            .cast<String>()
            .toList());
  }
}

class TopicsAndRawTypes extends RosServiceMessage<TopicsAndRawTypesRequest,
    TopicsAndRawTypesResponse> {
  @override
  TopicsAndRawTypesRequest get request => TopicsAndRawTypesRequest();

  @override
  TopicsAndRawTypesResponse get response => TopicsAndRawTypesResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/TopicsAndRawTypes';

  @override
  String get messageDefinition => '''

---
string[] topics
string[] types
string[] typedefs_full_text''';
}
