// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'GoalInfo.dart';

class GoalStatus extends RosMessage<GoalStatus> {
  GoalInfo goal_info;
  int status;

  static GoalStatus $prototype = GoalStatus();

  // Constructor
  GoalStatus({GoalInfo? goal_info, int? status})
      : goal_info = goal_info ?? GoalInfo(),
        status = status ?? 0;

  @override
  String get fullType => 'action_msgs/msg/GoalStatus';

  @override
  String get messageDefinition => '''GoalInfo goal_info
int8 status''';

  @override
  int getMessageSize() {
    return (goal_info.getMessageSize() + 1).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'goal_info': goal_info.toJson(), 'status': status};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GoalStatus fromJson(Map<String, dynamic> jsonMap) {
    return GoalStatus(
        goal_info:
            GoalInfo().fromJson(jsonMap['goal_info'] as Map<String, dynamic>),
        status: jsonMap['status'] as int);
  }
}
