// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:sensor_msgs/msg.dart' as sensor_msgs;

class GetPointMapROIRequest extends RosMessage<GetPointMapROIRequest> {
  double x;
  double y;
  double z;

  static GetPointMapROIRequest $prototype = GetPointMapROIRequest();

  // Constructor
  GetPointMapROIRequest({double? x, double? y, double? z})
      : x = x ?? 0.0,
        y = y ?? 0.0,
        z = z ?? 0.0;

  @override
  String get fullType => 'map_msgs/srv/GetPointMapROI_Request';

  @override
  String get messageDefinition => '''float64 x
float64 y
float64 z''';

  @override
  int getMessageSize() {
    return (8 + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'x': x, 'y': y, 'z': z};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPointMapROIRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetPointMapROIRequest(
        x: jsonMap['x'] as double,
        y: jsonMap['y'] as double,
        z: jsonMap['z'] as double);
  }
}

class GetPointMapROIResponse extends RosMessage<GetPointMapROIResponse> {
  sensor_msgs.PointCloud2 sub_map;

  static GetPointMapROIResponse $prototype = GetPointMapROIResponse();

  // Constructor
  GetPointMapROIResponse({sensor_msgs.PointCloud2? sub_map})
      : sub_map = sub_map ?? sensor_msgs.PointCloud2();

  @override
  String get fullType => 'map_msgs/srv/GetPointMapROI_Response';

  @override
  String get messageDefinition => '''sensor_msgs/PointCloud2 sub_map''';

  @override
  int getMessageSize() {
    return (sub_map.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'sub_map': sub_map.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPointMapROIResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetPointMapROIResponse(
        sub_map: sensor_msgs.PointCloud2()
            .fromJson(jsonMap['sub_map'] as Map<String, dynamic>));
  }
}

class GetPointMapROI
    extends RosServiceMessage<GetPointMapROIRequest, GetPointMapROIResponse> {
  @override
  GetPointMapROIRequest get request => GetPointMapROIRequest();

  @override
  GetPointMapROIResponse get response => GetPointMapROIResponse();

  @override
  String get fullType => 'map_msgs/srv/GetPointMapROI';

  @override
  String get messageDefinition => '''float64 x
float64 y
float64 z
float64 r    # if != 0, circular ROI of radius r
float64 l_x  # if r == 0, length of AABB on x
float64 l_y  # if r == 0, length of AABB on y
float64 l_z  # if r == 0, length of AABB on z
---
sensor_msgs/PointCloud2 sub_map''';
}
