// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/ProjectedMapInfo.dart';

class ProjectedMapsInfoRequest extends RosMessage<ProjectedMapsInfoRequest> {
  List<ProjectedMapInfo> projected_maps_info;

  static ProjectedMapsInfoRequest $prototype = ProjectedMapsInfoRequest();

  // Constructor
  ProjectedMapsInfoRequest({List<ProjectedMapInfo>? projected_maps_info})
      : projected_maps_info = projected_maps_info ?? const [];

  @override
  String get fullType => 'map_msgs/srv/ProjectedMapsInfo_Request';

  @override
  String get messageDefinition =>
      '''map_msgs/ProjectedMapInfo[] projected_maps_info''';

  @override
  int getMessageSize() {
    return (4 +
            projected_maps_info.fold(
                0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'projected_maps_info':
            projected_maps_info.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ProjectedMapsInfoRequest fromJson(Map<String, dynamic> jsonMap) {
    return ProjectedMapsInfoRequest(
        projected_maps_info: (jsonMap['projected_maps_info'] as List)
            .map((item) =>
                ProjectedMapInfo().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class ProjectedMapsInfoResponse extends RosMessage<ProjectedMapsInfoResponse> {
  static ProjectedMapsInfoResponse $prototype = ProjectedMapsInfoResponse();

  // Constructor
  ProjectedMapsInfoResponse();

  @override
  String get fullType => 'map_msgs/srv/ProjectedMapsInfo_Response';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ProjectedMapsInfoResponse fromJson(Map<String, dynamic> jsonMap) {
    return ProjectedMapsInfoResponse();
  }
}

class ProjectedMapsInfo extends RosServiceMessage<ProjectedMapsInfoRequest,
    ProjectedMapsInfoResponse> {
  @override
  ProjectedMapsInfoRequest get request => ProjectedMapsInfoRequest();

  @override
  ProjectedMapsInfoResponse get response => ProjectedMapsInfoResponse();

  @override
  String get fullType => 'map_msgs/srv/ProjectedMapsInfo';

  @override
  String get messageDefinition =>
      '''map_msgs/ProjectedMapInfo[] projected_maps_info
---
''';
}
