// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class MapMetaData extends RosMessage<MapMetaData> {
  builtin_interfaces.Time map_load_time;
  double resolution;
  int width;
  int height;
  geometry_msgs.Pose origin;

  static MapMetaData $prototype = MapMetaData();

  // Constructor
  MapMetaData(
      {builtin_interfaces.Time? map_load_time,
      double? resolution,
      int? width,
      int? height,
      geometry_msgs.Pose? origin})
      : map_load_time = map_load_time ?? builtin_interfaces.Time(),
        resolution = resolution ?? 0.0,
        width = width ?? 0,
        height = height ?? 0,
        origin = origin ?? geometry_msgs.Pose();

  @override
  String get fullType => 'nav_msgs/msg/MapMetaData';

  @override
  String get messageDefinition => '''builtin_interfaces/Time map_load_time
float32 resolution
uint32 width
uint32 height
geometry_msgs/Pose origin''';

  @override
  int getMessageSize() {
    return (map_load_time.getMessageSize() +
            4 +
            4 +
            4 +
            origin.getMessageSize())
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'map_load_time': map_load_time.toJson(),
        'resolution': resolution,
        'width': width,
        'height': height,
        'origin': origin.toJson()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MapMetaData fromJson(Map<String, dynamic> jsonMap) {
    return MapMetaData(
        map_load_time: builtin_interfaces.Time()
            .fromJson(jsonMap['map_load_time'] as Map<String, dynamic>),
        resolution: jsonMap['resolution'] as double,
        width: jsonMap['width'] as int,
        height: jsonMap['height'] as int,
        origin: geometry_msgs.Pose()
            .fromJson(jsonMap['origin'] as Map<String, dynamic>));
  }
}
