// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import '../msg/TF2Error.dart';

class LookupTransformGoal extends RosMessage<LookupTransformGoal> {
  late String target_frame;
  late String source_frame;
  late builtin_interfaces.Time source_time;
  late builtin_interfaces.Duration timeout;
  late builtin_interfaces.Time target_time;
  late String fixed_frame;
  late bool advanced;

  static LookupTransformGoal $prototype = LookupTransformGoal();

  LookupTransformGoal(
      {String? target_frame,
      String? source_frame,
      builtin_interfaces.Time? source_time,
      builtin_interfaces.Duration? timeout,
      builtin_interfaces.Time? target_time,
      String? fixed_frame,
      bool? advanced})
      : target_frame = target_frame ?? '',
        source_frame = source_frame ?? '',
        source_time = source_time ?? builtin_interfaces.Time(),
        timeout = timeout ?? builtin_interfaces.Duration(),
        target_time = target_time ?? builtin_interfaces.Time(),
        fixed_frame = fixed_frame ?? '',
        advanced = advanced ?? false;

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_Goal';

  @override
  String get messageDefinition => '''string target_frame
string source_frame
builtin_interfaces/Time source_time
builtin_interfaces/Duration timeout
builtin_interfaces/Time target_time
string fixed_frame
bool advanced''';

  @override
  int getMessageSize() {
    return 4 +
        target_frame.length +
        4 +
        source_frame.length +
        (source_time.getMessageSize()) +
        (timeout.getMessageSize()) +
        (target_time.getMessageSize()) +
        4 +
        fixed_frame.length +
        1;
  }

  @override
  Map<String, dynamic> toJson() => {
        'target_frame': target_frame,
        'source_frame': source_frame,
        'source_time': source_time.toJson(),
        'timeout': timeout.toJson(),
        'target_time': target_time.toJson(),
        'fixed_frame': fixed_frame,
        'advanced': advanced
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformGoal fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformGoal(
        target_frame: jsonMap['target_frame'] as String,
        source_frame: jsonMap['source_frame'] as String,
        source_time: builtin_interfaces.Time()
            .fromJson(jsonMap['source_time'] as Map<String, dynamic>),
        timeout: builtin_interfaces.Duration()
            .fromJson(jsonMap['timeout'] as Map<String, dynamic>),
        target_time: builtin_interfaces.Time()
            .fromJson(jsonMap['target_time'] as Map<String, dynamic>),
        fixed_frame: jsonMap['fixed_frame'] as String,
        advanced: jsonMap['advanced'] as bool);
  }
}

class LookupTransformResult extends RosMessage<LookupTransformResult> {
  late geometry_msgs.TransformStamped transform;
  late TF2Error error;

  static LookupTransformResult $prototype = LookupTransformResult();

  LookupTransformResult(
      {geometry_msgs.TransformStamped? transform, TF2Error? error})
      : transform = transform ?? geometry_msgs.TransformStamped(),
        error = error ?? TF2Error();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_Result';

  @override
  String get messageDefinition => '''geometry_msgs/TransformStamped transform
tf2_msgs/TF2Error error''';

  @override
  int getMessageSize() {
    return (transform.getMessageSize()) + (error.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'transform': transform.toJson(), 'error': error.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformResult fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformResult(
        transform: geometry_msgs.TransformStamped()
            .fromJson(jsonMap['transform'] as Map<String, dynamic>),
        error: TF2Error().fromJson(jsonMap['error'] as Map<String, dynamic>));
  }
}

class LookupTransformFeedback extends RosMessage<LookupTransformFeedback> {
  static LookupTransformFeedback $prototype = LookupTransformFeedback();

  LookupTransformFeedback();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_Feedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformFeedback fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformFeedback();
  }
}

class LookupTransformActionGoal
    extends RosActionGoal<LookupTransformGoal, LookupTransformActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late LookupTransformGoal goal;

  static LookupTransformActionGoal $prototype = LookupTransformActionGoal();

  LookupTransformActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    LookupTransformGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? LookupTransformGoal();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_ActionGoal';

  @override
  String get messageDefinition => '''
std_msgs/Header header
actionlib_msgs/GoalID goal_id
tf2_msgs/action/LookupTransform_Goal goal''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: LookupTransformGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class LookupTransformActionResult extends RosActionResult<LookupTransformResult,
    LookupTransformActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late LookupTransformResult result;

  static LookupTransformActionResult $prototype = LookupTransformActionResult();

  LookupTransformActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    LookupTransformResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? LookupTransformResult();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_ActionResult';

  @override
  String get messageDefinition => '''
std_msgs/Header header
actionlib_msgs/GoalStatus status
tf2_msgs/action/LookupTransform_Result result''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformActionResult fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: LookupTransformResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class LookupTransformActionFeedback extends RosActionFeedback<
    LookupTransformFeedback, LookupTransformActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late LookupTransformFeedback feedback;

  static LookupTransformActionFeedback $prototype =
      LookupTransformActionFeedback();

  LookupTransformActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    LookupTransformFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? LookupTransformFeedback();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform_ActionFeedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LookupTransformActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return LookupTransformActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: LookupTransformFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class LookupTransform extends RosActionMessage<
    LookupTransformGoal,
    LookupTransformActionGoal,
    LookupTransformFeedback,
    LookupTransformActionFeedback,
    LookupTransformResult,
    LookupTransformActionResult> {
  @override
  LookupTransformActionGoal get actionGoal => LookupTransformActionGoal();

  @override
  LookupTransformActionFeedback get actionFeedback =>
      LookupTransformActionFeedback();

  @override
  LookupTransformActionResult get actionResult => LookupTransformActionResult();

  @override
  LookupTransformGoal get goal => LookupTransformGoal();

  @override
  LookupTransformFeedback get feedback => LookupTransformFeedback();

  @override
  LookupTransformResult get result => LookupTransformResult();

  @override
  String get fullType => 'tf2_msgs/action/LookupTransform';

  @override
  String get messageDefinition => '''
Goal:
string target_frame
string source_frame
builtin_interfaces/Time source_time
builtin_interfaces/Duration timeout
builtin_interfaces/Time target_time
string fixed_frame
bool advanced
---
Result:
geometry_msgs/TransformStamped transform
tf2_msgs/TF2Error error
---
Feedback:
''';
}
