// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:nav_msgs/msg.dart' as nav_msgs;

class ProjectedMap extends RosMessage<ProjectedMap> {
  nav_msgs.OccupancyGrid map;
  double min_z;
  double max_z;

  static ProjectedMap $prototype = ProjectedMap();

  // Constructor
  ProjectedMap({nav_msgs.OccupancyGrid? map, double? min_z, double? max_z})
      : map = map ?? nav_msgs.OccupancyGrid(),
        min_z = min_z ?? 0.0,
        max_z = max_z ?? 0.0;

  @override
  String get fullType => 'map_msgs/msg/ProjectedMap';

  @override
  String get messageDefinition => '''nav_msgs/OccupancyGrid map
float64 min_z
float64 max_z''';

  @override
  int getMessageSize() {
    return (map.getMessageSize() + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'map': map.toJson(), 'min_z': min_z, 'max_z': max_z};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ProjectedMap fromJson(Map<String, dynamic> jsonMap) {
    return ProjectedMap(
        map: nav_msgs.OccupancyGrid()
            .fromJson(jsonMap['map'] as Map<String, dynamic>),
        min_z: jsonMap['min_z'] as double,
        max_z: jsonMap['max_z'] as double);
  }
}
