// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class DeleteMapRequest extends RosMessage<DeleteMapRequest> {
  late String map_name;
  late String map_path;

  static DeleteMapRequest $prototype = DeleteMapRequest();

  DeleteMapRequest({String? map_name, String? map_path})
      : map_name = map_name ?? '',
        map_path = map_path ?? '';

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/DeleteMap_Request';

  @override
  String get messageDefinition => '''string map_name
string map_path''';

  @override
  int getMessageSize() {
    return 4 + map_name.length + 4 + map_path.length;
  }

  @override
  Map<String, dynamic> toJson() => {'map_name': map_name, 'map_path': map_path};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DeleteMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return DeleteMapRequest(
        map_name: jsonMap['map_name'] as String,
        map_path: jsonMap['map_path'] as String);
  }
}

class DeleteMapResponse extends RosMessage<DeleteMapResponse> {
  late bool success;
  late String message;

  static DeleteMapResponse $prototype = DeleteMapResponse();

  DeleteMapResponse({bool? success, String? message})
      : success = success ?? false,
        message = message ?? '';

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/DeleteMap_Response';

  @override
  String get messageDefinition => '''bool success
string message''';

  @override
  int getMessageSize() {
    return 1 + 4 + message.length;
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DeleteMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return DeleteMapResponse(
        success: jsonMap['success'] as bool,
        message: jsonMap['message'] as String);
  }
}

class DeleteMap extends RosServiceMessage<DeleteMapRequest, DeleteMapResponse> {
  @override
  DeleteMapRequest get request => DeleteMapRequest();

  @override
  DeleteMapResponse get response => DeleteMapResponse();

  @override
  String get fullType => 'nav2_mission_planner_interfaces/srv/DeleteMap';

  @override
  String get messageDefinition => '''
string map_name
string map_path
---
bool success
string message''';
}
