// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GetMapListRequest extends RosMessage<GetMapListRequest> {
  late String path;

  static GetMapListRequest $prototype = GetMapListRequest();

  GetMapListRequest({String? path}) : path = path ?? '';

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/GetMapList_Request';

  @override
  String get messageDefinition => '''string path''';

  @override
  int getMessageSize() {
    return 4 + path.length;
  }

  @override
  Map<String, dynamic> toJson() => {'path': path};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetMapListRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetMapListRequest(path: jsonMap['path'] as String);
  }
}

class GetMapListResponse extends RosMessage<GetMapListResponse> {
  late bool success;
  late String message;
  late List<String> maplist;

  static GetMapListResponse $prototype = GetMapListResponse();

  GetMapListResponse({bool? success, String? message, List<String>? maplist})
      : success = success ?? false,
        message = message ?? '',
        maplist = maplist ?? const [];

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/GetMapList_Response';

  @override
  String get messageDefinition => '''bool success
string message
string[] maplist''';

  @override
  int getMessageSize() {
    return 1 + 4 + message.length + 4 + (maplist.length * 0);
  }

  @override
  Map<String, dynamic> toJson() =>
      {'success': success, 'message': message, 'maplist': maplist};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetMapListResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetMapListResponse(
        success: jsonMap['success'] as bool,
        message: jsonMap['message'] as String,
        maplist: (jsonMap['maplist'] as List<dynamic>).cast<String>().toList());
  }
}

class GetMapList
    extends RosServiceMessage<GetMapListRequest, GetMapListResponse> {
  @override
  GetMapListRequest get request => GetMapListRequest();

  @override
  GetMapListResponse get response => GetMapListResponse();

  @override
  String get fullType => 'nav2_mission_planner_interfaces/srv/GetMapList';

  @override
  String get messageDefinition => '''
string path
---
bool success
string message
string[] maplist''';
}
