// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class StopLaunchRequest extends RosMessage<StopLaunchRequest> {
  late String unique_id;

  static StopLaunchRequest $prototype = StopLaunchRequest();

  StopLaunchRequest({String? unique_id}) : unique_id = unique_id ?? '';

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/StopLaunch_Request';

  @override
  String get messageDefinition => '''string unique_id''';

  @override
  int getMessageSize() {
    return 4 + unique_id.length;
  }

  @override
  Map<String, dynamic> toJson() => {'unique_id': unique_id};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  StopLaunchRequest fromJson(Map<String, dynamic> jsonMap) {
    return StopLaunchRequest(unique_id: jsonMap['unique_id'] as String);
  }
}

class StopLaunchResponse extends RosMessage<StopLaunchResponse> {
  late bool success;
  late String message;

  static StopLaunchResponse $prototype = StopLaunchResponse();

  StopLaunchResponse({bool? success, String? message})
      : success = success ?? false,
        message = message ?? '';

  @override
  String get fullType =>
      'nav2_mission_planner_interfaces/srv/StopLaunch_Response';

  @override
  String get messageDefinition => '''bool success
string message''';

  @override
  int getMessageSize() {
    return 1 + 4 + message.length;
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  StopLaunchResponse fromJson(Map<String, dynamic> jsonMap) {
    return StopLaunchResponse(
        success: jsonMap['success'] as bool,
        message: jsonMap['message'] as String);
  }
}

class StopLaunch
    extends RosServiceMessage<StopLaunchRequest, StopLaunchResponse> {
  @override
  StopLaunchRequest get request => StopLaunchRequest();

  @override
  StopLaunchResponse get response => StopLaunchResponse();

  @override
  String get fullType => 'nav2_mission_planner_interfaces/srv/StopLaunch';

  @override
  String get messageDefinition => '''
string unique_id
---
bool success
string message''';
}
