// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class NavGoalGoal extends RosMessage<NavGoalGoal> {
  late geometry_msgs.PoseStamped goal_pose;

  static NavGoalGoal $prototype = NavGoalGoal();

  NavGoalGoal({geometry_msgs.PoseStamped? goal_pose}) : goal_pose = goal_pose ?? geometry_msgs.PoseStamped();

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_Goal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped goal_pose''';

  @override
  int getMessageSize() {
    return (goal_pose.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() => {'goal_pose': goal_pose.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalGoal(
        goal_pose: geometry_msgs.PoseStamped().fromJson(jsonMap['goal_pose'] as Map<String, dynamic>));
  }
}

class NavGoalResult extends RosMessage<NavGoalResult> {
  late bool success;
  late String message;

  static NavGoalResult $prototype = NavGoalResult();

  NavGoalResult({bool? success, String? message})
      : success = success ?? false,
        message = message ?? '';

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_Result';

  @override
  String get messageDefinition => '''bool success
string message''';

  @override
  int getMessageSize() {
    return 1 + 4 + message.length;
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalResult fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalResult(success: jsonMap['success'] as bool, message: jsonMap['message'] as String);
  }
}

class NavGoalFeedback extends RosMessage<NavGoalFeedback> {
  late double distance_remaining;
  late double estimated_time_remaining;
  late double navigation_time;
  late String current_status;

  static NavGoalFeedback $prototype = NavGoalFeedback();

  NavGoalFeedback(
      {double? distance_remaining,
      double? estimated_time_remaining,
      double? navigation_time,
      String? current_status})
      : distance_remaining = distance_remaining ?? 0.0,
        estimated_time_remaining = estimated_time_remaining ?? 0.0,
        navigation_time = navigation_time ?? 0.0,
        current_status = current_status ?? '';

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_Feedback';

  @override
  String get messageDefinition => '''float32 distance_remaining
float32 estimated_time_remaining
float32 navigation_time
string current_status''';

  @override
  int getMessageSize() {
    return 4 + 4 + 4 + 4 + current_status.length;
  }

  @override
  Map<String, dynamic> toJson() => {
        'distance_remaining': distance_remaining,
        'estimated_time_remaining': estimated_time_remaining,
        'navigation_time': navigation_time,
        'current_status': current_status
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalFeedback(
        distance_remaining: jsonMap['distance_remaining'] as double,
        estimated_time_remaining: jsonMap['estimated_time_remaining'] as double,
        navigation_time: jsonMap['navigation_time'] as double,
        current_status: jsonMap['current_status'] as String);
  }
}

class NavGoalActionGoal extends RosActionGoal<NavGoalGoal, NavGoalActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late NavGoalGoal goal;

  static NavGoalActionGoal $prototype = NavGoalActionGoal();

  NavGoalActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    NavGoalGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? NavGoalGoal();

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_ActionGoal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped goal_pose''';

  @override
  int getMessageSize() {
    return header.getMessageSize() + goal_id.getMessageSize() + goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalActionGoal(
      header: std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID().fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: NavGoalGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class NavGoalActionResult extends RosActionResult<NavGoalResult, NavGoalActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late NavGoalResult result;

  static NavGoalActionResult $prototype = NavGoalActionResult();

  NavGoalActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavGoalResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? NavGoalResult();

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_ActionResult';

  @override
  String get messageDefinition => '''bool success
string message''';

  @override
  int getMessageSize() {
    return header.getMessageSize() + status.getMessageSize() + result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalActionResult fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalActionResult(
      header: std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus().fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: NavGoalResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class NavGoalActionFeedback extends RosActionFeedback<NavGoalFeedback, NavGoalActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late NavGoalFeedback feedback;

  static NavGoalActionFeedback $prototype = NavGoalActionFeedback();

  NavGoalActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavGoalFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? NavGoalFeedback();

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal_ActionFeedback';

  @override
  String get messageDefinition => '''float32 distance_remaining
float32 estimated_time_remaining
float32 navigation_time
string current_status''';

  @override
  int getMessageSize() {
    return header.getMessageSize() + status.getMessageSize() + feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavGoalActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavGoalActionFeedback(
      header: std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus().fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: NavGoalFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class NavGoal extends RosActionMessage<NavGoalGoal, NavGoalActionGoal, NavGoalFeedback, NavGoalActionFeedback,
    NavGoalResult, NavGoalActionResult> {
  @override
  NavGoalActionGoal get actionGoal => NavGoalActionGoal();

  @override
  NavGoalActionFeedback get actionFeedback => NavGoalActionFeedback();

  @override
  NavGoalActionResult get actionResult => NavGoalActionResult();

  @override
  NavGoalGoal get goal => NavGoalGoal();

  @override
  NavGoalFeedback get feedback => NavGoalFeedback();

  @override
  NavGoalResult get result => NavGoalResult();

  @override
  String get fullType => 'navpromini_launch_manager_interfaces/action/NavGoal';

  @override
  String get messageDefinition => '''
Goal:
geometry_msgs/PoseStamped goal_pose
---
Result:
bool success
string message
---
Feedback:
float32 distance_remaining
float32 estimated_time_remaining
float32 navigation_time
string current_status''';
}
