// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import '../msg/OccupancyGrid.dart';

class GetMapRequest extends RosMessage<GetMapRequest> {
  static GetMapRequest $prototype = GetMapRequest();

  // Constructor
  GetMapRequest();

  @override
  String get fullType => 'nav_msgs/srv/GetMap_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetMapRequest();
  }
}

class GetMapResponse extends RosMessage<GetMapResponse> {
  OccupancyGrid map;

  static GetMapResponse $prototype = GetMapResponse();

  // Constructor
  GetMapResponse({OccupancyGrid? map}) : map = map ?? OccupancyGrid();

  @override
  String get fullType => 'nav_msgs/srv/GetMap_Response';

  @override
  String get messageDefinition => '''OccupancyGrid map''';

  @override
  int getMessageSize() {
    return (map.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'map': map.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetMapResponse(
        map: OccupancyGrid().fromJson(jsonMap['map'] as Map<String, dynamic>));
  }
}

class GetMap extends RosServiceMessage<GetMapRequest, GetMapResponse> {
  @override
  GetMapRequest get request => GetMapRequest();

  @override
  GetMapResponse get response => GetMapResponse();

  @override
  String get fullType => 'nav_msgs/srv/GetMap';

  @override
  String get messageDefinition => '''# Get the map as a nav_msgs/OccupancyGrid
---
# The current map hosted by this map service.
OccupancyGrid map''';
}
