// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import '../msg/Path.dart';

class GetPlanRequest extends RosMessage<GetPlanRequest> {
  geometry_msgs.PoseStamped start;
  geometry_msgs.PoseStamped goal;
  double tolerance;

  static GetPlanRequest $prototype = GetPlanRequest();

  // Constructor
  GetPlanRequest(
      {geometry_msgs.PoseStamped? start,
      geometry_msgs.PoseStamped? goal,
      double? tolerance})
      : start = start ?? geometry_msgs.PoseStamped(),
        goal = goal ?? geometry_msgs.PoseStamped(),
        tolerance = tolerance ?? 0.0;

  @override
  String get fullType => 'nav_msgs/srv/GetPlan_Request';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped start
geometry_msgs/PoseStamped goal
float32 tolerance''';

  @override
  int getMessageSize() {
    return (start.getMessageSize() + goal.getMessageSize() + 4).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'start': start.toJson(), 'goal': goal.toJson(), 'tolerance': tolerance};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPlanRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetPlanRequest(
        start: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['start'] as Map<String, dynamic>),
        goal: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['goal'] as Map<String, dynamic>),
        tolerance: jsonMap['tolerance'] as double);
  }
}

class GetPlanResponse extends RosMessage<GetPlanResponse> {
  Path plan;

  static GetPlanResponse $prototype = GetPlanResponse();

  // Constructor
  GetPlanResponse({Path? plan}) : plan = plan ?? Path();

  @override
  String get fullType => 'nav_msgs/srv/GetPlan_Response';

  @override
  String get messageDefinition => '''Path plan''';

  @override
  int getMessageSize() {
    return (plan.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'plan': plan.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPlanResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetPlanResponse(
        plan: Path().fromJson(jsonMap['plan'] as Map<String, dynamic>));
  }
}

class GetPlan extends RosServiceMessage<GetPlanRequest, GetPlanResponse> {
  @override
  GetPlanRequest get request => GetPlanRequest();

  @override
  GetPlanResponse get response => GetPlanResponse();

  @override
  String get fullType => 'nav_msgs/srv/GetPlan';

  @override
  String get messageDefinition =>
      '''# Get a plan from the current position to the goal Pose

# The start pose for the plan
geometry_msgs/PoseStamped start

# The final pose of the goal position
geometry_msgs/PoseStamped goal

# If the goal is obstructed, how many meters the planner can
# relax the constraint in x and y before failing.
float32 tolerance
---
# Array of poses from start to goal if one was successfully found.
Path plan''';
}
