// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class BatteryState extends RosMessage<BatteryState> {
  std_msgs.Header header;
  double voltage;
  double temperature;
  double current;
  double charge;
  double capacity;
  double design_capacity;
  double percentage;
  int power_supply_status;
  int power_supply_health;
  int power_supply_technology;
  bool present;
  List<double> cell_voltage;
  List<double> cell_temperature;
  String location;
  String serial_number;

  static BatteryState $prototype = BatteryState();

  // Constructor
  BatteryState(
      {std_msgs.Header? header,
      double? voltage,
      double? temperature,
      double? current,
      double? charge,
      double? capacity,
      double? design_capacity,
      double? percentage,
      int? power_supply_status,
      int? power_supply_health,
      int? power_supply_technology,
      bool? present,
      List<double>? cell_voltage,
      List<double>? cell_temperature,
      String? location,
      String? serial_number})
      : header = header ?? std_msgs.Header(),
        voltage = voltage ?? 0.0,
        temperature = temperature ?? 0.0,
        current = current ?? 0.0,
        charge = charge ?? 0.0,
        capacity = capacity ?? 0.0,
        design_capacity = design_capacity ?? 0.0,
        percentage = percentage ?? 0.0,
        power_supply_status = power_supply_status ?? 0,
        power_supply_health = power_supply_health ?? 0,
        power_supply_technology = power_supply_technology ?? 0,
        present = present ?? false,
        cell_voltage = cell_voltage ?? const [],
        cell_temperature = cell_temperature ?? const [],
        location = location ?? "",
        serial_number = serial_number ?? "";

  @override
  String get fullType => 'sensor_msgs/msg/BatteryState';

  @override
  String get messageDefinition => '''std_msgs/Header header
float32 voltage
float32 temperature
float32 current
float32 charge
float32 capacity
float32 design_capacity
float32 percentage
uint8 power_supply_status
uint8 power_supply_health
uint8 power_supply_technology
bool present
float32[] cell_voltage
float32[] cell_temperature
string location
string serial_number''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            1 +
            1 +
            1 +
            1 +
            4 +
            (cell_voltage.length * 4) +
            4 +
            (cell_temperature.length * 4) +
            4 +
            location.length +
            4 +
            serial_number.length)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'voltage': voltage,
        'temperature': temperature,
        'current': current,
        'charge': charge,
        'capacity': capacity,
        'design_capacity': design_capacity,
        'percentage': percentage,
        'power_supply_status': power_supply_status,
        'power_supply_health': power_supply_health,
        'power_supply_technology': power_supply_technology,
        'present': present,
        'cell_voltage': cell_voltage,
        'cell_temperature': cell_temperature,
        'location': location,
        'serial_number': serial_number
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  BatteryState fromJson(Map<String, dynamic> jsonMap) {
    double asDouble(dynamic v) {
      if (v is double) return v;
      if (v is int) return v.toDouble();
      if (v is num) return v.toDouble();
      return double.tryParse(v?.toString() ?? '') ?? 0.0;
    }

    int asInt(dynamic v) {
      if (v is int) return v;
      if (v is double) return v.toInt();
      if (v is num) return v.toInt();
      return int.tryParse(v?.toString() ?? '') ?? 0;
    }

    List<double> asDoubleList(dynamic v) {
      if (v is! List) return const [];
      return v.map((e) => asDouble(e)).toList();
    }

    final headerRaw = jsonMap['header'];
    return BatteryState(
        header: headerRaw is Map
            ? std_msgs.Header()
                .fromJson(Map<String, dynamic>.from(headerRaw))
            : std_msgs.Header(),
        voltage: asDouble(jsonMap['voltage']),
        temperature: asDouble(jsonMap['temperature']),
        current: asDouble(jsonMap['current']),
        charge: asDouble(jsonMap['charge']),
        capacity: asDouble(jsonMap['capacity']),
        design_capacity: asDouble(jsonMap['design_capacity']),
        percentage: asDouble(jsonMap['percentage']),
        power_supply_status: asInt(jsonMap['power_supply_status']),
        power_supply_health: asInt(jsonMap['power_supply_health']),
        power_supply_technology: asInt(jsonMap['power_supply_technology']),
        present: jsonMap['present'] == true,
        cell_voltage: asDoubleList(jsonMap['cell_voltage']),
        cell_temperature: asDoubleList(jsonMap['cell_temperature']),
        location: jsonMap['location']?.toString() ?? '',
        serial_number: jsonMap['serial_number']?.toString() ?? '');
  }
}
