// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class CompressedImage extends RosMessage<CompressedImage> {
  std_msgs.Header header;
  String format;
  List<int> data;

  static CompressedImage $prototype = CompressedImage();

  // Constructor
  CompressedImage({std_msgs.Header? header, String? format, List<int>? data})
      : header = header ?? std_msgs.Header(),
        format = format ?? '',
        data = data ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/CompressedImage';

  @override
  String get messageDefinition => '''std_msgs/Header header
string format
uint8[] data''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + 4 + format.length + 4 + (data.length * 1))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'format': format, 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  CompressedImage fromJson(Map<String, dynamic> jsonMap) {
    var data = jsonMap['data'];
    List<int> byteData;

    // Handle case where data is a String (base64 encoded)
    if (data is String) {
      try {
        byteData = base64Decode(data);
      } catch (e) {
        print('Error decoding base64 data: $e');
        byteData = [];
      }
    }
    // Handle case where data is already a List
    else if (data is List) {
      byteData = (data).cast<int>();
    }
    // Handle any other unexpected type
    else {
      print('Unexpected data type: ${data.runtimeType}');
      byteData = [];
    }

    return CompressedImage(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      format: jsonMap['format'] as String,
      data: byteData,
    );
  }
}
