// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: unnecessary_this, non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:std_msgs/msg.dart' as std_msgs;

class Imu extends RosMessage<Imu> {
  std_msgs.Header header;
  geometry_msgs.Quaternion orientation;
  List<double> orientation_covariance;
  geometry_msgs.Vector3 angular_velocity;
  List<double> angular_velocity_covariance;
  geometry_msgs.Vector3 linear_acceleration;
  List<double> linear_acceleration_covariance;

  static Imu $prototype = Imu();

  // Constructor
  Imu(
      {std_msgs.Header? header,
      geometry_msgs.Quaternion? orientation,
      List<double>? orientation_covariance,
      geometry_msgs.Vector3? angular_velocity,
      List<double>? angular_velocity_covariance,
      geometry_msgs.Vector3? linear_acceleration,
      List<double>? linear_acceleration_covariance})
      : this.header = header ?? std_msgs.Header(),
        orientation = orientation ?? geometry_msgs.Quaternion(),
        orientation_covariance = orientation_covariance ?? const [],
        angular_velocity = angular_velocity ?? geometry_msgs.Vector3(),
        angular_velocity_covariance = angular_velocity_covariance ?? const [],
        linear_acceleration = linear_acceleration ?? geometry_msgs.Vector3(),
        linear_acceleration_covariance =
            linear_acceleration_covariance ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/Imu';

  @override
  String get messageDefinition => '''std_msgs/Header header
geometry_msgs/Quaternion orientation
float64[9] orientation_covariance
geometry_msgs/Vector3 angular_velocity
float64[9] angular_velocity_covariance
geometry_msgs/Vector3 linear_acceleration
float64[9] linear_acceleration_covariance''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            orientation.getMessageSize() +
            4 +
            (orientation_covariance.length * 8) +
            angular_velocity.getMessageSize() +
            4 +
            (angular_velocity_covariance.length * 8) +
            linear_acceleration.getMessageSize() +
            4 +
            (linear_acceleration_covariance.length * 8))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() {
    // Validate quaternion values
    _validateQuaternion(orientation);

    // Validate vector values
    _validateVector3(angular_velocity);
    _validateVector3(linear_acceleration);

    // Validate covariance arrays
    _validateCovarianceArray(orientation_covariance);
    _validateCovarianceArray(angular_velocity_covariance);
    _validateCovarianceArray(linear_acceleration_covariance);

    return {
      'header': header.toJson(),
      'orientation': orientation.toJson(),
      'orientation_covariance': orientation_covariance,
      'angular_velocity': angular_velocity.toJson(),
      'angular_velocity_covariance': angular_velocity_covariance,
      'linear_acceleration': linear_acceleration.toJson(),
      'linear_acceleration_covariance': linear_acceleration_covariance
    };
  }

  @override
  String toJsonString() {
    try {
      return json.encode(toJson());
    } catch (e) {
      print('Error encoding IMU message: $e');
      // Return a safe fallback JSON if encoding fails
      return '{"header":${header.toJsonString()},"orientation":{"x":0,"y":0,"z":0,"w":1},"orientation_covariance":[0,0,0,0,0,0,0,0,0],"angular_velocity":{"x":0,"y":0,"z":0},"angular_velocity_covariance":[0,0,0,0,0,0,0,0,0],"linear_acceleration":{"x":0,"y":0,"z":0},"linear_acceleration_covariance":[0,0,0,0,0,0,0,0,0]}';
    }
  }

  // Helper method to validate Vector3 and replace NaN values with 0.0
  void _validateVector3(geometry_msgs.Vector3 vector) {
    if (vector.x.isNaN) vector.x = 0.0;
    if (vector.y.isNaN) vector.y = 0.0;
    if (vector.z.isNaN) vector.z = 0.0;
  }

  // Helper method to validate Quaternion and replace NaN values with defaults
  void _validateQuaternion(geometry_msgs.Quaternion quat) {
    if (quat.x.isNaN) quat.x = 0.0;
    if (quat.y.isNaN) quat.y = 0.0;
    if (quat.z.isNaN) quat.z = 0.0;
    if (quat.w.isNaN) quat.w = 1.0; // Default to identity quaternion
  }

  // Helper method to validate covariance arrays
  void _validateCovarianceArray(List<double> array) {
    // Ensure array has 9 elements
    if (array.isEmpty) {
      for (int i = 0; i < 9; i++) {
        array.add(0.0);
      }
    }

    // Replace any NaN values with 0.0
    for (int i = 0; i < array.length; i++) {
      if (array[i].isNaN) {
        array[i] = 0.0;
      }
    }
  }

  @override
  Imu fromJson(Map<String, dynamic> jsonMap) {
    return Imu(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        orientation: geometry_msgs.Quaternion()
            .fromJson(jsonMap['orientation'] as Map<String, dynamic>),
        orientation_covariance:
            (jsonMap['orientation_covariance'] as List).cast<double>(),
        angular_velocity: geometry_msgs.Vector3()
            .fromJson(jsonMap['angular_velocity'] as Map<String, dynamic>),
        angular_velocity_covariance:
            (jsonMap['angular_velocity_covariance'] as List).cast<double>(),
        linear_acceleration: geometry_msgs.Vector3()
            .fromJson(jsonMap['linear_acceleration'] as Map<String, dynamic>),
        linear_acceleration_covariance:
            (jsonMap['linear_acceleration_covariance'] as List).cast<double>());
  }
}
