// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class Joy extends RosMessage<Joy> {
  std_msgs.Header header;
  List<double> axes;
  List<int> buttons;

  static Joy $prototype = Joy();

  // Constructor
  Joy({std_msgs.Header? header, List<double>? axes, List<int>? buttons})
      : header = header ?? std_msgs.Header(),
        axes = axes ?? const [],
        buttons = buttons ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/Joy';

  @override
  String get messageDefinition => '''std_msgs/Header header
float32[] axes
int32[] buttons''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            (axes.length * 4) +
            4 +
            (buttons.length * 4))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'axes': axes, 'buttons': buttons};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Joy fromJson(Map<String, dynamic> jsonMap) {
    return Joy(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        axes: (jsonMap['axes'] as List).cast<double>(),
        buttons: (jsonMap['buttons'] as List).cast<int>());
  }
}
