// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class JoyFeedback extends RosMessage<JoyFeedback> {
  int type;
  int id;
  double intensity;

  static JoyFeedback $prototype = JoyFeedback();

  // Constructor
  JoyFeedback({int? type, int? id, double? intensity})
      : type = type ?? 0,
        id = id ?? 0,
        intensity = intensity ?? 0.0;

  @override
  String get fullType => 'sensor_msgs/msg/JoyFeedback';

  @override
  String get messageDefinition => '''uint8 type
uint8 id
float32 intensity''';

  @override
  int getMessageSize() {
    return (1 + 1 + 4).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'type': type, 'id': id, 'intensity': intensity};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  JoyFeedback fromJson(Map<String, dynamic> jsonMap) {
    return JoyFeedback(
        type: jsonMap['type'] as int,
        id: jsonMap['id'] as int,
        intensity: jsonMap['intensity'] as double);
  }
}
