// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:std_msgs/msg.dart' as std_msgs;

class MultiDOFJointState extends RosMessage<MultiDOFJointState> {
  std_msgs.Header header;
  List<String> joint_names;
  List<geometry_msgs.Transform> transforms;
  List<geometry_msgs.Twist> twist;
  List<geometry_msgs.Wrench> wrench;

  static MultiDOFJointState $prototype = MultiDOFJointState();

  // Constructor
  MultiDOFJointState(
      {std_msgs.Header? header,
      List<String>? joint_names,
      List<geometry_msgs.Transform>? transforms,
      List<geometry_msgs.Twist>? twist,
      List<geometry_msgs.Wrench>? wrench})
      : header = header ?? std_msgs.Header(),
        joint_names = joint_names ?? const [],
        transforms = transforms ?? const [],
        twist = twist ?? const [],
        wrench = wrench ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/MultiDOFJointState';

  @override
  String get messageDefinition => '''std_msgs/Header header
string[] joint_names
geometry_msgs/Transform[] transforms
geometry_msgs/Twist[] twist
geometry_msgs/Wrench[] wrench''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            (joint_names.length * 0) +
            4 +
            transforms.fold(0, (sum, item) => sum + item.getMessageSize()) +
            4 +
            twist.fold(0, (sum, item) => sum + item.getMessageSize()) +
            4 +
            wrench.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'joint_names': joint_names,
        'transforms': transforms.map((item) => item.toJson()).toList(),
        'twist': twist.map((item) => item.toJson()).toList(),
        'wrench': wrench.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MultiDOFJointState fromJson(Map<String, dynamic> jsonMap) {
    return MultiDOFJointState(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        joint_names: (jsonMap['joint_names'] as List).cast<String>(),
        transforms: (jsonMap['transforms'] as List)
            .map((item) => geometry_msgs.Transform()
                .fromJson(item as Map<String, dynamic>))
            .toList(),
        twist: (jsonMap['twist'] as List)
            .map((item) =>
                geometry_msgs.Twist().fromJson(item as Map<String, dynamic>))
            .toList(),
        wrench: (jsonMap['wrench'] as List)
            .map((item) =>
                geometry_msgs.Wrench().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
