// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class RegionOfInterest extends RosMessage<RegionOfInterest> {
  int x_offset;
  int y_offset;
  int height;
  int width;
  bool do_rectify;

  static RegionOfInterest $prototype = RegionOfInterest();

  // Constructor
  RegionOfInterest(
      {int? x_offset, int? y_offset, int? height, int? width, bool? do_rectify})
      : x_offset = x_offset ?? 0,
        y_offset = y_offset ?? 0,
        height = height ?? 0,
        width = width ?? 0,
        do_rectify = do_rectify ?? false;

  @override
  String get fullType => 'sensor_msgs/msg/RegionOfInterest';

  @override
  String get messageDefinition => '''uint32 x_offset
uint32 y_offset
uint32 height
uint32 width
bool do_rectify''';

  @override
  int getMessageSize() {
    return (4 + 4 + 4 + 4 + 1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'x_offset': x_offset,
        'y_offset': y_offset,
        'height': height,
        'width': width,
        'do_rectify': do_rectify
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  RegionOfInterest fromJson(Map<String, dynamic> jsonMap) {
    return RegionOfInterest(
        x_offset: jsonMap['x_offset'] as int,
        y_offset: jsonMap['y_offset'] as int,
        height: jsonMap['height'] as int,
        width: jsonMap['width'] as int,
        do_rectify: jsonMap['do_rectify'] as bool);
  }
}
