// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Bool extends RosMessage<Bool> {
  bool data;

  static Bool $prototype = Bool();

  // Constructor
  Bool({this.data = false});

  @override
  String get fullType => 'std_msgs/msg/Bool';

  @override
  String get messageDefinition => '''bool data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Bool fromJson(Map<String, dynamic> jsonMap) {
    return Bool(data: jsonMap['data'] as bool);
  }
}
