// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Byte extends RosMessage<Byte> {
  int data;

  static Byte $prototype = Byte();

  // Constructor
  Byte({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/Byte';

  @override
  String get messageDefinition => '''byte data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Byte fromJson(Map<String, dynamic> jsonMap) {
    return Byte(data: jsonMap['data'] as int);
  }
}
