// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Empty extends RosMessage<Empty> {
  static Empty $prototype = Empty();

  // Constructor
  Empty();

  @override
  String get fullType => 'std_msgs/msg/Empty';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Empty fromJson(Map<String, dynamic> jsonMap) {
    return Empty();
  }
}
