// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Float64 extends RosMessage<Float64> {
  double data;

  static Float64 $prototype = Float64();

  // Constructor
  Float64({this.data = 0.0});

  @override
  String get fullType => 'std_msgs/msg/Float64';

  @override
  String get messageDefinition => '''float64 data''';

  @override
  int getMessageSize() {
    return (8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Float64 fromJson(Map<String, dynamic> jsonMap) {
    return Float64(data: jsonMap['data'] as double);
  }
}
