// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'MultiArrayLayout.dart';

class Float64MultiArray extends RosMessage<Float64MultiArray> {
  MultiArrayLayout layout;
  List<double> data;

  static Float64MultiArray $prototype = Float64MultiArray();

  // Constructor
  Float64MultiArray({
    MultiArrayLayout? layout,
    List<double>? data,
  })  : layout = layout ?? MultiArrayLayout(),
        data = data ?? const [];

  @override
  String get fullType => 'std_msgs/msg/Float64MultiArray';

  @override
  String get messageDefinition => '''MultiArrayLayout layout
float64[] data''';

  @override
  int getMessageSize() {
    return (layout.getMessageSize() + 4 + (data.length * 8)).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'layout': layout.toJson(), 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Float64MultiArray fromJson(Map<String, dynamic> jsonMap) {
    return Float64MultiArray(
        layout: MultiArrayLayout()
            .fromJson(jsonMap['layout'] as Map<String, dynamic>),
        data: (jsonMap['data'] as List).cast<double>());
  }
}
