// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names, prefer_initializing_formals

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'package:builtin_interfaces/msg.dart';

class Header extends RosMessage<Header> {
  Time stamp;
  String frame_id;

  static Header $prototype = Header();
  // Constructor
  Header({
    Time? stamp,
    String frame_id = '',
  })  : stamp = stamp ?? Time(),
        frame_id = frame_id; // Initialize frame_id to ensure it's non-nullable

  @override
  String get fullType => 'std_msgs/msg/Header';

  @override
  String get messageDefinition => '''builtin_interfaces/Time stamp
string frame_id''';

  @override
  int getMessageSize() {
    return stamp.getMessageSize() + 4 + frame_id.length;
  }

  @override
  Map<String, dynamic> toJson() => {
        'stamp': stamp.toJson(),
        'frame_id': frame_id,
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Header fromJson(Map<String, dynamic> jsonMap) {
    return Header(
      stamp: Time().fromJson(jsonMap['stamp'] as Map<String, dynamic>),
      frame_id: jsonMap['frame_id'] as String,
    );
  }
}
