// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Int64 extends RosMessage<Int64> {
  int data;

  static Int64 $prototype = Int64();

  // Constructor
  Int64({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/Int64';

  @override
  String get messageDefinition => '''int64 data''';

  @override
  int getMessageSize() {
    return (8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Int64 fromJson(Map<String, dynamic> jsonMap) {
    return Int64(data: jsonMap['data'] as int);
  }
}
