// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Int8 extends RosMessage<Int8> {
  int data;

  static Int8 $prototype = Int8();

  // Constructor
  Int8({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/Int8';

  @override
  String get messageDefinition => '''int8 data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Int8 fromJson(Map<String, dynamic> jsonMap) {
    return Int8(data: jsonMap['data'] as int);
  }
}
