// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'MultiArrayDimension.dart';

class MultiArrayLayout extends RosMessage<MultiArrayLayout> {
  List<MultiArrayDimension> dim;
  int data_offset;

  static MultiArrayLayout $prototype = MultiArrayLayout();

  // Constructor
  MultiArrayLayout({this.dim = const [], this.data_offset = 0});

  @override
  String get fullType => 'std_msgs/msg/MultiArrayLayout';

  @override
  String get messageDefinition => '''MultiArrayDimension[] dim
uint32 data_offset''';

  @override
  int getMessageSize() {
    return (4 + dim.fold(0, (sum, item) => sum + item.getMessageSize()) + 4)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'dim': dim.map((item) => item.toJson()).toList(),
        'data_offset': data_offset
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MultiArrayLayout fromJson(Map<String, dynamic> jsonMap) {
    return MultiArrayLayout(
        dim: (jsonMap['dim'] as List)
            .map((item) =>
                MultiArrayDimension().fromJson(item as Map<String, dynamic>))
            .toList(),
        data_offset: jsonMap['data_offset'] as int);
  }
}
