// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class UInt32 extends RosMessage<UInt32> {
  int data;

  static UInt32 $prototype = UInt32();

  // Constructor
  UInt32({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/UInt32';

  @override
  String get messageDefinition => '''uint32 data''';

  @override
  int getMessageSize() {
    return (4).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UInt32 fromJson(Map<String, dynamic> jsonMap) {
    return UInt32(data: jsonMap['data'] as int);
  }
}
