// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class UInt8 extends RosMessage<UInt8> {
  int data;

  static UInt8 $prototype = UInt8();

  // Constructor
  UInt8({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/UInt8';

  @override
  String get messageDefinition => '''uint8 data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UInt8 fromJson(Map<String, dynamic> jsonMap) {
    return UInt8(data: jsonMap['data'] as int);
  }
}
