// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class UInt16 extends RosMessage<UInt16> {
  int data;

  static UInt16 $prototype = UInt16();

  // Constructor
  UInt16({this.data = 0});

  @override
  String get fullType => 'std_msgs/msg/UInt16';

  @override
  String get messageDefinition => '''uint16 data''';

  @override
  int getMessageSize() {
    return (2).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UInt16 fromJson(Map<String, dynamic> jsonMap) {
    return UInt16(data: jsonMap['data'] as int);
  }
}
