// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'MultiArrayLayout.dart';

class UInt16MultiArray extends RosMessage<UInt16MultiArray> {
  MultiArrayLayout layout;
  List<int> data;

  static UInt16MultiArray $prototype = UInt16MultiArray();

  // Constructor
  UInt16MultiArray({
    MultiArrayLayout? layout,
    List<int>? data,
  })  : layout = layout ?? MultiArrayLayout(),
        data = data ?? [];

  @override
  String get fullType => 'std_msgs/msg/UInt16MultiArray';

  @override
  String get messageDefinition => '''MultiArrayLayout layout
uint16[] data''';

  @override
  int getMessageSize() {
    return (layout.getMessageSize() + 4 + (data.length * 2)).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'layout': layout.toJson(), 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UInt16MultiArray fromJson(Map<String, dynamic> jsonMap) {
    return UInt16MultiArray(
        layout: MultiArrayLayout()
            .fromJson(jsonMap['layout'] as Map<String, dynamic>),
        data: (jsonMap['data'] as List).cast<int>());
  }
}
