// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class BatteryState extends RosMessage<BatteryState> {
  std_msgs.Header header;
  double voltage;
  double temperature;
  double current;
  double charge;
  double capacity;
  double design_capacity;
  double percentage;
  int power_supply_status;
  int power_supply_health;
  int power_supply_technology;
  bool present;
  List<double> cell_voltage;
  List<double> cell_temperature;
  String location;
  String serial_number;

  static BatteryState $prototype = BatteryState();

  // Constructor
  BatteryState(
      {std_msgs.Header? header,
      double? voltage,
      double? temperature,
      double? current,
      double? charge,
      double? capacity,
      double? design_capacity,
      double? percentage,
      int? power_supply_status,
      int? power_supply_health,
      int? power_supply_technology,
      bool? present,
      List<double>? cell_voltage,
      List<double>? cell_temperature,
      String? location,
      String? serial_number})
      : header = header ?? std_msgs.Header(),
        voltage = voltage ?? 0.0,
        temperature = temperature ?? 0.0,
        current = current ?? 0.0,
        charge = charge ?? 0.0,
        capacity = capacity ?? 0.0,
        design_capacity = design_capacity ?? 0.0,
        percentage = percentage ?? 0.0,
        power_supply_status = power_supply_status ?? 0,
        power_supply_health = power_supply_health ?? 0,
        power_supply_technology = power_supply_technology ?? 0,
        present = present ?? false,
        cell_voltage = cell_voltage ?? const [],
        cell_temperature = cell_temperature ?? const [],
        location = location ?? "",
        serial_number = serial_number ?? "";

  @override
  String get fullType => 'sensor_msgs/msg/BatteryState';

  @override
  String get messageDefinition => '''std_msgs/Header header
float32 voltage
float32 temperature
float32 current
float32 charge
float32 capacity
float32 design_capacity
float32 percentage
uint8 power_supply_status
uint8 power_supply_health
uint8 power_supply_technology
bool present
float32[] cell_voltage
float32[] cell_temperature
string location
string serial_number''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            1 +
            1 +
            1 +
            1 +
            4 +
            (cell_voltage.length * 4) +
            4 +
            (cell_temperature.length * 4) +
            4 +
            location.length +
            4 +
            serial_number.length)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'voltage': voltage,
        'temperature': temperature,
        'current': current,
        'charge': charge,
        'capacity': capacity,
        'design_capacity': design_capacity,
        'percentage': percentage,
        'power_supply_status': power_supply_status,
        'power_supply_health': power_supply_health,
        'power_supply_technology': power_supply_technology,
        'present': present,
        'cell_voltage': cell_voltage,
        'cell_temperature': cell_temperature,
        'location': location,
        'serial_number': serial_number
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  BatteryState fromJson(Map<String, dynamic> jsonMap) {
    return BatteryState(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        voltage: jsonMap['voltage'] as double,
        temperature: jsonMap['temperature'] as double,
        current: jsonMap['current'] as double,
        charge: jsonMap['charge'] as double,
        capacity: jsonMap['capacity'] as double,
        design_capacity: jsonMap['design_capacity'] as double,
        percentage: jsonMap['percentage'] as double,
        power_supply_status: jsonMap['power_supply_status'] as int,
        power_supply_health: jsonMap['power_supply_health'] as int,
        power_supply_technology: jsonMap['power_supply_technology'] as int,
        present: jsonMap['present'] as bool,
        cell_voltage: (jsonMap['cell_voltage'] as List).cast<double>(),
        cell_temperature: (jsonMap['cell_temperature'] as List).cast<double>(),
        location: jsonMap['location'] as String,
        serial_number: jsonMap['serial_number'] as String);
  }
}
