// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class JointState extends RosMessage<JointState> {
  std_msgs.Header header;
  List<String> name;
  List<double> position;
  List<double> velocity;
  List<double> effort;

  static JointState $prototype = JointState();

  // Constructor
  JointState(
      {std_msgs.Header? header,
      List<String>? name,
      List<double>? position,
      List<double>? velocity,
      List<double>? effort})
      : header = header ?? std_msgs.Header(),
        name = name ?? const [],
        position = position ?? const [],
        velocity = velocity ?? const [],
        effort = effort ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/JointState';

  @override
  String get messageDefinition => '''std_msgs/Header header
string[] name
float64[] position
float64[] velocity
float64[] effort''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            (name.length * 0) +
            4 +
            (position.length * 8) +
            4 +
            (velocity.length * 8) +
            4 +
            (effort.length * 8))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'name': name,
        'position': position,
        'velocity': velocity,
        'effort': effort
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  JointState fromJson(Map<String, dynamic> jsonMap) {
    return JointState(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        name: (jsonMap['name'] as List).cast<String>(),
        position: (jsonMap['position'] as List).cast<double>(),
        velocity: (jsonMap['velocity'] as List).cast<double>(),
        effort: (jsonMap['effort'] as List).cast<double>());
  }
}
