// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'JoyFeedback.dart';

class JoyFeedbackArray extends RosMessage<JoyFeedbackArray> {
  List<JoyFeedback> array;

  static JoyFeedbackArray $prototype = JoyFeedbackArray();

  // Constructor
  JoyFeedbackArray({List<JoyFeedback>? array}) : array = array ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/JoyFeedbackArray';

  @override
  String get messageDefinition => '''JoyFeedback[] array''';

  @override
  int getMessageSize() {
    return (4 + array.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'array': array.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  JoyFeedbackArray fromJson(Map<String, dynamic> jsonMap) {
    return JoyFeedbackArray(
        array: (jsonMap['array'] as List)
            .map((item) => JoyFeedback().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
