// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class LaserScan extends RosMessage<LaserScan> {
  std_msgs.Header header;
  double angle_min;
  double angle_max;
  double angle_increment;
  double time_increment;
  double scan_time;
  double range_min;
  double range_max;
  List<double> ranges;
  List<double> intensities;

  static LaserScan $prototype = LaserScan();

  // Constructor
  LaserScan(
      {std_msgs.Header? header,
      double? angle_min,
      double? angle_max,
      double? angle_increment,
      double? time_increment,
      double? scan_time,
      double? range_min,
      double? range_max,
      List<double>? ranges,
      List<double>? intensities})
      : header = header ?? std_msgs.Header(),
        angle_min = angle_min ?? 0.0,
        angle_max = angle_max ?? 0.0,
        angle_increment = angle_increment ?? 0.0,
        time_increment = time_increment ?? 0.0,
        scan_time = scan_time ?? 0.0,
        range_min = range_min ?? 0.0,
        range_max = range_max ?? 0.0,
        ranges = ranges ?? const [],
        intensities = intensities ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/LaserScan';

  @override
  String get messageDefinition => '''std_msgs/Header header
float32 angle_min
float32 angle_max
float32 angle_increment
float32 time_increment
float32 scan_time
float32 range_min
float32 range_max
float32[] ranges
float32[] intensities''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            4 +
            (ranges.length * 4) +
            4 +
            (intensities.length * 4))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'angle_min': angle_min,
        'angle_max': angle_max,
        'angle_increment': angle_increment,
        'time_increment': time_increment,
        'scan_time': scan_time,
        'range_min': range_min,
        'range_max': range_max,
        'ranges': ranges,
        'intensities': intensities
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  LaserScan fromJson(Map<String, dynamic> jsonMap) {
    return LaserScan(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        angle_min: jsonMap['angle_min'] as double,
        angle_max: jsonMap['angle_max'] as double,
        angle_increment: jsonMap['angle_increment'] as double,
        time_increment: jsonMap['time_increment'] as double,
        scan_time: jsonMap['scan_time'] as double,
        range_min: jsonMap['range_min'] as double,
        range_max: jsonMap['range_max'] as double,
        ranges: (jsonMap['ranges'] as List).cast<double>(),
        intensities: (jsonMap['intensities'] as List).cast<double>());
  }
}
