// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:std_msgs/msg.dart' as std_msgs;

class MagneticField extends RosMessage<MagneticField> {
  std_msgs.Header header;
  geometry_msgs.Vector3 magnetic_field;
  List<double> magnetic_field_covariance;

  static MagneticField $prototype = MagneticField();

  // Constructor
  MagneticField(
      {std_msgs.Header? header,
      geometry_msgs.Vector3? magnetic_field,
      List<double>? magnetic_field_covariance})
      : header = header ?? std_msgs.Header(),
        magnetic_field = magnetic_field ?? geometry_msgs.Vector3(),
        magnetic_field_covariance = magnetic_field_covariance ?? const [];

  @override
  String get fullType => 'sensor_msgs/msg/MagneticField';

  @override
  String get messageDefinition => '''std_msgs/Header header
geometry_msgs/Vector3 magnetic_field
float64[9] magnetic_field_covariance''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            magnetic_field.getMessageSize() +
            4 +
            (magnetic_field_covariance.length * 8))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'magnetic_field': magnetic_field.toJson(),
        'magnetic_field_covariance': magnetic_field_covariance
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MagneticField fromJson(Map<String, dynamic> jsonMap) {
    return MagneticField(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        magnetic_field: geometry_msgs.Vector3()
            .fromJson(jsonMap['magnetic_field'] as Map<String, dynamic>),
        magnetic_field_covariance:
            (jsonMap['magnetic_field_covariance'] as List).cast<double>());
  }
}
