// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'NavSatStatus.dart';

class NavSatFix extends RosMessage<NavSatFix> {
  std_msgs.Header header;
  NavSatStatus status;
  double latitude;
  double longitude;
  double altitude;
  List<double> position_covariance;
  int position_covariance_type;

  static NavSatFix $prototype = NavSatFix();

  // Constructor
  NavSatFix(
      {std_msgs.Header? header,
      NavSatStatus? status,
      double? latitude,
      double? longitude,
      double? altitude,
      List<double>? position_covariance,
      int? position_covariance_type})
      : header = header ?? std_msgs.Header(),
        status = status ?? NavSatStatus(),
        latitude = latitude ?? 0.0,
        longitude = longitude ?? 0.0,
        altitude = altitude ?? 0.0,
        position_covariance = position_covariance ?? const [],
        position_covariance_type = position_covariance_type ?? 0;

  @override
  String get fullType => 'sensor_msgs/msg/NavSatFix';

  @override
  String get messageDefinition => '''std_msgs/Header header
NavSatStatus status
float64 latitude
float64 longitude
float64 altitude
float64[9] position_covariance
uint8 position_covariance_type''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            status.getMessageSize() +
            8 +
            8 +
            8 +
            4 +
            (position_covariance.length * 8) +
            1)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'latitude': latitude,
        'longitude': longitude,
        'altitude': altitude,
        'position_covariance': position_covariance,
        'position_covariance_type': position_covariance_type
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavSatFix fromJson(Map<String, dynamic> jsonMap) {
    return NavSatFix(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        status:
            NavSatStatus().fromJson(jsonMap['status'] as Map<String, dynamic>),
        latitude: jsonMap['latitude'] as double,
        longitude: jsonMap['longitude'] as double,
        altitude: jsonMap['altitude'] as double,
        position_covariance:
            (jsonMap['position_covariance'] as List).cast<double>(),
        position_covariance_type: jsonMap['position_covariance_type'] as int);
  }
}
