// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class NavSatStatus extends RosMessage<NavSatStatus> {
  int status;
  int service;

  static NavSatStatus $prototype = NavSatStatus();

  // Constructor
  NavSatStatus({int? status, int? service})
      : status = status ?? 0,
        service = service ?? 0;

  @override
  String get fullType => 'sensor_msgs/msg/NavSatStatus';

  @override
  String get messageDefinition => '''int8 status
uint16 service''';

  @override
  int getMessageSize() {
    return (1 + 2).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'status': status, 'service': service};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavSatStatus fromJson(Map<String, dynamic> jsonMap) {
    return NavSatStatus(
        status: jsonMap['status'] as int, service: jsonMap['service'] as int);
  }
}
