// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class PointField extends RosMessage<PointField> {
  String name;
  int offset;
  int datatype;
  int count;

  static PointField $prototype = PointField();

  // Constructor
  PointField({String? name, int? offset, int? datatype, int? count})
      : name = name ?? '',
        offset = offset ?? 0,
        datatype = datatype ?? 0,
        count = count ?? 0;

  @override
  String get fullType => 'sensor_msgs/msg/PointField';

  @override
  String get messageDefinition => '''string name
uint32 offset
uint8 datatype
uint32 count''';

  @override
  int getMessageSize() {
    return (4 + name.length + 4 + 1 + 4).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'name': name, 'offset': offset, 'datatype': datatype, 'count': count};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PointField fromJson(Map<String, dynamic> jsonMap) {
    return PointField(
        name: jsonMap['name'] as String,
        offset: jsonMap['offset'] as int,
        datatype: jsonMap['datatype'] as int,
        count: jsonMap['count'] as int);
  }
}
