// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'PointField.dart';

class PointCloud2 extends RosMessage<PointCloud2> {
  std_msgs.Header header;
  int height;
  int width;
  List<PointField> fields;
  bool is_bigendian;
  int point_step;
  int row_step;
  List<int> data;
  bool is_dense;

  static PointCloud2 $prototype = PointCloud2();

  // Constructor
  PointCloud2(
      {std_msgs.Header? header,
      int? height,
      int? width,
      List<PointField>? fields,
      bool? is_bigendian,
      int? point_step,
      int? row_step,
      List<int>? data,
      bool? is_dense})
      : header = header ?? std_msgs.Header(),
        height = height ?? 0,
        width = width ?? 0,
        fields = fields ?? const [],
        is_bigendian = is_bigendian ?? false,
        point_step = point_step ?? 0,
        row_step = row_step ?? 0,
        data = data ?? const [],
        is_dense = is_dense ?? false;

  @override
  String get fullType => 'sensor_msgs/msg/PointCloud2';

  @override
  String get messageDefinition => '''std_msgs/Header header
uint32 height
uint32 width
PointField[] fields
bool is_bigendian
uint32 point_step
uint32 row_step
uint8[] data
bool is_dense''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            4 +
            4 +
            fields.fold(0, (sum, item) => sum + item.getMessageSize()) +
            1 +
            4 +
            4 +
            4 +
            (data.length * 1) +
            1)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'height': height,
        'width': width,
        'fields': fields.map((item) => item.toJson()).toList(),
        'is_bigendian': is_bigendian,
        'point_step': point_step,
        'row_step': row_step,
        'data': data,
        'is_dense': is_dense
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PointCloud2 fromJson(Map<String, dynamic> jsonMap) {
    return PointCloud2(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        height: jsonMap['height'] as int,
        width: jsonMap['width'] as int,
        fields: (jsonMap['fields'] as List)
            .map((item) => PointField().fromJson(item as Map<String, dynamic>))
            .toList(),
        is_bigendian: jsonMap['is_bigendian'] as bool,
        point_step: jsonMap['point_step'] as int,
        row_step: jsonMap['row_step'] as int,
        data: (jsonMap['data'] as List).cast<int>(),
        is_dense: jsonMap['is_dense'] as bool);
  }
}
