// Generated by ros_to_dart_converter
// Do not edit manually

// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class RelativeHumidity extends RosMessage<RelativeHumidity> {
  std_msgs.Header header;
  double relative_humidity;
  double variance;

  static RelativeHumidity $prototype = RelativeHumidity();

  // Constructor
  RelativeHumidity(
      {std_msgs.Header? header, double? relative_humidity, double? variance})
      : header = header ?? std_msgs.Header(),
        relative_humidity = relative_humidity ?? 0.0,
        variance = variance ?? 0.0;

  @override
  String get fullType => 'sensor_msgs/msg/RelativeHumidity';

  @override
  String get messageDefinition => '''std_msgs/Header header
float64 relative_humidity
float64 variance''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'relative_humidity': relative_humidity,
        'variance': variance
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  RelativeHumidity fromJson(Map<String, dynamic> jsonMap) {
    return RelativeHumidity(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        relative_humidity: jsonMap['relative_humidity'] as double,
        variance: jsonMap['variance'] as double);
  }
}
