// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class Temperature extends RosMessage<Temperature> {
  std_msgs.Header header;
  double temperature;
  double variance;

  static Temperature $prototype = Temperature();

  // Constructor
  Temperature({std_msgs.Header? header, double? temperature, double? variance})
      : header = header ?? std_msgs.Header(),
        temperature = temperature ?? 0.0,
        variance = variance ?? 0.0;

  @override
  String get fullType => 'sensor_msgs/msg/Temperature';

  @override
  String get messageDefinition => '''std_msgs/Header header
float64 temperature
float64 variance''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'temperature': temperature,
        'variance': variance
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Temperature fromJson(Map<String, dynamic> jsonMap) {
    return Temperature(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        temperature: jsonMap['temperature'] as double,
        variance: jsonMap['variance'] as double);
  }
}
