// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'BehaviorTreeStatusChange.dart';

class BehaviorTreeLog extends RosMessage<BehaviorTreeLog> {
  builtin_interfaces.Time timestamp;
  List<BehaviorTreeStatusChange> event_log;

  static BehaviorTreeLog $prototype = BehaviorTreeLog();

  // Constructor
  BehaviorTreeLog(
      {builtin_interfaces.Time? timestamp,
      List<BehaviorTreeStatusChange>? event_log})
      : timestamp = timestamp ?? builtin_interfaces.Time(),
        event_log = event_log ?? const [];

  @override
  String get fullType => 'nav2_msgs/msg/BehaviorTreeLog';

  @override
  String get messageDefinition => '''builtin_interfaces/Time timestamp
BehaviorTreeStatusChange[] event_log''';

  @override
  int getMessageSize() {
    return (timestamp.getMessageSize() +
            4 +
            event_log.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'timestamp': timestamp.toJson(),
        'event_log': event_log.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  BehaviorTreeLog fromJson(Map<String, dynamic> jsonMap) {
    return BehaviorTreeLog(
        timestamp: builtin_interfaces.Time()
            .fromJson(jsonMap['timestamp'] as Map<String, dynamic>),
        event_log: (jsonMap['event_log'] as List)
            .map((item) => BehaviorTreeStatusChange()
                .fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
