// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class BehaviorTreeStatusChange extends RosMessage<BehaviorTreeStatusChange> {
  builtin_interfaces.Time timestamp;
  String node_name;
  String previous_status;
  String current_status;

  static BehaviorTreeStatusChange $prototype = BehaviorTreeStatusChange();

  // Constructor
  BehaviorTreeStatusChange(
      {builtin_interfaces.Time? timestamp,
      String? node_name,
      String? previous_status,
      String? current_status})
      : timestamp = timestamp ?? builtin_interfaces.Time(),
        node_name = node_name ?? '',
        previous_status = previous_status ?? '',
        current_status = current_status ?? '';

  @override
  String get fullType => 'nav2_msgs/msg/BehaviorTreeStatusChange';

  @override
  String get messageDefinition => '''builtin_interfaces/Time timestamp
string node_name
string previous_status
string current_status''';

  @override
  int getMessageSize() {
    return (timestamp.getMessageSize() +
            4 +
            node_name.length +
            4 +
            previous_status.length +
            4 +
            current_status.length)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'timestamp': timestamp.toJson(),
        'node_name': node_name,
        'previous_status': previous_status,
        'current_status': current_status
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  BehaviorTreeStatusChange fromJson(Map<String, dynamic> jsonMap) {
    return BehaviorTreeStatusChange(
        timestamp: builtin_interfaces.Time()
            .fromJson(jsonMap['timestamp'] as Map<String, dynamic>),
        node_name: jsonMap['node_name'] as String,
        previous_status: jsonMap['previous_status'] as String,
        current_status: jsonMap['current_status'] as String);
  }
}
