// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class MissedWaypoint extends RosMessage<MissedWaypoint> {
  int index;
  geometry_msgs.PoseStamped goal;
  int error_code;

  static MissedWaypoint $prototype = MissedWaypoint();

  // Constructor
  MissedWaypoint({int? index, geometry_msgs.PoseStamped? goal, int? error_code})
      : index = index ?? 0,
        goal = goal ?? geometry_msgs.PoseStamped(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/msg/MissedWaypoint';

  @override
  String get messageDefinition => '''uint32 index
geometry_msgs/PoseStamped goal
uint16 error_code''';

  @override
  int getMessageSize() {
    return (4 + goal.getMessageSize() + 2).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'index': index, 'goal': goal.toJson(), 'error_code': error_code};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MissedWaypoint fromJson(Map<String, dynamic> jsonMap) {
    return MissedWaypoint(
        index: jsonMap['index'] as int,
        goal: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['goal'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}
