// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart';
import 'GoalStatus.dart';

class GoalStatusArray extends RosMessage<GoalStatusArray> {
  Header header;
  List<GoalStatus> status_list;

  static GoalStatusArray $prototype = GoalStatusArray();
  // Constructor
  GoalStatusArray({Header? header, List<GoalStatus>? status_list})
      : header = header ?? Header(),
        status_list = status_list ?? [];

  @override
  String get fullType => 'actionlib_msgs/msg/GoalStatusArray';

  @override
  String get messageDefinition => '''std_msgs/Header header
GoalStatus[] status_list''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            status_list.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status_list': status_list.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GoalStatusArray fromJson(Map<String, dynamic> jsonMap) {
    return GoalStatusArray(
        header: Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
        status_list: (jsonMap['status_list'] as List)
            .map((item) => GoalStatus().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
