// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'GoalID.dart';

class GoalStatus extends RosMessage<GoalStatus> {
  GoalID goal_id;
  int status;
  String text;

  static GoalStatus $prototype = GoalStatus();
  // Constructor
  GoalStatus({GoalID? goal_id, int? status, String? text})
      : goal_id = goal_id ?? GoalID(),
        status = status ?? 0,
        text = text ?? '';

  @override
  String get fullType => 'actionlib_msgs/msg/GoalStatus';

  @override
  String get messageDefinition => '''GoalID goal_id
uint8 status
string text''';

  @override
  int getMessageSize() {
    return (goal_id.getMessageSize() + 1 + 4 + text.length).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'goal_id': goal_id.toJson(), 'status': status, 'text': text};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GoalStatus fromJson(Map<String, dynamic> jsonMap) {
    return GoalStatus(
        goal_id: GoalID().fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
        status: jsonMap['status'] as int,
        text: jsonMap['text'] as String);
  }
}
