// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class OccupancyGridUpdate extends RosMessage<OccupancyGridUpdate> {
  std_msgs.Header header;
  int x;
  int y;
  int width;
  int height;
  List<int> data;

  static OccupancyGridUpdate $prototype = OccupancyGridUpdate();

  // Constructor
  OccupancyGridUpdate(
      {std_msgs.Header? header,
      int? x,
      int? y,
      int? width,
      int? height,
      List<int>? data})
      : header = header ?? std_msgs.Header(),
        x = x ?? 0,
        y = y ?? 0,
        width = width ?? 0,
        height = height ?? 0,
        data = data ?? const [];

  @override
  String get fullType => 'map_msgs/msg/OccupancyGridUpdate';

  @override
  String get messageDefinition => '''std_msgs/Header header
int32 x
int32 y
uint32 width
uint32 height
int8[] data''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + 4 + 4 + 4 + 4 + 4 + (data.length * 1))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'x': x,
        'y': y,
        'width': width,
        'height': height,
        'data': data
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  OccupancyGridUpdate fromJson(Map<String, dynamic> jsonMap) {
    return OccupancyGridUpdate(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        x: jsonMap['x'] as int,
        y: jsonMap['y'] as int,
        width: jsonMap['width'] as int,
        height: jsonMap['height'] as int,
        data: (jsonMap['data'] as List).cast<int>());
  }
}
