// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class AssistedTeleopGoal extends RosMessage<AssistedTeleopGoal> {
  late builtin_interfaces.Duration time_allowance;

  static AssistedTeleopGoal $prototype = AssistedTeleopGoal();

  AssistedTeleopGoal({builtin_interfaces.Duration? time_allowance})
      : time_allowance = time_allowance ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_Goal';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return (time_allowance.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() => {'time_allowance': time_allowance.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopGoal fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopGoal(
        time_allowance: builtin_interfaces.Duration()
            .fromJson(jsonMap['time_allowance'] as Map<String, dynamic>));
  }
}

class AssistedTeleopResult extends RosMessage<AssistedTeleopResult> {
  late builtin_interfaces.Duration total_elapsed_time;
  late int error_code;

  static AssistedTeleopResult $prototype = AssistedTeleopResult();

  AssistedTeleopResult(
      {builtin_interfaces.Duration? total_elapsed_time, int? error_code})
      : total_elapsed_time =
            total_elapsed_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_Result';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (total_elapsed_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'total_elapsed_time': total_elapsed_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopResult fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopResult(
        total_elapsed_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['total_elapsed_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class AssistedTeleopFeedback extends RosMessage<AssistedTeleopFeedback> {
  late builtin_interfaces.Duration current_teleop_duration;

  static AssistedTeleopFeedback $prototype = AssistedTeleopFeedback();

  AssistedTeleopFeedback({builtin_interfaces.Duration? current_teleop_duration})
      : current_teleop_duration =
            current_teleop_duration ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_Feedback';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration current_teleop_duration''';

  @override
  int getMessageSize() {
    return (current_teleop_duration.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'current_teleop_duration': current_teleop_duration.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopFeedback fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopFeedback(
        current_teleop_duration: builtin_interfaces.Duration().fromJson(
            jsonMap['current_teleop_duration'] as Map<String, dynamic>));
  }
}

class AssistedTeleopActionGoal
    extends RosActionGoal<AssistedTeleopGoal, AssistedTeleopActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late AssistedTeleopGoal goal;

  static AssistedTeleopActionGoal $prototype = AssistedTeleopActionGoal();

  AssistedTeleopActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    AssistedTeleopGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? AssistedTeleopGoal();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_ActionGoal';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: AssistedTeleopGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class AssistedTeleopActionResult
    extends RosActionResult<AssistedTeleopResult, AssistedTeleopActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late AssistedTeleopResult result;

  static AssistedTeleopActionResult $prototype = AssistedTeleopActionResult();

  AssistedTeleopActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    AssistedTeleopResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? AssistedTeleopResult();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_ActionResult';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopActionResult fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: AssistedTeleopResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class AssistedTeleopActionFeedback extends RosActionFeedback<
    AssistedTeleopFeedback, AssistedTeleopActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late AssistedTeleopFeedback feedback;

  static AssistedTeleopActionFeedback $prototype =
      AssistedTeleopActionFeedback();

  AssistedTeleopActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    AssistedTeleopFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? AssistedTeleopFeedback();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop_ActionFeedback';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration current_teleop_duration''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AssistedTeleopActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return AssistedTeleopActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: AssistedTeleopFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class AssistedTeleop extends RosActionMessage<
    AssistedTeleopGoal,
    AssistedTeleopActionGoal,
    AssistedTeleopFeedback,
    AssistedTeleopActionFeedback,
    AssistedTeleopResult,
    AssistedTeleopActionResult> {
  @override
  AssistedTeleopActionGoal get actionGoal => AssistedTeleopActionGoal();

  @override
  AssistedTeleopActionFeedback get actionFeedback =>
      AssistedTeleopActionFeedback();

  @override
  AssistedTeleopActionResult get actionResult => AssistedTeleopActionResult();

  @override
  AssistedTeleopGoal get goal => AssistedTeleopGoal();

  @override
  AssistedTeleopFeedback get feedback => AssistedTeleopFeedback();

  @override
  AssistedTeleopResult get result => AssistedTeleopResult();

  @override
  String get fullType => 'nav2_msgs/action/AssistedTeleop';

  @override
  String get messageDefinition => '''
Goal:
builtin_interfaces/Duration time_allowance
---
Result:
builtin_interfaces/Duration total_elapsed_time
uint16 error_code
---
Feedback:
builtin_interfaces/Duration current_teleop_duration''';
}
