// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class DriveOnHeadingGoal extends RosMessage<DriveOnHeadingGoal> {
  late geometry_msgs.Point target;
  late double speed;
  late builtin_interfaces.Duration time_allowance;

  static DriveOnHeadingGoal $prototype = DriveOnHeadingGoal();

  DriveOnHeadingGoal(
      {geometry_msgs.Point? target,
      double? speed,
      builtin_interfaces.Duration? time_allowance})
      : target = target ?? geometry_msgs.Point(),
        speed = speed ?? 0.0,
        time_allowance = time_allowance ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_Goal';

  @override
  String get messageDefinition => '''geometry_msgs/Point target
float32 speed
builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return (target.getMessageSize()) + 4 + (time_allowance.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() => {
        'target': target.toJson(),
        'speed': speed,
        'time_allowance': time_allowance.toJson()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingGoal fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingGoal(
        target: geometry_msgs.Point()
            .fromJson(jsonMap['target'] as Map<String, dynamic>),
        speed: jsonMap['speed'] as double,
        time_allowance: builtin_interfaces.Duration()
            .fromJson(jsonMap['time_allowance'] as Map<String, dynamic>));
  }
}

class DriveOnHeadingResult extends RosMessage<DriveOnHeadingResult> {
  late builtin_interfaces.Duration total_elapsed_time;
  late int error_code;

  static DriveOnHeadingResult $prototype = DriveOnHeadingResult();

  DriveOnHeadingResult(
      {builtin_interfaces.Duration? total_elapsed_time, int? error_code})
      : total_elapsed_time =
            total_elapsed_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_Result';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (total_elapsed_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'total_elapsed_time': total_elapsed_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingResult fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingResult(
        total_elapsed_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['total_elapsed_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class DriveOnHeadingFeedback extends RosMessage<DriveOnHeadingFeedback> {
  late double distance_traveled;

  static DriveOnHeadingFeedback $prototype = DriveOnHeadingFeedback();

  DriveOnHeadingFeedback({double? distance_traveled})
      : distance_traveled = distance_traveled ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_Feedback';

  @override
  String get messageDefinition => '''float32 distance_traveled''';

  @override
  int getMessageSize() {
    return 4;
  }

  @override
  Map<String, dynamic> toJson() => {'distance_traveled': distance_traveled};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingFeedback fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingFeedback(
        distance_traveled: jsonMap['distance_traveled'] as double);
  }
}

class DriveOnHeadingActionGoal
    extends RosActionGoal<DriveOnHeadingGoal, DriveOnHeadingActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late DriveOnHeadingGoal goal;

  static DriveOnHeadingActionGoal $prototype = DriveOnHeadingActionGoal();

  DriveOnHeadingActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    DriveOnHeadingGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? DriveOnHeadingGoal();

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_ActionGoal';

  @override
  String get messageDefinition => '''geometry_msgs/Point target
float32 speed
builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: DriveOnHeadingGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class DriveOnHeadingActionResult
    extends RosActionResult<DriveOnHeadingResult, DriveOnHeadingActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late DriveOnHeadingResult result;

  static DriveOnHeadingActionResult $prototype = DriveOnHeadingActionResult();

  DriveOnHeadingActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    DriveOnHeadingResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? DriveOnHeadingResult();

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_ActionResult';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingActionResult fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: DriveOnHeadingResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class DriveOnHeadingActionFeedback extends RosActionFeedback<
    DriveOnHeadingFeedback, DriveOnHeadingActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late DriveOnHeadingFeedback feedback;

  static DriveOnHeadingActionFeedback $prototype =
      DriveOnHeadingActionFeedback();

  DriveOnHeadingActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    DriveOnHeadingFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? DriveOnHeadingFeedback();

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading_ActionFeedback';

  @override
  String get messageDefinition => '''float32 distance_traveled''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DriveOnHeadingActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return DriveOnHeadingActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: DriveOnHeadingFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class DriveOnHeading extends RosActionMessage<
    DriveOnHeadingGoal,
    DriveOnHeadingActionGoal,
    DriveOnHeadingFeedback,
    DriveOnHeadingActionFeedback,
    DriveOnHeadingResult,
    DriveOnHeadingActionResult> {
  @override
  DriveOnHeadingActionGoal get actionGoal => DriveOnHeadingActionGoal();

  @override
  DriveOnHeadingActionFeedback get actionFeedback =>
      DriveOnHeadingActionFeedback();

  @override
  DriveOnHeadingActionResult get actionResult => DriveOnHeadingActionResult();

  @override
  DriveOnHeadingGoal get goal => DriveOnHeadingGoal();

  @override
  DriveOnHeadingFeedback get feedback => DriveOnHeadingFeedback();

  @override
  DriveOnHeadingResult get result => DriveOnHeadingResult();

  @override
  String get fullType => 'nav2_msgs/action/DriveOnHeading';

  @override
  String get messageDefinition => '''
Goal:
geometry_msgs/Point target
float32 speed
builtin_interfaces/Duration time_allowance
---
Result:
builtin_interfaces/Duration total_elapsed_time
uint16 error_code
---
Feedback:
float32 distance_traveled''';
}
