// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class DummyBehaviorGoal extends RosMessage<DummyBehaviorGoal> {
  late std_msgs.StringMessage command;

  static DummyBehaviorGoal $prototype = DummyBehaviorGoal();

  DummyBehaviorGoal({std_msgs.StringMessage? command})
      : command = command ?? std_msgs.StringMessage();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_Goal';

  @override
  String get messageDefinition => '''std_msgs/String command''';

  @override
  int getMessageSize() {
    return command.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {'command': command.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorGoal fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorGoal(
        command: std_msgs.StringMessage()
            .fromJson(jsonMap['command'] as Map<String, dynamic>));
  }
}

class DummyBehaviorResult extends RosMessage<DummyBehaviorResult> {
  late builtin_interfaces.Duration total_elapsed_time;
  late int error_code;

  static DummyBehaviorResult $prototype = DummyBehaviorResult();

  DummyBehaviorResult(
      {builtin_interfaces.Duration? total_elapsed_time, int? error_code})
      : total_elapsed_time =
            total_elapsed_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_Result';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (total_elapsed_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'total_elapsed_time': total_elapsed_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorResult fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorResult(
        total_elapsed_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['total_elapsed_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class DummyBehaviorFeedback extends RosMessage<DummyBehaviorFeedback> {
  static DummyBehaviorFeedback $prototype = DummyBehaviorFeedback();

  DummyBehaviorFeedback();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_Feedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorFeedback fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorFeedback();
  }
}

class DummyBehaviorActionGoal
    extends RosActionGoal<DummyBehaviorGoal, DummyBehaviorActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late DummyBehaviorGoal goal;

  static DummyBehaviorActionGoal $prototype = DummyBehaviorActionGoal();

  DummyBehaviorActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    DummyBehaviorGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? DummyBehaviorGoal();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_ActionGoal';

  @override
  String get messageDefinition => '''std_msgs/String command''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal:
          DummyBehaviorGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class DummyBehaviorActionResult
    extends RosActionResult<DummyBehaviorResult, DummyBehaviorActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late DummyBehaviorResult result;

  static DummyBehaviorActionResult $prototype = DummyBehaviorActionResult();

  DummyBehaviorActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    DummyBehaviorResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? DummyBehaviorResult();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_ActionResult';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorActionResult fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: DummyBehaviorResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class DummyBehaviorActionFeedback extends RosActionFeedback<
    DummyBehaviorFeedback, DummyBehaviorActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late DummyBehaviorFeedback feedback;

  static DummyBehaviorActionFeedback $prototype = DummyBehaviorActionFeedback();

  DummyBehaviorActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    DummyBehaviorFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? DummyBehaviorFeedback();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior_ActionFeedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  DummyBehaviorActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return DummyBehaviorActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: DummyBehaviorFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class DummyBehavior extends RosActionMessage<
    DummyBehaviorGoal,
    DummyBehaviorActionGoal,
    DummyBehaviorFeedback,
    DummyBehaviorActionFeedback,
    DummyBehaviorResult,
    DummyBehaviorActionResult> {
  @override
  DummyBehaviorActionGoal get actionGoal => DummyBehaviorActionGoal();

  @override
  DummyBehaviorActionFeedback get actionFeedback =>
      DummyBehaviorActionFeedback();

  @override
  DummyBehaviorActionResult get actionResult => DummyBehaviorActionResult();

  @override
  DummyBehaviorGoal get goal => DummyBehaviorGoal();

  @override
  DummyBehaviorFeedback get feedback => DummyBehaviorFeedback();

  @override
  DummyBehaviorResult get result => DummyBehaviorResult();

  @override
  String get fullType => 'nav2_msgs/action/DummyBehavior';

  @override
  String get messageDefinition => '''
Goal:
std_msgs/String command
---
Result:
builtin_interfaces/Duration total_elapsed_time
uint16 error_code
---
Feedback:
''';
}
