// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import '../msg/MissedWaypoint.dart';

class FollowWaypointsGoal extends RosMessage<FollowWaypointsGoal> {
  late int number_of_loops;
  late int goal_index;
  late List<geometry_msgs.PoseStamped> poses;

  static FollowWaypointsGoal $prototype = FollowWaypointsGoal();

  FollowWaypointsGoal(
      {int? number_of_loops,
      int? goal_index,
      List<geometry_msgs.PoseStamped>? poses})
      : number_of_loops = number_of_loops ?? 0,
        goal_index = goal_index ?? 0,
        poses = poses ?? const [];

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_Goal';

  @override
  String get messageDefinition => '''uint32 number_of_loops
uint32 goal_index
geometry_msgs/PoseStamped[] poses''';

  @override
  int getMessageSize() {
    return 4 +
        4 +
        4 +
        poses.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'number_of_loops': number_of_loops,
        'goal_index': goal_index,
        'poses': poses.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsGoal fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsGoal(
        number_of_loops: jsonMap['number_of_loops'] as int,
        goal_index: jsonMap['goal_index'] as int,
        poses: (jsonMap['poses'] as List<dynamic>)
            .map((item) => geometry_msgs.PoseStamped()
                .fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class FollowWaypointsResult extends RosMessage<FollowWaypointsResult> {
  late List<MissedWaypoint> missed_waypoints;

  static FollowWaypointsResult $prototype = FollowWaypointsResult();

  FollowWaypointsResult({List<MissedWaypoint>? missed_waypoints})
      : missed_waypoints = missed_waypoints ?? const [];

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_Result';

  @override
  String get messageDefinition => '''MissedWaypoint[] missed_waypoints''';

  @override
  int getMessageSize() {
    return 4 +
        missed_waypoints.fold<int>(
            0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'missed_waypoints':
            missed_waypoints.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsResult fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsResult(
        missed_waypoints: (jsonMap['missed_waypoints'] as List<dynamic>)
            .map((item) =>
                MissedWaypoint().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class FollowWaypointsFeedback extends RosMessage<FollowWaypointsFeedback> {
  late int current_waypoint;

  static FollowWaypointsFeedback $prototype = FollowWaypointsFeedback();

  FollowWaypointsFeedback({int? current_waypoint})
      : current_waypoint = current_waypoint ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_Feedback';

  @override
  String get messageDefinition => '''uint32 current_waypoint''';

  @override
  int getMessageSize() {
    return 4;
  }

  @override
  Map<String, dynamic> toJson() => {'current_waypoint': current_waypoint};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsFeedback fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsFeedback(
        current_waypoint: jsonMap['current_waypoint'] as int);
  }
}

class FollowWaypointsActionGoal
    extends RosActionGoal<FollowWaypointsGoal, FollowWaypointsActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late FollowWaypointsGoal goal;

  static FollowWaypointsActionGoal $prototype = FollowWaypointsActionGoal();

  FollowWaypointsActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    FollowWaypointsGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? FollowWaypointsGoal();

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_ActionGoal';

  @override
  String get messageDefinition => '''uint32 number_of_loops
uint32 goal_index
geometry_msgs/PoseStamped[] poses''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: FollowWaypointsGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class FollowWaypointsActionResult extends RosActionResult<FollowWaypointsResult,
    FollowWaypointsActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late FollowWaypointsResult result;

  static FollowWaypointsActionResult $prototype = FollowWaypointsActionResult();

  FollowWaypointsActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    FollowWaypointsResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? FollowWaypointsResult();

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_ActionResult';

  @override
  String get messageDefinition => '''MissedWaypoint[] missed_waypoints''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsActionResult fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: FollowWaypointsResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class FollowWaypointsActionFeedback extends RosActionFeedback<
    FollowWaypointsFeedback, FollowWaypointsActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late FollowWaypointsFeedback feedback;

  static FollowWaypointsActionFeedback $prototype =
      FollowWaypointsActionFeedback();

  FollowWaypointsActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    FollowWaypointsFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? FollowWaypointsFeedback();

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints_ActionFeedback';

  @override
  String get messageDefinition => '''uint32 current_waypoint''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowWaypointsActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return FollowWaypointsActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: FollowWaypointsFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class FollowWaypoints extends RosActionMessage<
    FollowWaypointsGoal,
    FollowWaypointsActionGoal,
    FollowWaypointsFeedback,
    FollowWaypointsActionFeedback,
    FollowWaypointsResult,
    FollowWaypointsActionResult> {
  @override
  FollowWaypointsActionGoal get actionGoal => FollowWaypointsActionGoal();

  @override
  FollowWaypointsActionFeedback get actionFeedback =>
      FollowWaypointsActionFeedback();

  @override
  FollowWaypointsActionResult get actionResult => FollowWaypointsActionResult();

  @override
  FollowWaypointsGoal get goal => FollowWaypointsGoal();

  @override
  FollowWaypointsFeedback get feedback => FollowWaypointsFeedback();

  @override
  FollowWaypointsResult get result => FollowWaypointsResult();

  @override
  String get fullType => 'nav2_msgs/action/FollowWaypoints';

  @override
  String get messageDefinition => '''
Goal:
uint32 number_of_loops
uint32 goal_index
geometry_msgs/PoseStamped[] poses
---
Result:
MissedWaypoint[] missed_waypoints
---
Feedback:
uint32 current_waypoint''';
}
