// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class SpinGoal extends RosMessage<SpinGoal> {
  late double target_yaw;
  late builtin_interfaces.Duration time_allowance;

  static SpinGoal $prototype = SpinGoal();

  SpinGoal({double? target_yaw, builtin_interfaces.Duration? time_allowance})
      : target_yaw = target_yaw ?? 0.0,
        time_allowance = time_allowance ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/Spin_Goal';

  @override
  String get messageDefinition => '''float32 target_yaw
builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return 4 + (time_allowance.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'target_yaw': target_yaw, 'time_allowance': time_allowance.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinGoal fromJson(Map<String, dynamic> jsonMap) {
    return SpinGoal(
        target_yaw: jsonMap['target_yaw'] as double,
        time_allowance: builtin_interfaces.Duration()
            .fromJson(jsonMap['time_allowance'] as Map<String, dynamic>));
  }
}

class SpinResult extends RosMessage<SpinResult> {
  late builtin_interfaces.Duration total_elapsed_time;
  late int error_code;

  static SpinResult $prototype = SpinResult();

  SpinResult({builtin_interfaces.Duration? total_elapsed_time, int? error_code})
      : total_elapsed_time =
            total_elapsed_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/Spin_Result';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (total_elapsed_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'total_elapsed_time': total_elapsed_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinResult fromJson(Map<String, dynamic> jsonMap) {
    return SpinResult(
        total_elapsed_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['total_elapsed_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class SpinFeedback extends RosMessage<SpinFeedback> {
  late double angular_distance_traveled;

  static SpinFeedback $prototype = SpinFeedback();

  SpinFeedback({double? angular_distance_traveled})
      : angular_distance_traveled = angular_distance_traveled ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/action/Spin_Feedback';

  @override
  String get messageDefinition => '''float32 angular_distance_traveled''';

  @override
  int getMessageSize() {
    return 4;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'angular_distance_traveled': angular_distance_traveled};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinFeedback fromJson(Map<String, dynamic> jsonMap) {
    return SpinFeedback(
        angular_distance_traveled:
            jsonMap['angular_distance_traveled'] as double);
  }
}

class SpinActionGoal extends RosActionGoal<SpinGoal, SpinActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late SpinGoal goal;

  static SpinActionGoal $prototype = SpinActionGoal();

  SpinActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    SpinGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? SpinGoal();

  @override
  String get fullType => 'nav2_msgs/action/Spin_ActionGoal';

  @override
  String get messageDefinition => '''float32 target_yaw
builtin_interfaces/Duration time_allowance''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return SpinActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: SpinGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class SpinActionResult extends RosActionResult<SpinResult, SpinActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late SpinResult result;

  static SpinActionResult $prototype = SpinActionResult();

  SpinActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    SpinResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? SpinResult();

  @override
  String get fullType => 'nav2_msgs/action/Spin_ActionResult';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinActionResult fromJson(Map<String, dynamic> jsonMap) {
    return SpinActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: SpinResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class SpinActionFeedback
    extends RosActionFeedback<SpinFeedback, SpinActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late SpinFeedback feedback;

  static SpinActionFeedback $prototype = SpinActionFeedback();

  SpinActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    SpinFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? SpinFeedback();

  @override
  String get fullType => 'nav2_msgs/action/Spin_ActionFeedback';

  @override
  String get messageDefinition => '''float32 angular_distance_traveled''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpinActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return SpinActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback:
          SpinFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class Spin extends RosActionMessage<SpinGoal, SpinActionGoal, SpinFeedback,
    SpinActionFeedback, SpinResult, SpinActionResult> {
  @override
  SpinActionGoal get actionGoal => SpinActionGoal();

  @override
  SpinActionFeedback get actionFeedback => SpinActionFeedback();

  @override
  SpinActionResult get actionResult => SpinActionResult();

  @override
  SpinGoal get goal => SpinGoal();

  @override
  SpinFeedback get feedback => SpinFeedback();

  @override
  SpinResult get result => SpinResult();

  @override
  String get fullType => 'nav2_msgs/action/Spin';

  @override
  String get messageDefinition => '''
Goal:
float32 target_yaw
builtin_interfaces/Duration time_allowance
---
Result:
builtin_interfaces/Duration total_elapsed_time
uint16 error_code
---
Feedback:
float32 angular_distance_traveled''';
}
