// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class EmptyRequest extends RosMessage<EmptyRequest> {
  static EmptyRequest $prototype = EmptyRequest();

  // Constructor
  EmptyRequest();

  @override
  String get fullType => 'std_srvs/srv/Empty_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  EmptyRequest fromJson(Map<String, dynamic> jsonMap) {
    return EmptyRequest();
  }
}

class EmptyResponse extends RosMessage<EmptyResponse> {
  static EmptyResponse $prototype = EmptyResponse();

  // Constructor
  EmptyResponse();

  @override
  String get fullType => 'std_srvs/srv/Empty_Response';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  EmptyResponse fromJson(Map<String, dynamic> jsonMap) {
    return EmptyResponse();
  }
}

class Empty extends RosServiceMessage<EmptyRequest, EmptyResponse> {
  @override
  EmptyRequest get request => EmptyRequest();

  @override
  EmptyResponse get response => EmptyResponse();

  @override
  String get fullType => 'std_srvs/srv/Empty';

  @override
  String get messageDefinition => '''
---
''';
}
