// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class SetBoolRequest extends RosMessage<SetBoolRequest> {
  bool data;

  static SetBoolRequest $prototype = SetBoolRequest();

  SetBoolRequest({this.data = false});
  @override
  String get fullType => 'std_srvs/srv/SetBool_Request';

  @override
  String get messageDefinition => '''bool data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SetBoolRequest fromJson(Map<String, dynamic> jsonMap) {
    return SetBoolRequest(data: jsonMap['data'] as bool);
  }
}

class SetBoolResponse extends RosMessage<SetBoolResponse> {
  bool success;
  String message;

  static SetBoolResponse $prototype = SetBoolResponse();

  // Constructor
  SetBoolResponse({this.success = false, this.message = ''});

  @override
  String get fullType => 'std_srvs/srv/SetBool_Response';

  @override
  String get messageDefinition => '''bool success
string message''';

  @override
  int getMessageSize() {
    return (1 + 4 + message.length).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SetBoolResponse fromJson(Map<String, dynamic> jsonMap) {
    return SetBoolResponse(
        success: jsonMap['success'] as bool,
        message: jsonMap['message'] as String);
  }
}

class SetBool extends RosServiceMessage<SetBoolRequest, SetBoolResponse> {
  @override
  SetBoolRequest get request => SetBoolRequest();

  @override
  SetBoolResponse get response => SetBoolResponse();

  @override
  String get fullType => 'std_srvs/srv/SetBool';

  @override
  String get messageDefinition =>
      '''bool data # e.g. for hardware enabling / disabling
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages''';
}
