// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Duration extends RosMessage<Duration> {
  int sec;
  int nanosec;

  static Duration $prototype = Duration();

  // Constructor
  Duration({this.sec = 0, this.nanosec = 0});

  @override
  String get fullType => 'builtin_interfaces/msg/Duration';

  @override
  String get messageDefinition => '''int32 sec
uint32 nanosec''';

  @override
  int getMessageSize() {
    return (4 + 4).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'sec': sec, 'nanosec': nanosec};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Duration fromJson(Map<String, dynamic> jsonMap) {
    return Duration(
        sec: jsonMap['sec'] as int, nanosec: jsonMap['nanosec'] as int);
  }
}
