// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class CameraRequest extends RosMessage<CameraRequest> {
  late int direction;
  late bool status;

  static CameraRequest $prototype = CameraRequest();

  CameraRequest({int? direction, bool? status})
      : direction = direction ?? 0,
        status = status ?? false;

  @override
  String get fullType => 'rio_interfaces/srv/Camera_Request';

  @override
  String get messageDefinition => '''int direction bool status''';

  @override
  int getMessageSize() {
    return 4 + 1;
  }

  @override
  Map<String, dynamic> toJson() => {'direction': direction, 'status': status};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  CameraRequest fromJson(Map<String, dynamic> jsonMap) {
    return CameraRequest(
        direction: jsonMap['direction'] as int,
        status: jsonMap['status'] as bool);
  }
}

class CameraResponse extends RosMessage<CameraResponse> {
  late bool success;
  late String message;

  static CameraResponse $prototype = CameraResponse();

  CameraResponse({bool? success, String? message})
      : success = success ?? false,
        message = message ?? '';

  @override
  String get fullType => 'rio_interfaces/srv/Camera_Response';

  @override
  String get messageDefinition => '''bool success string message''';

  @override
  int getMessageSize() {
    return 1 + message.length;
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  CameraResponse fromJson(Map<String, dynamic> jsonMap) {
    return CameraResponse(
        success: jsonMap['success'] as bool,
        message: jsonMap['message'] as String);
  }
}

class Camera extends RosServiceMessage<CameraRequest, CameraResponse> {
  @override
  CameraRequest get request => CameraRequest();

  @override
  CameraResponse get response => CameraResponse();

  @override
  String get fullType => 'rio_interfaces/srv/Camera';

  @override
  String get messageDefinition => '''
int direction
---
bool success string message''';
}
