// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'GeoPoint.dart';

class BoundingBox extends RosMessage<BoundingBox> {
  late GeoPoint min_pt;
  late GeoPoint max_pt;

  static BoundingBox $prototype = BoundingBox();

  // Constructor
  BoundingBox({GeoPoint? min_pt, GeoPoint? max_pt})
      : min_pt = min_pt ?? GeoPoint(),
        max_pt = max_pt ?? GeoPoint();

  @override
  String get fullType => 'geographic_msgs/msg/BoundingBox';

  @override
  String get messageDefinition => '''GeoPoint min_pt
GeoPoint max_pt''';

  @override
  int getMessageSize() {
    return (min_pt.getMessageSize()) + (max_pt.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'min_pt': min_pt.toJson(), 'max_pt': max_pt.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  BoundingBox fromJson(Map<String, dynamic> jsonMap) {
    return BoundingBox(
        min_pt: GeoPoint().fromJson(jsonMap['min_pt'] as Map<String, dynamic>),
        max_pt: GeoPoint().fromJson(jsonMap['max_pt'] as Map<String, dynamic>));
  }
}
