// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'GeographicMap.dart';

class GeographicMapChanges extends RosMessage<GeographicMapChanges> {
  late std_msgs.Header header;
  late GeographicMap diffs;
  late List<unique_identifier_msgs.UUID> deletes;

  static GeographicMapChanges $prototype = GeographicMapChanges();

  // Constructor
  GeographicMapChanges(
      {std_msgs.Header? header,
      GeographicMap? diffs,
      List<unique_identifier_msgs.UUID>? deletes})
      : header = header ?? std_msgs.Header(),
        diffs = diffs ?? GeographicMap(),
        deletes = deletes ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/GeographicMapChanges';

  @override
  String get messageDefinition => '''std_msgs/Header header
GeographicMap diffs
unique_identifier_msgs/UUID[] deletes''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) +
        (diffs.getMessageSize()) +
        4 +
        deletes.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'diffs': diffs.toJson(),
        'deletes': deletes.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeographicMapChanges fromJson(Map<String, dynamic> jsonMap) {
    return GeographicMapChanges(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        diffs:
            GeographicMap().fromJson(jsonMap['diffs'] as Map<String, dynamic>),
        deletes: (jsonMap['deletes'] as List<dynamic>)
            .map((item) => unique_identifier_msgs
                .UUID()
                .fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
