// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'GeoPoseStamped.dart';

class GeoPath extends RosMessage<GeoPath> {
  late std_msgs.Header header;
  late List<GeoPoseStamped> poses;

  static GeoPath $prototype = GeoPath();

  // Constructor
  GeoPath({std_msgs.Header? header, List<GeoPoseStamped>? poses})
      : header = header ?? std_msgs.Header(),
        poses = poses ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/GeoPath';

  @override
  String get messageDefinition => '''std_msgs/Header header
geographic_msgs/GeoPoseStamped[] poses''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) +
        4 +
        poses.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'poses': poses.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPath fromJson(Map<String, dynamic> jsonMap) {
    return GeoPath(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        poses: (jsonMap['poses'] as List<dynamic>)
            .map((item) =>
                GeoPoseStamped().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
