// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'GeoPose.dart';

class GeoPoseStamped extends RosMessage<GeoPoseStamped> {
  late std_msgs.Header header;
  late GeoPose pose;

  static GeoPoseStamped $prototype = GeoPoseStamped();

  // Constructor
  GeoPoseStamped({std_msgs.Header? header, GeoPose? pose})
      : header = header ?? std_msgs.Header(),
        pose = pose ?? GeoPose();

  @override
  String get fullType => 'geographic_msgs/msg/GeoPoseStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
geographic_msgs/GeoPose pose''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) + (pose.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'pose': pose.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPoseStamped fromJson(Map<String, dynamic> jsonMap) {
    return GeoPoseStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        pose: GeoPose().fromJson(jsonMap['pose'] as Map<String, dynamic>));
  }
}
