// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'GeoPoseWithCovariance.dart';

class GeoPoseWithCovarianceStamped
    extends RosMessage<GeoPoseWithCovarianceStamped> {
  late std_msgs.Header header;
  late GeoPoseWithCovariance pose;

  static GeoPoseWithCovarianceStamped $prototype =
      GeoPoseWithCovarianceStamped();

  // Constructor
  GeoPoseWithCovarianceStamped(
      {std_msgs.Header? header, GeoPoseWithCovariance? pose})
      : header = header ?? std_msgs.Header(),
        pose = pose ?? GeoPoseWithCovariance();

  @override
  String get fullType => 'geographic_msgs/msg/GeoPoseWithCovarianceStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
geographic_msgs/GeoPoseWithCovariance pose''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) + (pose.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'pose': pose.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPoseWithCovarianceStamped fromJson(Map<String, dynamic> jsonMap) {
    return GeoPoseWithCovarianceStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        pose: GeoPoseWithCovariance()
            .fromJson(jsonMap['pose'] as Map<String, dynamic>));
  }
}
