// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class KeyValue extends RosMessage<KeyValue> {
  late String key;
  late String value;

  static KeyValue $prototype = KeyValue();

  // Constructor
  KeyValue({String? key, String? value})
      : key = key ?? '',
        value = value ?? '';

  @override
  String get fullType => 'geographic_msgs/msg/KeyValue';

  @override
  String get messageDefinition => '''string key
string value''';

  @override
  int getMessageSize() {
    return 4 + key.length + 4 + value.length;
  }

  @override
  Map<String, dynamic> toJson() => {'key': key, 'value': value};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  KeyValue fromJson(Map<String, dynamic> jsonMap) {
    return KeyValue(
        key: jsonMap['key'] as String, value: jsonMap['value'] as String);
  }
}
