// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'KeyValue.dart';

class MapFeature extends RosMessage<MapFeature> {
  late unique_identifier_msgs.UUID id;
  late List<unique_identifier_msgs.UUID> components;
  late List<KeyValue> props;

  static MapFeature $prototype = MapFeature();

  // Constructor
  MapFeature(
      {unique_identifier_msgs.UUID? id,
      List<unique_identifier_msgs.UUID>? components,
      List<KeyValue>? props})
      : id = id ?? unique_identifier_msgs.UUID(),
        components = components ?? const [],
        props = props ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/MapFeature';

  @override
  String get messageDefinition => '''unique_identifier_msgs/UUID id
unique_identifier_msgs/UUID[] components
KeyValue[] props''';

  @override
  int getMessageSize() {
    return (id.getMessageSize()) +
        4 +
        components.fold<int>(0, (sum, item) => sum + (item.getMessageSize())) +
        4 +
        props.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'id': id.toJson(),
        'components': components.map((item) => item.toJson()).toList(),
        'props': props.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MapFeature fromJson(Map<String, dynamic> jsonMap) {
    return MapFeature(
        id: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['id'] as Map<String, dynamic>),
        components: (jsonMap['components'] as List<dynamic>)
            .map((item) => unique_identifier_msgs
                .UUID()
                .fromJson(item as Map<String, dynamic>))
            .toList(),
        props: (jsonMap['props'] as List<dynamic>)
            .map((item) => KeyValue().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
