// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'KeyValue.dart';

class RoutePath extends RosMessage<RoutePath> {
  late std_msgs.Header header;
  late unique_identifier_msgs.UUID network;
  late List<unique_identifier_msgs.UUID> segments;
  late List<KeyValue> props;

  static RoutePath $prototype = RoutePath();

  // Constructor
  RoutePath(
      {std_msgs.Header? header,
      unique_identifier_msgs.UUID? network,
      List<unique_identifier_msgs.UUID>? segments,
      List<KeyValue>? props})
      : header = header ?? std_msgs.Header(),
        network = network ?? unique_identifier_msgs.UUID(),
        segments = segments ?? const [],
        props = props ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/RoutePath';

  @override
  String get messageDefinition => '''std_msgs/Header header
unique_identifier_msgs/UUID network
unique_identifier_msgs/UUID[] segments
KeyValue[] props''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) +
        (network.getMessageSize()) +
        4 +
        segments.fold<int>(0, (sum, item) => sum + (item.getMessageSize())) +
        4 +
        props.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'network': network.toJson(),
        'segments': segments.map((item) => item.toJson()).toList(),
        'props': props.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  RoutePath fromJson(Map<String, dynamic> jsonMap) {
    return RoutePath(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        network: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['network'] as Map<String, dynamic>),
        segments: (jsonMap['segments'] as List<dynamic>)
            .map((item) => unique_identifier_msgs
                .UUID()
                .fromJson(item as Map<String, dynamic>))
            .toList(),
        props: (jsonMap['props'] as List<dynamic>)
            .map((item) => KeyValue().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
