// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'KeyValue.dart';

class RouteSegment extends RosMessage<RouteSegment> {
  late unique_identifier_msgs.UUID id;
  late unique_identifier_msgs.UUID start;
  late unique_identifier_msgs.UUID end;
  late List<KeyValue> props;

  static RouteSegment $prototype = RouteSegment();

  // Constructor
  RouteSegment(
      {unique_identifier_msgs.UUID? id,
      unique_identifier_msgs.UUID? start,
      unique_identifier_msgs.UUID? end,
      List<KeyValue>? props})
      : id = id ?? unique_identifier_msgs.UUID(),
        start = start ?? unique_identifier_msgs.UUID(),
        end = end ?? unique_identifier_msgs.UUID(),
        props = props ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/RouteSegment';

  @override
  String get messageDefinition => '''unique_identifier_msgs/UUID id
unique_identifier_msgs/UUID start
unique_identifier_msgs/UUID end
KeyValue[] props''';

  @override
  int getMessageSize() {
    return (id.getMessageSize()) +
        (start.getMessageSize()) +
        (end.getMessageSize()) +
        4 +
        props.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'id': id.toJson(),
        'start': start.toJson(),
        'end': end.toJson(),
        'props': props.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  RouteSegment fromJson(Map<String, dynamic> jsonMap) {
    return RouteSegment(
        id: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['id'] as Map<String, dynamic>),
        start: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['start'] as Map<String, dynamic>),
        end: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['end'] as Map<String, dynamic>),
        props: (jsonMap['props'] as List<dynamic>)
            .map((item) => KeyValue().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
