// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'BoundingBox.dart';
import 'WayPoint.dart';
import 'RouteSegment.dart';
import 'KeyValue.dart';

class RouteNetwork extends RosMessage<RouteNetwork> {
  late std_msgs.Header header;
  late unique_identifier_msgs.UUID id;
  late BoundingBox bounds;
  late List<WayPoint> points;
  late List<RouteSegment> segments;
  late List<KeyValue> props;

  static RouteNetwork $prototype = RouteNetwork();

  // Constructor
  RouteNetwork(
      {std_msgs.Header? header,
      unique_identifier_msgs.UUID? id,
      BoundingBox? bounds,
      List<WayPoint>? points,
      List<RouteSegment>? segments,
      List<KeyValue>? props})
      : header = header ?? std_msgs.Header(),
        id = id ?? unique_identifier_msgs.UUID(),
        bounds = bounds ?? BoundingBox(),
        points = points ?? const [],
        segments = segments ?? const [],
        props = props ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/RouteNetwork';

  @override
  String get messageDefinition => '''std_msgs/Header header
unique_identifier_msgs/UUID id
BoundingBox bounds
WayPoint[] points
RouteSegment[] segments
KeyValue[] props''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) +
        (id.getMessageSize()) +
        (bounds.getMessageSize()) +
        4 +
        points.fold<int>(0, (sum, item) => sum + (item.getMessageSize())) +
        4 +
        segments.fold<int>(0, (sum, item) => sum + (item.getMessageSize())) +
        4 +
        props.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'id': id.toJson(),
        'bounds': bounds.toJson(),
        'points': points.map((item) => item.toJson()).toList(),
        'segments': segments.map((item) => item.toJson()).toList(),
        'props': props.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  RouteNetwork fromJson(Map<String, dynamic> jsonMap) {
    return RouteNetwork(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        id: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['id'] as Map<String, dynamic>),
        bounds:
            BoundingBox().fromJson(jsonMap['bounds'] as Map<String, dynamic>),
        points: (jsonMap['points'] as List<dynamic>)
            .map((item) => WayPoint().fromJson(item as Map<String, dynamic>))
            .toList(),
        segments: (jsonMap['segments'] as List<dynamic>)
            .map(
                (item) => RouteSegment().fromJson(item as Map<String, dynamic>))
            .toList(),
        props: (jsonMap['props'] as List<dynamic>)
            .map((item) => KeyValue().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
