// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'MultiArrayLayout.dart';

class ByteMultiArray extends RosMessage<ByteMultiArray> {
  MultiArrayLayout layout;
  List<int> data;

  static ByteMultiArray $prototype = ByteMultiArray();

  // Constructor
  ByteMultiArray({
    MultiArrayLayout? layout,
    List<int>? data,
  })  : layout = layout ?? MultiArrayLayout(),
        data = data ?? const [];

  @override
  String get fullType => 'std_msgs/msg/ByteMultiArray';

  @override
  String get messageDefinition => '''MultiArrayLayout layout
byte[] data''';

  @override
  int getMessageSize() {
    return (layout.getMessageSize() + 4 + (data.length * 1)).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'layout': layout.toJson(), 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ByteMultiArray fromJson(Map<String, dynamic> jsonMap) {
    return ByteMultiArray(
        layout: MultiArrayLayout()
            .fromJson(jsonMap['layout'] as Map<String, dynamic>),
        data: (jsonMap['data'] as List).cast<int>());
  }
}
