// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class Char extends RosMessage<Char> {
  String data;

  static Char $prototype = Char();

  // Constructor
  Char({this.data = ''});

  @override
  String get fullType => 'std_msgs/msg/Char';

  @override
  String get messageDefinition => '''char data''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Char fromJson(Map<String, dynamic> jsonMap) {
    return Char(data: jsonMap['data'] as String);
  }
}
