// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

import 'MultiArrayLayout.dart';

class Int64MultiArray extends RosMessage<Int64MultiArray> {
  MultiArrayLayout layout;
  List<int> data;

  static Int64MultiArray $prototype = Int64MultiArray();

  // Constructor
  Int64MultiArray({
    MultiArrayLayout? layout,
    List<int>? data,
  })  : layout = layout ?? MultiArrayLayout(),
        data = data ?? [];
  @override
  String get fullType => 'std_msgs/msg/Int64MultiArray';

  @override
  String get messageDefinition => '''MultiArrayLayout layout
int64[] data''';

  @override
  int getMessageSize() {
    return (layout.getMessageSize() + 4 + (data.length * 8)).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'layout': layout.toJson(), 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Int64MultiArray fromJson(Map<String, dynamic> jsonMap) {
    return Int64MultiArray(
        layout: MultiArrayLayout()
            .fromJson(jsonMap['layout'] as Map<String, dynamic>),
        data: (jsonMap['data'] as List).cast<int>());
  }
}
