// Generated by ros_to_dart_converter
// Do not edit manually

import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'dart:convert';

class StringMessage extends RosMessage<StringMessage> {
  String data;

  static StringMessage $prototype = StringMessage();

  // Constructor
  StringMessage({this.data = ''});

  @override
  String get fullType => 'std_msgs/msg/String';

  @override
  String get messageDefinition => '''string data''';

  @override
  int getMessageSize() {
    return (4 + data.length).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  StringMessage fromJson(Map<String, dynamic> jsonMap) {
    return StringMessage(data: jsonMap['data'] as String);
  }
}
