// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class CollisionMonitorState extends RosMessage<CollisionMonitorState> {
  int action_type;
  String polygon_name;

  static CollisionMonitorState $prototype = CollisionMonitorState();

  // Constructor
  CollisionMonitorState({int? action_type, String? polygon_name})
      : action_type = action_type ?? 0,
        polygon_name = polygon_name ?? '';

  @override
  String get fullType => 'nav2_msgs/msg/CollisionMonitorState';

  @override
  String get messageDefinition => '''uint8 action_type
string polygon_name''';

  @override
  int getMessageSize() {
    return (1 + 4 + polygon_name.length).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'action_type': action_type, 'polygon_name': polygon_name};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  CollisionMonitorState fromJson(Map<String, dynamic> jsonMap) {
    return CollisionMonitorState(
        action_type: jsonMap['action_type'] as int,
        polygon_name: jsonMap['polygon_name'] as String);
  }
}
