// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class CollisionDetectorState extends RosMessage<CollisionDetectorState> {
  List<String> polygons;
  List<bool> detections;

  static CollisionDetectorState $prototype = CollisionDetectorState();

  // Constructor
  CollisionDetectorState({List<String>? polygons, List<bool>? detections})
      : polygons = polygons ?? const [],
        detections = detections ?? const [];

  @override
  String get fullType => 'nav2_msgs/msg/CollisionDetectorState';

  @override
  String get messageDefinition => '''string[] polygons
bool[] detections''';

  @override
  int getMessageSize() {
    return (4 + (polygons.length * 0) + 4 + (detections.length * 1)).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'polygons': polygons, 'detections': detections};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  CollisionDetectorState fromJson(Map<String, dynamic> jsonMap) {
    return CollisionDetectorState(
        polygons: (jsonMap['polygons'] as List).cast<String>(),
        detections: (jsonMap['detections'] as List).cast<bool>());
  }
}
