// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'CostmapMetaData.dart';

class Costmap extends RosMessage<Costmap> {
  std_msgs.Header header;
  CostmapMetaData metadata;
  List<int> data;

  static Costmap $prototype = Costmap();

  // Constructor
  Costmap({std_msgs.Header? header, CostmapMetaData? metadata, List<int>? data})
      : header = header ?? std_msgs.Header(),
        metadata = metadata ?? CostmapMetaData(),
        data = data ?? const [];

  @override
  String get fullType => 'nav2_msgs/msg/Costmap';

  @override
  String get messageDefinition => '''std_msgs/Header header
CostmapMetaData metadata
uint8[] data''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            metadata.getMessageSize() +
            4 +
            (data.length * 1))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'metadata': metadata.toJson(), 'data': data};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Costmap fromJson(Map<String, dynamic> jsonMap) {
    return Costmap(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        metadata: CostmapMetaData()
            .fromJson(jsonMap['metadata'] as Map<String, dynamic>),
        data: (jsonMap['data'] as List).cast<int>());
  }
}
