// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Particle.dart';

class ParticleCloud extends RosMessage<ParticleCloud> {
  std_msgs.Header header;
  List<Particle> particles;

  static ParticleCloud $prototype = ParticleCloud();

  // Constructor
  ParticleCloud({std_msgs.Header? header, List<Particle>? particles})
      : header = header ?? std_msgs.Header(),
        particles = particles ?? const [];

  @override
  String get fullType => 'nav2_msgs/msg/ParticleCloud';

  @override
  String get messageDefinition => '''std_msgs/Header header
Particle[] particles''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            particles.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'particles': particles.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ParticleCloud fromJson(Map<String, dynamic> jsonMap) {
    return ParticleCloud(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        particles: (jsonMap['particles'] as List)
            .map((item) => Particle().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
