// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class SpeedLimit extends RosMessage<SpeedLimit> {
  std_msgs.Header header;
  bool percentage;
  double speed_limit;

  static SpeedLimit $prototype = SpeedLimit();

  // Constructor
  SpeedLimit({std_msgs.Header? header, bool? percentage, double? speed_limit})
      : header = header ?? std_msgs.Header(),
        percentage = percentage ?? false,
        speed_limit = speed_limit ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/msg/SpeedLimit';

  @override
  String get messageDefinition => '''std_msgs/Header header
bool percentage
float64 speed_limit''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + 1 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'percentage': percentage,
        'speed_limit': speed_limit
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SpeedLimit fromJson(Map<String, dynamic> jsonMap) {
    return SpeedLimit(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        percentage: jsonMap['percentage'] as bool,
        speed_limit: jsonMap['speed_limit'] as double);
  }
}
