// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'GeoPoint.dart';

class GeoPose extends RosMessage<GeoPose> {
  late GeoPoint position;
  late geometry_msgs.Quaternion orientation;

  static GeoPose $prototype = GeoPose();

  // Constructor
  GeoPose({GeoPoint? position, geometry_msgs.Quaternion? orientation})
      : position = position ?? GeoPoint(),
        orientation = orientation ?? geometry_msgs.Quaternion();

  @override
  String get fullType => 'geographic_msgs/msg/GeoPose';

  @override
  String get messageDefinition => '''GeoPoint position
geometry_msgs/Quaternion orientation''';

  @override
  int getMessageSize() {
    return (position.getMessageSize()) + (orientation.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'position': position.toJson(), 'orientation': orientation.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPose fromJson(Map<String, dynamic> jsonMap) {
    return GeoPose(
        position:
            GeoPoint().fromJson(jsonMap['position'] as Map<String, dynamic>),
        orientation: geometry_msgs.Quaternion()
            .fromJson(jsonMap['orientation'] as Map<String, dynamic>));
  }
}
