// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'GeoPoint.dart';

class GeoPointStamped extends RosMessage<GeoPointStamped> {
  late std_msgs.Header header;
  late GeoPoint position;

  static GeoPointStamped $prototype = GeoPointStamped();

  // Constructor
  GeoPointStamped({std_msgs.Header? header, GeoPoint? position})
      : header = header ?? std_msgs.Header(),
        position = position ?? GeoPoint();

  @override
  String get fullType => 'geographic_msgs/msg/GeoPointStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
geographic_msgs/GeoPoint position''';

  @override
  int getMessageSize() {
    return (header.getMessageSize()) + (position.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'position': position.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPointStamped fromJson(Map<String, dynamic> jsonMap) {
    return GeoPointStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        position:
            GeoPoint().fromJson(jsonMap['position'] as Map<String, dynamic>));
  }
}
