// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GeoPoint extends RosMessage<GeoPoint> {
  late double latitude;
  late double longitude;
  late double altitude;

  static GeoPoint $prototype = GeoPoint();

  // Constructor
  GeoPoint({double? latitude, double? longitude, double? altitude})
      : latitude = latitude ?? 0.0,
        longitude = longitude ?? 0.0,
        altitude = altitude ?? 0.0;

  @override
  String get fullType => 'geographic_msgs/msg/GeoPoint';

  @override
  String get messageDefinition => '''float64 latitude
float64 longitude
float64 altitude''';

  @override
  int getMessageSize() {
    return 8 + 8 + 8;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'latitude': latitude, 'longitude': longitude, 'altitude': altitude};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GeoPoint fromJson(Map<String, dynamic> jsonMap) {
    return GeoPoint(
        latitude: jsonMap['latitude'] as double,
        longitude: jsonMap['longitude'] as double,
        altitude: jsonMap['altitude'] as double);
  }
}
