// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:unique_identifier_msgs/msg.dart' as unique_identifier_msgs;
import 'GeoPoint.dart';
import 'KeyValue.dart';

class WayPoint extends RosMessage<WayPoint> {
  late unique_identifier_msgs.UUID id;
  late GeoPoint position;
  late List<KeyValue> props;

  static WayPoint $prototype = WayPoint();

  // Constructor
  WayPoint(
      {unique_identifier_msgs.UUID? id,
      GeoPoint? position,
      List<KeyValue>? props})
      : id = id ?? unique_identifier_msgs.UUID(),
        position = position ?? GeoPoint(),
        props = props ?? const [];

  @override
  String get fullType => 'geographic_msgs/msg/WayPoint';

  @override
  String get messageDefinition => '''unique_identifier_msgs/UUID id
GeoPoint position
KeyValue[] props''';

  @override
  int getMessageSize() {
    return (id.getMessageSize()) +
        (position.getMessageSize()) +
        4 +
        props.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() => {
        'id': id.toJson(),
        'position': position.toJson(),
        'props': props.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WayPoint fromJson(Map<String, dynamic> jsonMap) {
    return WayPoint(
        id: unique_identifier_msgs
            .UUID()
            .fromJson(jsonMap['id'] as Map<String, dynamic>),
        position:
            GeoPoint().fromJson(jsonMap['position'] as Map<String, dynamic>),
        props: (jsonMap['props'] as List<dynamic>)
            .map((item) => KeyValue().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
