// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:builtin_interfaces/msg.dart';

class GoalID extends RosMessage<GoalID> {
  Time stamp;
  String id;

  static GoalID $prototype = GoalID();
  // Constructor
  GoalID({Time? stamp, String? id})
      : stamp = stamp ?? Time(),
        id = id ?? '';

  @override
  String get fullType => 'actionlib_msgs/msg/GoalID';

  @override
  String get messageDefinition => '''builtin_interfaces/Time stamp
string id''';

  @override
  int getMessageSize() {
    return (stamp.getMessageSize() + 4 + id.length).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'stamp': stamp.toJson(), 'id': id};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GoalID fromJson(Map<String, dynamic> jsonMap) {
    return GoalID(
        stamp: Time().fromJson(jsonMap['stamp'] as Map<String, dynamic>),
        id: jsonMap['id'] as String);
  }
}
