// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Accel.dart';

class AccelStamped extends RosMessage<AccelStamped> {
  std_msgs.Header header;
  Accel accel;

  static AccelStamped $prototype = AccelStamped();

  // Constructor
  AccelStamped({std_msgs.Header? header, Accel? accel})
      : header = header ?? std_msgs.Header(),
        accel = accel ?? Accel();

  @override
  String get fullType => 'geometry_msgs/msg/AccelStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Accel accel''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + accel.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'accel': accel.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AccelStamped fromJson(Map<String, dynamic> jsonMap) {
    return AccelStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        accel: Accel().fromJson(jsonMap['accel'] as Map<String, dynamic>));
  }
}
