// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'Accel.dart';

class AccelWithCovariance extends RosMessage<AccelWithCovariance> {
  Accel accel;
  List<double> covariance;

  static AccelWithCovariance $prototype = AccelWithCovariance();

  // Constructor
  AccelWithCovariance({Accel? accel, List<double>? covariance})
      : accel = accel ?? Accel(),
        covariance = covariance ?? const [];

  @override
  String get fullType => 'geometry_msgs/msg/AccelWithCovariance';

  @override
  String get messageDefinition => '''Accel accel
float64[36] covariance''';

  @override
  int getMessageSize() {
    return (accel.getMessageSize() + 4 + (covariance.length * 8)).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'accel': accel.toJson(), 'covariance': covariance};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AccelWithCovariance fromJson(Map<String, dynamic> jsonMap) {
    return AccelWithCovariance(
        accel: Accel().fromJson(jsonMap['accel'] as Map<String, dynamic>),
        covariance: (jsonMap['covariance'] as List).cast<double>());
  }
}
