// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'Vector3.dart';

class Inertia extends RosMessage<Inertia> {
  double m;
  Vector3 com;
  double ixx;
  double ixy;
  double ixz;
  double iyy;
  double iyz;
  double izz;

  static Inertia $prototype = Inertia();

  // Constructor
  Inertia(
      {double? m,
      Vector3? com,
      double? ixx,
      double? ixy,
      double? ixz,
      double? iyy,
      double? iyz,
      double? izz})
      : m = m ?? 0.0,
        com = com ?? Vector3(),
        ixx = ixx ?? 0.0,
        ixy = ixy ?? 0.0,
        ixz = ixz ?? 0.0,
        iyy = iyy ?? 0.0,
        iyz = iyz ?? 0.0,
        izz = izz ?? 0.0;

  @override
  String get fullType => 'geometry_msgs/msg/Inertia';

  @override
  String get messageDefinition => '''float64 m
geometry_msgs/Vector3 com
float64 ixx
float64 ixy
float64 ixz
float64 iyy
float64 iyz
float64 izz''';

  @override
  int getMessageSize() {
    return (8 + com.getMessageSize() + 8 + 8 + 8 + 8 + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'm': m,
        'com': com.toJson(),
        'ixx': ixx,
        'ixy': ixy,
        'ixz': ixz,
        'iyy': iyy,
        'iyz': iyz,
        'izz': izz
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Inertia fromJson(Map<String, dynamic> jsonMap) {
    return Inertia(
        m: jsonMap['m'] as double,
        com: Vector3().fromJson(jsonMap['com'] as Map<String, dynamic>),
        ixx: jsonMap['ixx'] as double,
        ixy: jsonMap['ixy'] as double,
        ixz: jsonMap['ixz'] as double,
        iyy: jsonMap['iyy'] as double,
        iyz: jsonMap['iyz'] as double,
        izz: jsonMap['izz'] as double);
  }
}
