// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Point.dart';

class PointStamped extends RosMessage<PointStamped> {
  std_msgs.Header header;
  Point point;

  static PointStamped $prototype = PointStamped();

  // Constructor
  PointStamped({std_msgs.Header? header, Point? point})
      : header = header ?? std_msgs.Header(),
        point = point ?? Point();

  @override
  String get fullType => 'geometry_msgs/msg/PointStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Point point''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + point.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'point': point.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PointStamped fromJson(Map<String, dynamic> jsonMap) {
    return PointStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        point: Point().fromJson(jsonMap['point'] as Map<String, dynamic>));
  }
}
