// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class Point32 extends RosMessage<Point32> {
  double x;
  double y;
  double z;

  static Point32 $prototype = Point32();

  // Constructor
  Point32({double? x, double? y, double? z})
      : x = x ?? 0.0,
        y = y ?? 0.0,
        z = z ?? 0.0;

  @override
  String get fullType => 'geometry_msgs/msg/Point32';

  @override
  String get messageDefinition => '''float32 x
float32 y
float32 z''';

  @override
  int getMessageSize() {
    return (4 + 4 + 4).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'x': x, 'y': y, 'z': z};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Point32 fromJson(Map<String, dynamic> jsonMap) {
    return Point32(
        x: jsonMap['x'] as double,
        y: jsonMap['y'] as double,
        z: jsonMap['z'] as double);
  }
}
