// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'Point32.dart';

class Polygon extends RosMessage<Polygon> {
  List<Point32> points;

  static Polygon $prototype = Polygon();

  // Constructor
  Polygon({List<Point32>? points}) : points = points ?? const [];

  @override
  String get fullType => 'geometry_msgs/msg/Polygon';

  @override
  String get messageDefinition => '''Point32[] points''';

  @override
  int getMessageSize() {
    return (4 + points.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'points': points.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Polygon fromJson(Map<String, dynamic> jsonMap) {
    return Polygon(
        points: (jsonMap['points'] as List)
            .map((item) => Point32().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
