// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Pose.dart';

class PoseArray extends RosMessage<PoseArray> {
  std_msgs.Header header;
  List<Pose> poses;

  static PoseArray $prototype = PoseArray();

  // Constructor
  PoseArray({std_msgs.Header? header, List<Pose>? poses})
      : header = header ?? std_msgs.Header(),
        poses = poses ?? const [];

  @override
  String get fullType => 'geometry_msgs/msg/PoseArray';

  @override
  String get messageDefinition => '''std_msgs/Header header
Pose[] poses''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            poses.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'poses': poses.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PoseArray fromJson(Map<String, dynamic> jsonMap) {
    return PoseArray(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        poses: (jsonMap['poses'] as List)
            .map((item) => Pose().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
