// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class Pose2D extends RosMessage<Pose2D> {
  double x;
  double y;
  double theta;

  static Pose2D $prototype = Pose2D();

  // Constructor
  Pose2D({double? x, double? y, double? theta})
      : x = x ?? 0.0,
        y = y ?? 0.0,
        theta = theta ?? 0.0;

  @override
  String get fullType => 'geometry_msgs/msg/Pose2D';

  @override
  String get messageDefinition => '''float64 x
float64 y
float64 theta''';

  @override
  int getMessageSize() {
    return (8 + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'x': x, 'y': y, 'theta': theta};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Pose2D fromJson(Map<String, dynamic> jsonMap) {
    return Pose2D(
        x: jsonMap['x'] as double,
        y: jsonMap['y'] as double,
        theta: jsonMap['theta'] as double);
  }
}
