// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Pose.dart';

class PoseStamped extends RosMessage<PoseStamped> {
  std_msgs.Header header;
  Pose pose;

  static PoseStamped $prototype = PoseStamped();

  // Constructor
  PoseStamped({std_msgs.Header? header, Pose? pose})
      : header = header ?? std_msgs.Header(),
        pose = pose ?? Pose();

  @override
  String get fullType => 'geometry_msgs/msg/PoseStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Pose pose''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + pose.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'pose': pose.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PoseStamped fromJson(Map<String, dynamic> jsonMap) {
    return PoseStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        pose: Pose().fromJson(jsonMap['pose'] as Map<String, dynamic>));
  }
}
