// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'Pose.dart';

class PoseWithCovariance extends RosMessage<PoseWithCovariance> {
  Pose pose;
  List<double> covariance;

  static PoseWithCovariance $prototype = PoseWithCovariance();

  // Constructor
  PoseWithCovariance({Pose? pose, List<double>? covariance})
      : pose = pose ?? Pose(),
        covariance = covariance ?? const [];

  @override
  String get fullType => 'geometry_msgs/msg/PoseWithCovariance';

  @override
  String get messageDefinition => '''Pose pose
float64[36] covariance''';

  @override
  int getMessageSize() {
    return (pose.getMessageSize() + 4 + (covariance.length * 8)).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'pose': pose.toJson(), 'covariance': covariance};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PoseWithCovariance fromJson(Map<String, dynamic> jsonMap) {
    return PoseWithCovariance(
        pose: Pose().fromJson(jsonMap['pose'] as Map<String, dynamic>),
        covariance: (jsonMap['covariance'] as List).cast<double>());
  }
}
