// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class Quaternion extends RosMessage<Quaternion> {
  double x;
  double y;
  double z;
  double w;

  static Quaternion $prototype = Quaternion();

  // Constructor
  Quaternion({double? x, double? y, double? z, double? w})
      : x = x ?? 0.0,
        y = y ?? 0.0,
        z = z ?? 0.0,
        w = w ?? 0.0;

  @override
  String get fullType => 'geometry_msgs/msg/Quaternion';

  @override
  String get messageDefinition => '''float64 x
float64 y
float64 z
float64 w''';

  @override
  int getMessageSize() {
    return (8 + 8 + 8 + 8).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'x': x, 'y': y, 'z': z, 'w': w};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Quaternion fromJson(Map<String, dynamic> jsonMap) {
    return Quaternion(
        x: jsonMap['x'] as double,
        y: jsonMap['y'] as double,
        z: jsonMap['z'] as double,
        w: jsonMap['w'] as double);
  }
}
