// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'TwistWithCovariance.dart';

class TwistWithCovarianceStamped
    extends RosMessage<TwistWithCovarianceStamped> {
  std_msgs.Header header;
  TwistWithCovariance twist;

  static TwistWithCovarianceStamped $prototype = TwistWithCovarianceStamped();

  // Constructor
  TwistWithCovarianceStamped(
      {std_msgs.Header? header, TwistWithCovariance? twist})
      : header = header ?? std_msgs.Header(),
        twist = twist ?? TwistWithCovariance();

  @override
  String get fullType => 'geometry_msgs/msg/TwistWithCovarianceStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
TwistWithCovariance twist''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + twist.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'twist': twist.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TwistWithCovarianceStamped fromJson(Map<String, dynamic> jsonMap) {
    return TwistWithCovarianceStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        twist: TwistWithCovariance()
            .fromJson(jsonMap['twist'] as Map<String, dynamic>));
  }
}
