// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Vector3.dart';

class Vector3Stamped extends RosMessage<Vector3Stamped> {
  std_msgs.Header header;
  Vector3 vector;

  static Vector3Stamped $prototype = Vector3Stamped();

  // Constructor
  Vector3Stamped({std_msgs.Header? header, Vector3? vector})
      : header = header ?? std_msgs.Header(),
        vector = vector ?? Vector3();

  @override
  String get fullType => 'geometry_msgs/msg/Vector3Stamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Vector3 vector''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + vector.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'vector': vector.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Vector3Stamped fromJson(Map<String, dynamic> jsonMap) {
    return Vector3Stamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        vector: Vector3().fromJson(jsonMap['vector'] as Map<String, dynamic>));
  }
}
