// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;

class SmsGoal extends RosMessage<SmsGoal> {
  late int number;
  late String message;
  late int sim_slot;

  static SmsGoal $prototype = SmsGoal();

  SmsGoal({int? number, String? message, int? sim_slot})
      : number = number ?? 0,
        message = message ?? '',
        sim_slot = sim_slot ?? 0;

  @override
  String get fullType => 'rio_interfaces/action/Sms_Goal';

  @override
  String get messageDefinition => '''int64 number
string message
uint8 sim_slot''';

  @override
  int getMessageSize() {
    return 8 + 4 + message.length + 1;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'number': number, 'message': message, 'sim_slot': sim_slot};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsGoal fromJson(Map<String, dynamic> jsonMap) {
    return SmsGoal(
        number: jsonMap['number'] as int,
        message: jsonMap['message'] as String,
        sim_slot: jsonMap['sim_slot'] as int);
  }
}

class SmsResult extends RosMessage<SmsResult> {
  late bool success;
  late String error_message;

  static SmsResult $prototype = SmsResult();

  SmsResult({bool? success, String? error_message})
      : success = success ?? false,
        error_message = error_message ?? '';

  @override
  String get fullType => 'rio_interfaces/action/Sms_Result';

  @override
  String get messageDefinition => '''bool success
string error_message''';

  @override
  int getMessageSize() {
    return 1 + 4 + error_message.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'success': success, 'error_message': error_message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsResult fromJson(Map<String, dynamic> jsonMap) {
    return SmsResult(
        success: jsonMap['success'] as bool,
        error_message: jsonMap['error_message'] as String);
  }
}

class SmsFeedback extends RosMessage<SmsFeedback> {
  static SmsFeedback $prototype = SmsFeedback();

  SmsFeedback();

  @override
  String get fullType => 'rio_interfaces/action/Sms_Feedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsFeedback fromJson(Map<String, dynamic> jsonMap) {
    return SmsFeedback();
  }
}

class SmsActionGoal extends RosActionGoal<SmsGoal, SmsActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late SmsGoal goal;

  static SmsActionGoal $prototype = SmsActionGoal();

  SmsActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    SmsGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? SmsGoal();

  @override
  String get fullType => 'rio_interfaces/action/Sms_ActionGoal';

  @override
  String get messageDefinition => '''int64 number
string message
uint8 sim_slot''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return SmsActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: SmsGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class SmsActionResult extends RosActionResult<SmsResult, SmsActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late SmsResult result;

  static SmsActionResult $prototype = SmsActionResult();

  SmsActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    SmsResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? SmsResult();

  @override
  String get fullType => 'rio_interfaces/action/Sms_ActionResult';

  @override
  String get messageDefinition => '''bool success
string error_message''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsActionResult fromJson(Map<String, dynamic> jsonMap) {
    return SmsActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: SmsResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class SmsActionFeedback
    extends RosActionFeedback<SmsFeedback, SmsActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late SmsFeedback feedback;

  static SmsActionFeedback $prototype = SmsActionFeedback();

  SmsActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    SmsFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? SmsFeedback();

  @override
  String get fullType => 'rio_interfaces/action/Sms_ActionFeedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SmsActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return SmsActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback:
          SmsFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class Sms extends RosActionMessage<SmsGoal, SmsActionGoal, SmsFeedback,
    SmsActionFeedback, SmsResult, SmsActionResult> {
  @override
  SmsActionGoal get actionGoal => SmsActionGoal();

  @override
  SmsActionFeedback get actionFeedback => SmsActionFeedback();

  @override
  SmsActionResult get actionResult => SmsActionResult();

  @override
  SmsGoal get goal => SmsGoal();

  @override
  SmsFeedback get feedback => SmsFeedback();

  @override
  SmsResult get result => SmsResult();

  @override
  String get fullType => 'rio_interfaces/action/Sms';

  @override
  String get messageDefinition => '''
Goal:
int64 number
string message
uint8 sim_slot
---
Result:
bool success
string error_message
---
Feedback:
''';
}
