// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:sensor_msgs/msg.dart' as sensor_msgs;

class GetPointMapRequest extends RosMessage<GetPointMapRequest> {
  static GetPointMapRequest $prototype = GetPointMapRequest();

  // Constructor
  GetPointMapRequest();

  @override
  String get fullType => 'map_msgs/srv/GetPointMap_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPointMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetPointMapRequest();
  }
}

class GetPointMapResponse extends RosMessage<GetPointMapResponse> {
  sensor_msgs.PointCloud2 map;

  static GetPointMapResponse $prototype = GetPointMapResponse();

  // Constructor
  GetPointMapResponse({sensor_msgs.PointCloud2? map})
      : map = map ?? sensor_msgs.PointCloud2();

  @override
  String get fullType => 'map_msgs/srv/GetPointMap_Response';

  @override
  String get messageDefinition => '''sensor_msgs/PointCloud2 map''';

  @override
  int getMessageSize() {
    return (map.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'map': map.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetPointMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetPointMapResponse(
        map: sensor_msgs.PointCloud2()
            .fromJson(jsonMap['map'] as Map<String, dynamic>));
  }
}

class GetPointMap
    extends RosServiceMessage<GetPointMapRequest, GetPointMapResponse> {
  @override
  GetPointMapRequest get request => GetPointMapRequest();

  @override
  GetPointMapResponse get response => GetPointMapResponse();

  @override
  String get fullType => 'map_msgs/srv/GetPointMap';

  @override
  String get messageDefinition => '''# Get the map as a sensor_msgs/PointCloud2
---
sensor_msgs/PointCloud2 map''';
}
