// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class SaveMapRequest extends RosMessage<SaveMapRequest> {
  std_msgs.StringMessage filename;

  static SaveMapRequest $prototype = SaveMapRequest();

  // Constructor
  SaveMapRequest({std_msgs.StringMessage? filename})
      : filename = filename ?? std_msgs.StringMessage();

  @override
  String get fullType => 'map_msgs/srv/SaveMap_Request';

  @override
  String get messageDefinition => '''std_msgs/String filename''';

  @override
  int getMessageSize() {
    return (filename.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'filename': filename.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SaveMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return SaveMapRequest(
        filename: std_msgs.StringMessage()
            .fromJson(jsonMap['filename'] as Map<String, dynamic>));
  }
}

class SaveMapResponse extends RosMessage<SaveMapResponse> {
  static SaveMapResponse $prototype = SaveMapResponse();

  // Constructor
  SaveMapResponse();

  @override
  String get fullType => 'map_msgs/srv/SaveMap_Response';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SaveMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return SaveMapResponse();
  }
}

class SaveMap extends RosServiceMessage<SaveMapRequest, SaveMapResponse> {
  @override
  SaveMapRequest get request => SaveMapRequest();

  @override
  SaveMapResponse get response => SaveMapResponse();

  @override
  String get fullType => 'map_msgs/srv/SaveMap';

  @override
  String get messageDefinition => '''# Save the map to the filesystem
std_msgs/String filename
---
''';
}
