// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class TF2Error extends RosMessage<TF2Error> {
  late int error;
  late String error_string;

  static TF2Error $prototype = TF2Error();

  // Constructor
  TF2Error({int? error, String? error_string})
      : error = error ?? 0,
        error_string = error_string ?? '';

  @override
  String get fullType => 'tf2_msgs/msg/TF2Error';

  @override
  String get messageDefinition => '''uint8 error
string error_string''';

  @override
  int getMessageSize() {
    return 1 + 4 + error_string.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'error': error, 'error_string': error_string};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TF2Error fromJson(Map<String, dynamic> jsonMap) {
    return TF2Error(
        error: jsonMap['error'] as int,
        error_string: jsonMap['error_string'] as String);
  }
}
