// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:std_msgs/msg.dart' as std_msgs;

class Odometry extends RosMessage<Odometry> {
  std_msgs.Header header;
  String child_frame_id;
  geometry_msgs.PoseWithCovariance pose;
  geometry_msgs.TwistWithCovariance twist;

  static Odometry $prototype = Odometry();

  // Constructor
  Odometry(
      {std_msgs.Header? header,
      String? child_frame_id,
      geometry_msgs.PoseWithCovariance? pose,
      geometry_msgs.TwistWithCovariance? twist})
      : header = header ?? std_msgs.Header(),
        child_frame_id = child_frame_id ?? '',
        pose = pose ?? geometry_msgs.PoseWithCovariance(),
        twist = twist ?? geometry_msgs.TwistWithCovariance();

  @override
  String get fullType => 'nav_msgs/msg/Odometry';

  @override
  String get messageDefinition => '''std_msgs/Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            child_frame_id.length +
            pose.getMessageSize() +
            twist.getMessageSize())
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'child_frame_id': child_frame_id,
        'pose': pose.toJson(),
        'twist': twist.toJson()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Odometry fromJson(Map<String, dynamic> jsonMap) {
    return Odometry(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        child_frame_id: jsonMap['child_frame_id'] as String,
        pose: geometry_msgs.PoseWithCovariance()
            .fromJson(jsonMap['pose'] as Map<String, dynamic>),
        twist: geometry_msgs.TwistWithCovariance()
            .fromJson(jsonMap['twist'] as Map<String, dynamic>));
  }
}
