// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:std_msgs/msg.dart' as std_msgs;

class Path extends RosMessage<Path> {
  std_msgs.Header header;
  List<geometry_msgs.PoseStamped> poses;

  static Path $prototype = Path();

  // Constructor
  Path({std_msgs.Header? header, List<geometry_msgs.PoseStamped>? poses})
      : header = header ?? std_msgs.Header(),
        poses = poses ?? const [];

  @override
  String get fullType => 'nav_msgs/msg/Path';

  @override
  String get messageDefinition => '''std_msgs/Header header
geometry_msgs/PoseStamped[] poses''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            poses.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'poses': poses.map((item) => item.toJson()).toList()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Path fromJson(Map<String, dynamic> jsonMap) {
    return Path(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        poses: (jsonMap['poses'] as List)
            .map((item) => geometry_msgs.PoseStamped()
                .fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
