// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'GoalStatus.dart';

class GoalStatusArray extends RosMessage<GoalStatusArray> {
  List<GoalStatus> status_list;

  static GoalStatusArray $prototype = GoalStatusArray();

  // Constructor
  GoalStatusArray({List<GoalStatus>? status_list})
      : status_list = status_list ?? const [];

  @override
  String get fullType => 'action_msgs/msg/GoalStatusArray';

  @override
  String get messageDefinition => '''GoalStatus[] status_list''';

  @override
  int getMessageSize() {
    return (4 + status_list.fold(0, (sum, item) => sum + item.getMessageSize()))
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'status_list': status_list.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GoalStatusArray fromJson(Map<String, dynamic> jsonMap) {
    return GoalStatusArray(
        status_list: (jsonMap['status_list'] as List)
            .map((item) => GoalStatus().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}
