// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/BoundingBox.dart';
import '../msg/GeographicMap.dart';

class GetGeographicMapRequest extends RosMessage<GetGeographicMapRequest> {
  late String url;
  late BoundingBox bounds;

  static GetGeographicMapRequest $prototype = GetGeographicMapRequest();

  GetGeographicMapRequest({String? url, BoundingBox? bounds})
      : url = url ?? '',
        bounds = bounds ?? BoundingBox();

  @override
  String get fullType => 'geographic_msgs/srv/GetGeographicMap_Request';

  @override
  String get messageDefinition => '''string url
BoundingBox bounds''';

  @override
  int getMessageSize() {
    return 4 + url.length + (bounds.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() => {'url': url, 'bounds': bounds.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetGeographicMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetGeographicMapRequest(
        url: jsonMap['url'] as String,
        bounds:
            BoundingBox().fromJson(jsonMap['bounds'] as Map<String, dynamic>));
  }
}

class GetGeographicMapResponse extends RosMessage<GetGeographicMapResponse> {
  late bool success;
  late String status;
  late GeographicMap map;

  static GetGeographicMapResponse $prototype = GetGeographicMapResponse();

  GetGeographicMapResponse({bool? success, String? status, GeographicMap? map})
      : success = success ?? false,
        status = status ?? '',
        map = map ?? GeographicMap();

  @override
  String get fullType => 'geographic_msgs/srv/GetGeographicMap_Response';

  @override
  String get messageDefinition => '''bool success
string status
GeographicMap map''';

  @override
  int getMessageSize() {
    return 1 + 4 + status.length + (map.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() =>
      {'success': success, 'status': status, 'map': map.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetGeographicMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetGeographicMapResponse(
        success: jsonMap['success'] as bool,
        status: jsonMap['status'] as String,
        map: GeographicMap().fromJson(jsonMap['map'] as Map<String, dynamic>));
  }
}

class GetGeographicMap extends RosServiceMessage<GetGeographicMapRequest,
    GetGeographicMapResponse> {
  @override
  GetGeographicMapRequest get request => GetGeographicMapRequest();

  @override
  GetGeographicMapResponse get response => GetGeographicMapResponse();

  @override
  String get fullType => 'geographic_msgs/srv/GetGeographicMap';

  @override
  String get messageDefinition => '''
string url
BoundingBox bounds
---
bool success
string status
GeographicMap map''';
}
