// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/GeographicMapChanges.dart';

class UpdateGeographicMapRequest
    extends RosMessage<UpdateGeographicMapRequest> {
  late GeographicMapChanges updates;

  static UpdateGeographicMapRequest $prototype = UpdateGeographicMapRequest();

  UpdateGeographicMapRequest({GeographicMapChanges? updates})
      : updates = updates ?? GeographicMapChanges();

  @override
  String get fullType => 'geographic_msgs/srv/UpdateGeographicMap_Request';

  @override
  String get messageDefinition => '''GeographicMapChanges updates''';

  @override
  int getMessageSize() {
    return (updates.getMessageSize());
  }

  @override
  Map<String, dynamic> toJson() => {'updates': updates.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UpdateGeographicMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return UpdateGeographicMapRequest(
        updates: GeographicMapChanges()
            .fromJson(jsonMap['updates'] as Map<String, dynamic>));
  }
}

class UpdateGeographicMapResponse
    extends RosMessage<UpdateGeographicMapResponse> {
  late bool success;
  late String status;

  static UpdateGeographicMapResponse $prototype = UpdateGeographicMapResponse();

  UpdateGeographicMapResponse({bool? success, String? status})
      : success = success ?? false,
        status = status ?? '';

  @override
  String get fullType => 'geographic_msgs/srv/UpdateGeographicMap_Response';

  @override
  String get messageDefinition => '''bool success
string status''';

  @override
  int getMessageSize() {
    return 1 + 4 + status.length;
  }

  @override
  Map<String, dynamic> toJson() => {'success': success, 'status': status};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UpdateGeographicMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return UpdateGeographicMapResponse(
        success: jsonMap['success'] as bool,
        status: jsonMap['status'] as String);
  }
}

class UpdateGeographicMap extends RosServiceMessage<UpdateGeographicMapRequest,
    UpdateGeographicMapResponse> {
  @override
  UpdateGeographicMapRequest get request => UpdateGeographicMapRequest();

  @override
  UpdateGeographicMapResponse get response => UpdateGeographicMapResponse();

  @override
  String get fullType => 'geographic_msgs/srv/UpdateGeographicMap';

  @override
  String get messageDefinition => '''
GeographicMapChanges updates
---
bool success
string status''';
}
