// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class ClearCostmapAroundRobotRequest
    extends RosMessage<ClearCostmapAroundRobotRequest> {
  double reset_distance;

  static ClearCostmapAroundRobotRequest $prototype =
      ClearCostmapAroundRobotRequest();

  // Constructor
  ClearCostmapAroundRobotRequest({double? reset_distance})
      : reset_distance = reset_distance ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapAroundRobot_Request';

  @override
  String get messageDefinition => '''float32 reset_distance''';

  @override
  int getMessageSize() {
    return (4).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'reset_distance': reset_distance};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearCostmapAroundRobotRequest fromJson(Map<String, dynamic> jsonMap) {
    return ClearCostmapAroundRobotRequest(
        reset_distance: jsonMap['reset_distance'] as double);
  }
}

class ClearCostmapAroundRobotResponse
    extends RosMessage<ClearCostmapAroundRobotResponse> {
  std_msgs.Empty response;

  static ClearCostmapAroundRobotResponse $prototype =
      ClearCostmapAroundRobotResponse();

  // Constructor
  ClearCostmapAroundRobotResponse({std_msgs.Empty? response})
      : response = response ?? std_msgs.Empty();

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapAroundRobot_Response';

  @override
  String get messageDefinition => '''std_msgs/Empty response''';

  @override
  int getMessageSize() {
    return (response.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'response': response.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearCostmapAroundRobotResponse fromJson(Map<String, dynamic> jsonMap) {
    return ClearCostmapAroundRobotResponse(
        response: std_msgs.Empty()
            .fromJson(jsonMap['response'] as Map<String, dynamic>));
  }
}

class ClearCostmapAroundRobot extends RosServiceMessage<
    ClearCostmapAroundRobotRequest, ClearCostmapAroundRobotResponse> {
  @override
  ClearCostmapAroundRobotRequest get request =>
      ClearCostmapAroundRobotRequest();

  @override
  ClearCostmapAroundRobotResponse get response =>
      ClearCostmapAroundRobotResponse();

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapAroundRobot';

  @override
  String get messageDefinition => '''# Clears the costmap within a distance

float32 reset_distance
---
std_msgs/Empty response''';
}
