// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class ClearCostmapExceptRegionRequest
    extends RosMessage<ClearCostmapExceptRegionRequest> {
  double reset_distance;

  static ClearCostmapExceptRegionRequest $prototype =
      ClearCostmapExceptRegionRequest();

  // Constructor
  ClearCostmapExceptRegionRequest({double? reset_distance})
      : reset_distance = reset_distance ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapExceptRegion_Request';

  @override
  String get messageDefinition => '''float32 reset_distance''';

  @override
  int getMessageSize() {
    return (4).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'reset_distance': reset_distance};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearCostmapExceptRegionRequest fromJson(Map<String, dynamic> jsonMap) {
    return ClearCostmapExceptRegionRequest(
        reset_distance: jsonMap['reset_distance'] as double);
  }
}

class ClearCostmapExceptRegionResponse
    extends RosMessage<ClearCostmapExceptRegionResponse> {
  std_msgs.Empty response;

  static ClearCostmapExceptRegionResponse $prototype =
      ClearCostmapExceptRegionResponse();

  // Constructor
  ClearCostmapExceptRegionResponse({std_msgs.Empty? response})
      : response = response ?? std_msgs.Empty();

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapExceptRegion_Response';

  @override
  String get messageDefinition => '''std_msgs/Empty response''';

  @override
  int getMessageSize() {
    return (response.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'response': response.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearCostmapExceptRegionResponse fromJson(Map<String, dynamic> jsonMap) {
    return ClearCostmapExceptRegionResponse(
        response: std_msgs.Empty()
            .fromJson(jsonMap['response'] as Map<String, dynamic>));
  }
}

class ClearCostmapExceptRegion extends RosServiceMessage<
    ClearCostmapExceptRegionRequest, ClearCostmapExceptRegionResponse> {
  @override
  ClearCostmapExceptRegionRequest get request =>
      ClearCostmapExceptRegionRequest();

  @override
  ClearCostmapExceptRegionResponse get response =>
      ClearCostmapExceptRegionResponse();

  @override
  String get fullType => 'nav2_msgs/srv/ClearCostmapExceptRegion';

  @override
  String get messageDefinition =>
      '''# Clears the costmap except a rectangular region specified by reset_distance

float32 reset_distance
---
std_msgs/Empty response''';
}
