// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;

class ClearEntireCostmapRequest extends RosMessage<ClearEntireCostmapRequest> {
  std_msgs.Empty request;

  static ClearEntireCostmapRequest $prototype = ClearEntireCostmapRequest();

  // Constructor
  ClearEntireCostmapRequest({std_msgs.Empty? request})
      : request = request ?? std_msgs.Empty();

  @override
  String get fullType => 'nav2_msgs/srv/ClearEntireCostmap_Request';

  @override
  String get messageDefinition => '''std_msgs/Empty request''';

  @override
  int getMessageSize() {
    return (request.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'request': request.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearEntireCostmapRequest fromJson(Map<String, dynamic> jsonMap) {
    return ClearEntireCostmapRequest(
        request: std_msgs.Empty()
            .fromJson(jsonMap['request'] as Map<String, dynamic>));
  }
}

class ClearEntireCostmapResponse
    extends RosMessage<ClearEntireCostmapResponse> {
  std_msgs.Empty response;

  static ClearEntireCostmapResponse $prototype = ClearEntireCostmapResponse();

  // Constructor
  ClearEntireCostmapResponse({std_msgs.Empty? response})
      : response = response ?? std_msgs.Empty();

  @override
  String get fullType => 'nav2_msgs/srv/ClearEntireCostmap_Response';

  @override
  String get messageDefinition => '''std_msgs/Empty response''';

  @override
  int getMessageSize() {
    return (response.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'response': response.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ClearEntireCostmapResponse fromJson(Map<String, dynamic> jsonMap) {
    return ClearEntireCostmapResponse(
        response: std_msgs.Empty()
            .fromJson(jsonMap['response'] as Map<String, dynamic>));
  }
}

class ClearEntireCostmap extends RosServiceMessage<ClearEntireCostmapRequest,
    ClearEntireCostmapResponse> {
  @override
  ClearEntireCostmapRequest get request => ClearEntireCostmapRequest();

  @override
  ClearEntireCostmapResponse get response => ClearEntireCostmapResponse();

  @override
  String get fullType => 'nav2_msgs/srv/ClearEntireCostmap';

  @override
  String get messageDefinition => '''# Clears all layers on the costmap

std_msgs/Empty request
---
std_msgs/Empty response''';
}
