// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/CostmapMetaData.dart';
import '../msg/Costmap.dart';

class GetCostmapRequest extends RosMessage<GetCostmapRequest> {
  CostmapMetaData specs;

  static GetCostmapRequest $prototype = GetCostmapRequest();

  // Constructor
  GetCostmapRequest({CostmapMetaData? specs})
      : specs = specs ?? CostmapMetaData();

  @override
  String get fullType => 'nav2_msgs/srv/GetCostmap_Request';

  @override
  String get messageDefinition => '''nav2_msgs/CostmapMetaData specs''';

  @override
  int getMessageSize() {
    return (specs.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'specs': specs.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetCostmapRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetCostmapRequest(
        specs: CostmapMetaData()
            .fromJson(jsonMap['specs'] as Map<String, dynamic>));
  }
}

class GetCostmapResponse extends RosMessage<GetCostmapResponse> {
  Costmap map;

  static GetCostmapResponse $prototype = GetCostmapResponse();

  // Constructor
  GetCostmapResponse({Costmap? map}) : map = map ?? Costmap();

  @override
  String get fullType => 'nav2_msgs/srv/GetCostmap_Response';

  @override
  String get messageDefinition => '''nav2_msgs/Costmap map''';

  @override
  int getMessageSize() {
    return (map.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'map': map.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetCostmapResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetCostmapResponse(
        map: Costmap().fromJson(jsonMap['map'] as Map<String, dynamic>));
  }
}

class GetCostmap
    extends RosServiceMessage<GetCostmapRequest, GetCostmapResponse> {
  @override
  GetCostmapRequest get request => GetCostmapRequest();

  @override
  GetCostmapResponse get response => GetCostmapResponse();

  @override
  String get fullType => 'nav2_msgs/srv/GetCostmap';

  @override
  String get messageDefinition => '''# Get the costmap

# Specifications for the requested costmap
nav2_msgs/CostmapMetaData specs
---
nav2_msgs/Costmap map''';
}
