// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class SaveMapRequest extends RosMessage<SaveMapRequest> {
  String map_topic;
  String map_url;
  String image_format;
  String map_mode;
  double free_thresh;
  double occupied_thresh;

  static SaveMapRequest $prototype = SaveMapRequest();

  // Constructor
  SaveMapRequest(
      {String? map_topic,
      String? map_url,
      String? image_format,
      String? map_mode,
      double? free_thresh,
      double? occupied_thresh})
      : map_topic = map_topic ?? '',
        map_url = map_url ?? '',
        image_format = image_format ?? '',
        map_mode = map_mode ?? '',
        free_thresh = free_thresh ?? 0.0,
        occupied_thresh = occupied_thresh ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/srv/SaveMap_Request';

  @override
  String get messageDefinition => '''string map_topic
string map_url
string image_format
string map_mode
float32 free_thresh
float32 occupied_thresh''';

  @override
  int getMessageSize() {
    return (4 +
            map_topic.length +
            4 +
            map_url.length +
            4 +
            image_format.length +
            4 +
            map_mode.length +
            4 +
            4)
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'map_topic': map_topic,
        'map_url': map_url,
        'image_format': image_format,
        'map_mode': map_mode,
        'free_thresh': free_thresh,
        'occupied_thresh': occupied_thresh
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SaveMapRequest fromJson(Map<String, dynamic> jsonMap) {
    return SaveMapRequest(
        map_topic: jsonMap['map_topic'] as String,
        map_url: jsonMap['map_url'] as String,
        image_format: jsonMap['image_format'] as String,
        map_mode: jsonMap['map_mode'] as String,
        free_thresh: jsonMap['free_thresh'] as double,
        occupied_thresh: jsonMap['occupied_thresh'] as double);
  }
}

class SaveMapResponse extends RosMessage<SaveMapResponse> {
  bool result;

  static SaveMapResponse $prototype = SaveMapResponse();

  // Constructor
  SaveMapResponse({bool? result}) : result = result ?? false;

  @override
  String get fullType => 'nav2_msgs/srv/SaveMap_Response';

  @override
  String get messageDefinition => '''bool result''';

  @override
  int getMessageSize() {
    return (1).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'result': result};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SaveMapResponse fromJson(Map<String, dynamic> jsonMap) {
    return SaveMapResponse(result: jsonMap['result'] as bool);
  }
}

class SaveMap extends RosServiceMessage<SaveMapRequest, SaveMapResponse> {
  @override
  SaveMapRequest get request => SaveMapRequest();

  @override
  SaveMapResponse get response => SaveMapResponse();

  @override
  String get fullType => 'nav2_msgs/srv/SaveMap';

  @override
  String get messageDefinition => '''# URL of map resource
# Can be an absolute path to a file: file:///path/to/maps/floor1.yaml
# Or, relative to a ROS package: package://my_ros_package/maps/floor2.yaml
string map_topic
string map_url
# Constants for image_format. Supported formats: pgm, png, bmp
string image_format
# Map modes: trinary, scale or raw
string map_mode
# Thresholds. Values in range of [0.0 .. 1.0]
float32 free_thresh
float32 occupied_thresh
---
bool result''';
}
