// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;
import 'package:nav_msgs/msg.dart' as nav_msgs;

class ComputePathToPoseGoal extends RosMessage<ComputePathToPoseGoal> {
  late geometry_msgs.PoseStamped goal;
  late geometry_msgs.PoseStamped start;
  late String planner_id;
  late bool use_start;

  static ComputePathToPoseGoal $prototype = ComputePathToPoseGoal();

  ComputePathToPoseGoal(
      {geometry_msgs.PoseStamped? goal,
      geometry_msgs.PoseStamped? start,
      String? planner_id,
      bool? use_start})
      : goal = goal ?? geometry_msgs.PoseStamped(),
        start = start ?? geometry_msgs.PoseStamped(),
        planner_id = planner_id ?? '',
        use_start = use_start ?? false;

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_Goal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped goal
geometry_msgs/PoseStamped start
string planner_id
bool use_start''';

  @override
  int getMessageSize() {
    return (goal.getMessageSize()) +
        (start.getMessageSize()) +
        4 +
        planner_id.length +
        1;
  }

  @override
  Map<String, dynamic> toJson() => {
        'goal': goal.toJson(),
        'start': start.toJson(),
        'planner_id': planner_id,
        'use_start': use_start
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseGoal fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseGoal(
        goal: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['goal'] as Map<String, dynamic>),
        start: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['start'] as Map<String, dynamic>),
        planner_id: jsonMap['planner_id'] as String,
        use_start: jsonMap['use_start'] as bool);
  }
}

class ComputePathToPoseResult extends RosMessage<ComputePathToPoseResult> {
  late nav_msgs.Path path;
  late builtin_interfaces.Duration planning_time;
  late int error_code;

  static ComputePathToPoseResult $prototype = ComputePathToPoseResult();

  ComputePathToPoseResult(
      {nav_msgs.Path? path,
      builtin_interfaces.Duration? planning_time,
      int? error_code})
      : path = path ?? nav_msgs.Path(),
        planning_time = planning_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_Result';

  @override
  String get messageDefinition => '''nav_msgs/Path path
builtin_interfaces/Duration planning_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (path.getMessageSize()) + (planning_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'path': path.toJson(),
        'planning_time': planning_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseResult fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseResult(
        path: nav_msgs.Path().fromJson(jsonMap['path'] as Map<String, dynamic>),
        planning_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['planning_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class ComputePathToPoseFeedback extends RosMessage<ComputePathToPoseFeedback> {
  static ComputePathToPoseFeedback $prototype = ComputePathToPoseFeedback();

  ComputePathToPoseFeedback();

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_Feedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseFeedback fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseFeedback();
  }
}

class ComputePathToPoseActionGoal
    extends RosActionGoal<ComputePathToPoseGoal, ComputePathToPoseActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late ComputePathToPoseGoal goal;

  static ComputePathToPoseActionGoal $prototype = ComputePathToPoseActionGoal();

  ComputePathToPoseActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    ComputePathToPoseGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? ComputePathToPoseGoal();

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_ActionGoal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped goal
geometry_msgs/PoseStamped start
string planner_id
bool use_start''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: ComputePathToPoseGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class ComputePathToPoseActionResult extends RosActionResult<
    ComputePathToPoseResult, ComputePathToPoseActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late ComputePathToPoseResult result;

  static ComputePathToPoseActionResult $prototype =
      ComputePathToPoseActionResult();

  ComputePathToPoseActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    ComputePathToPoseResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? ComputePathToPoseResult();

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_ActionResult';

  @override
  String get messageDefinition => '''nav_msgs/Path path
builtin_interfaces/Duration planning_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseActionResult fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: ComputePathToPoseResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class ComputePathToPoseActionFeedback extends RosActionFeedback<
    ComputePathToPoseFeedback, ComputePathToPoseActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late ComputePathToPoseFeedback feedback;

  static ComputePathToPoseActionFeedback $prototype =
      ComputePathToPoseActionFeedback();

  ComputePathToPoseActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    ComputePathToPoseFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? ComputePathToPoseFeedback();

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose_ActionFeedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ComputePathToPoseActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return ComputePathToPoseActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: ComputePathToPoseFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class ComputePathToPose extends RosActionMessage<
    ComputePathToPoseGoal,
    ComputePathToPoseActionGoal,
    ComputePathToPoseFeedback,
    ComputePathToPoseActionFeedback,
    ComputePathToPoseResult,
    ComputePathToPoseActionResult> {
  @override
  ComputePathToPoseActionGoal get actionGoal => ComputePathToPoseActionGoal();

  @override
  ComputePathToPoseActionFeedback get actionFeedback =>
      ComputePathToPoseActionFeedback();

  @override
  ComputePathToPoseActionResult get actionResult =>
      ComputePathToPoseActionResult();

  @override
  ComputePathToPoseGoal get goal => ComputePathToPoseGoal();

  @override
  ComputePathToPoseFeedback get feedback => ComputePathToPoseFeedback();

  @override
  ComputePathToPoseResult get result => ComputePathToPoseResult();

  @override
  String get fullType => 'nav2_msgs/action/ComputePathToPose';

  @override
  String get messageDefinition => '''
Goal:
geometry_msgs/PoseStamped goal
geometry_msgs/PoseStamped start
string planner_id
bool use_start
---
Result:
nav_msgs/Path path
builtin_interfaces/Duration planning_time
uint16 error_code
---
Feedback:
''';
}
