// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:nav_msgs/msg.dart' as nav_msgs;

class FollowPathGoal extends RosMessage<FollowPathGoal> {
  late nav_msgs.Path path;
  late String controller_id;
  late String goal_checker_id;
  late String progress_checker_id;

  static FollowPathGoal $prototype = FollowPathGoal();

  FollowPathGoal(
      {nav_msgs.Path? path,
      String? controller_id,
      String? goal_checker_id,
      String? progress_checker_id})
      : path = path ?? nav_msgs.Path(),
        controller_id = controller_id ?? '',
        goal_checker_id = goal_checker_id ?? '',
        progress_checker_id = progress_checker_id ?? '';

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_Goal';

  @override
  String get messageDefinition => '''nav_msgs/Path path
string controller_id
string goal_checker_id
string progress_checker_id''';

  @override
  int getMessageSize() {
    return (path.getMessageSize()) +
        4 +
        controller_id.length +
        4 +
        goal_checker_id.length +
        4 +
        progress_checker_id.length;
  }

  @override
  Map<String, dynamic> toJson() => {
        'path': path.toJson(),
        'controller_id': controller_id,
        'goal_checker_id': goal_checker_id,
        'progress_checker_id': progress_checker_id
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathGoal fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathGoal(
        path: nav_msgs.Path().fromJson(jsonMap['path'] as Map<String, dynamic>),
        controller_id: jsonMap['controller_id'] as String,
        goal_checker_id: jsonMap['goal_checker_id'] as String,
        progress_checker_id: jsonMap['progress_checker_id'] as String);
  }
}

class FollowPathResult extends RosMessage<FollowPathResult> {
  late std_msgs.Empty result;
  late int error_code;

  static FollowPathResult $prototype = FollowPathResult();

  FollowPathResult({std_msgs.Empty? result, int? error_code})
      : result = result ?? std_msgs.Empty(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_Result';

  @override
  String get messageDefinition => '''std_msgs/Empty result
uint16 error_code''';

  @override
  int getMessageSize() {
    return (result.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'result': result.toJson(), 'error_code': error_code};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathResult fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathResult(
        result: std_msgs.Empty()
            .fromJson(jsonMap['result'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class FollowPathFeedback extends RosMessage<FollowPathFeedback> {
  late double distance_to_goal;
  late double speed;

  static FollowPathFeedback $prototype = FollowPathFeedback();

  FollowPathFeedback({double? distance_to_goal, double? speed})
      : distance_to_goal = distance_to_goal ?? 0.0,
        speed = speed ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_Feedback';

  @override
  String get messageDefinition => '''float32 distance_to_goal
float32 speed''';

  @override
  int getMessageSize() {
    return 4 + 4;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'distance_to_goal': distance_to_goal, 'speed': speed};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathFeedback fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathFeedback(
        distance_to_goal: jsonMap['distance_to_goal'] as double,
        speed: jsonMap['speed'] as double);
  }
}

class FollowPathActionGoal
    extends RosActionGoal<FollowPathGoal, FollowPathActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late FollowPathGoal goal;

  static FollowPathActionGoal $prototype = FollowPathActionGoal();

  FollowPathActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    FollowPathGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? FollowPathGoal();

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_ActionGoal';

  @override
  String get messageDefinition => '''nav_msgs/Path path
string controller_id
string goal_checker_id
string progress_checker_id''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: FollowPathGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class FollowPathActionResult
    extends RosActionResult<FollowPathResult, FollowPathActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late FollowPathResult result;

  static FollowPathActionResult $prototype = FollowPathActionResult();

  FollowPathActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    FollowPathResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? FollowPathResult();

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_ActionResult';

  @override
  String get messageDefinition => '''std_msgs/Empty result
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathActionResult fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: FollowPathResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class FollowPathActionFeedback
    extends RosActionFeedback<FollowPathFeedback, FollowPathActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late FollowPathFeedback feedback;

  static FollowPathActionFeedback $prototype = FollowPathActionFeedback();

  FollowPathActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    FollowPathFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? FollowPathFeedback();

  @override
  String get fullType => 'nav2_msgs/action/FollowPath_ActionFeedback';

  @override
  String get messageDefinition => '''float32 distance_to_goal
float32 speed''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  FollowPathActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return FollowPathActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: FollowPathFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class FollowPath extends RosActionMessage<
    FollowPathGoal,
    FollowPathActionGoal,
    FollowPathFeedback,
    FollowPathActionFeedback,
    FollowPathResult,
    FollowPathActionResult> {
  @override
  FollowPathActionGoal get actionGoal => FollowPathActionGoal();

  @override
  FollowPathActionFeedback get actionFeedback => FollowPathActionFeedback();

  @override
  FollowPathActionResult get actionResult => FollowPathActionResult();

  @override
  FollowPathGoal get goal => FollowPathGoal();

  @override
  FollowPathFeedback get feedback => FollowPathFeedback();

  @override
  FollowPathResult get result => FollowPathResult();

  @override
  String get fullType => 'nav2_msgs/action/FollowPath';

  @override
  String get messageDefinition => '''
Goal:
nav_msgs/Path path
string controller_id
string goal_checker_id
string progress_checker_id
---
Result:
std_msgs/Empty result
uint16 error_code
---
Feedback:
float32 distance_to_goal
float32 speed''';
}
