// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class NavigateThroughPosesGoal extends RosMessage<NavigateThroughPosesGoal> {
  late List<geometry_msgs.PoseStamped> poses;
  late String behavior_tree;

  static NavigateThroughPosesGoal $prototype = NavigateThroughPosesGoal();

  NavigateThroughPosesGoal(
      {List<geometry_msgs.PoseStamped>? poses, String? behavior_tree})
      : poses = poses ?? const [],
        behavior_tree = behavior_tree ?? '';

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_Goal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped[] poses
string behavior_tree''';

  @override
  int getMessageSize() {
    return 4 +
        poses.fold<int>(0, (sum, item) => sum + (item.getMessageSize())) +
        4 +
        behavior_tree.length;
  }

  @override
  Map<String, dynamic> toJson() => {
        'poses': poses.map((item) => item.toJson()).toList(),
        'behavior_tree': behavior_tree
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesGoal(
        poses: (jsonMap['poses'] as List<dynamic>)
            .map((item) => geometry_msgs.PoseStamped()
                .fromJson(item as Map<String, dynamic>))
            .toList(),
        behavior_tree: jsonMap['behavior_tree'] as String);
  }
}

class NavigateThroughPosesResult
    extends RosMessage<NavigateThroughPosesResult> {
  late int error_code;

  static NavigateThroughPosesResult $prototype = NavigateThroughPosesResult();

  NavigateThroughPosesResult({int? error_code}) : error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_Result';

  @override
  String get messageDefinition => '''uint16 error_code''';

  @override
  int getMessageSize() {
    return 2;
  }

  @override
  Map<String, dynamic> toJson() => {'error_code': error_code};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesResult fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesResult(error_code: jsonMap['error_code'] as int);
  }
}

class NavigateThroughPosesFeedback
    extends RosMessage<NavigateThroughPosesFeedback> {
  late geometry_msgs.PoseStamped current_pose;
  late builtin_interfaces.Duration navigation_time;
  late builtin_interfaces.Duration estimated_time_remaining;
  late int number_of_recoveries;
  late double distance_remaining;
  late int number_of_poses_remaining;

  static NavigateThroughPosesFeedback $prototype =
      NavigateThroughPosesFeedback();

  NavigateThroughPosesFeedback(
      {geometry_msgs.PoseStamped? current_pose,
      builtin_interfaces.Duration? navigation_time,
      builtin_interfaces.Duration? estimated_time_remaining,
      int? number_of_recoveries,
      double? distance_remaining,
      int? number_of_poses_remaining})
      : current_pose = current_pose ?? geometry_msgs.PoseStamped(),
        navigation_time = navigation_time ?? builtin_interfaces.Duration(),
        estimated_time_remaining =
            estimated_time_remaining ?? builtin_interfaces.Duration(),
        number_of_recoveries = number_of_recoveries ?? 0,
        distance_remaining = distance_remaining ?? 0.0,
        number_of_poses_remaining = number_of_poses_remaining ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_Feedback';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
int16 number_of_poses_remaining''';

  @override
  int getMessageSize() {
    return (current_pose.getMessageSize()) +
        (navigation_time.getMessageSize()) +
        (estimated_time_remaining.getMessageSize()) +
        2 +
        4 +
        2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'current_pose': current_pose.toJson(),
        'navigation_time': navigation_time.toJson(),
        'estimated_time_remaining': estimated_time_remaining.toJson(),
        'number_of_recoveries': number_of_recoveries,
        'distance_remaining': distance_remaining,
        'number_of_poses_remaining': number_of_poses_remaining
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesFeedback(
        current_pose: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['current_pose'] as Map<String, dynamic>),
        navigation_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['navigation_time'] as Map<String, dynamic>),
        estimated_time_remaining: builtin_interfaces.Duration().fromJson(
            jsonMap['estimated_time_remaining'] as Map<String, dynamic>),
        number_of_recoveries: jsonMap['number_of_recoveries'] as int,
        distance_remaining: jsonMap['distance_remaining'] as double,
        number_of_poses_remaining: jsonMap['number_of_poses_remaining'] as int);
  }
}

class NavigateThroughPosesActionGoal extends RosActionGoal<
    NavigateThroughPosesGoal, NavigateThroughPosesActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late NavigateThroughPosesGoal goal;

  static NavigateThroughPosesActionGoal $prototype =
      NavigateThroughPosesActionGoal();

  NavigateThroughPosesActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    NavigateThroughPosesGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? NavigateThroughPosesGoal();

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_ActionGoal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped[] poses
string behavior_tree''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: NavigateThroughPosesGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class NavigateThroughPosesActionResult extends RosActionResult<
    NavigateThroughPosesResult, NavigateThroughPosesActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late NavigateThroughPosesResult result;

  static NavigateThroughPosesActionResult $prototype =
      NavigateThroughPosesActionResult();

  NavigateThroughPosesActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavigateThroughPosesResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? NavigateThroughPosesResult();

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_ActionResult';

  @override
  String get messageDefinition => '''uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesActionResult fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: NavigateThroughPosesResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class NavigateThroughPosesActionFeedback extends RosActionFeedback<
    NavigateThroughPosesFeedback, NavigateThroughPosesActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late NavigateThroughPosesFeedback feedback;

  static NavigateThroughPosesActionFeedback $prototype =
      NavigateThroughPosesActionFeedback();

  NavigateThroughPosesActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavigateThroughPosesFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? NavigateThroughPosesFeedback();

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses_ActionFeedback';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
int16 number_of_poses_remaining''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateThroughPosesActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavigateThroughPosesActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: NavigateThroughPosesFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class NavigateThroughPoses extends RosActionMessage<
    NavigateThroughPosesGoal,
    NavigateThroughPosesActionGoal,
    NavigateThroughPosesFeedback,
    NavigateThroughPosesActionFeedback,
    NavigateThroughPosesResult,
    NavigateThroughPosesActionResult> {
  @override
  NavigateThroughPosesActionGoal get actionGoal =>
      NavigateThroughPosesActionGoal();

  @override
  NavigateThroughPosesActionFeedback get actionFeedback =>
      NavigateThroughPosesActionFeedback();

  @override
  NavigateThroughPosesActionResult get actionResult =>
      NavigateThroughPosesActionResult();

  @override
  NavigateThroughPosesGoal get goal => NavigateThroughPosesGoal();

  @override
  NavigateThroughPosesFeedback get feedback => NavigateThroughPosesFeedback();

  @override
  NavigateThroughPosesResult get result => NavigateThroughPosesResult();

  @override
  String get fullType => 'nav2_msgs/action/NavigateThroughPoses';

  @override
  String get messageDefinition => '''
Goal:
geometry_msgs/PoseStamped[] poses
string behavior_tree
---
Result:
uint16 error_code
---
Feedback:
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
int16 number_of_poses_remaining''';
}
