// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;

class WaitGoal extends RosMessage<WaitGoal> {
  late builtin_interfaces.Duration time;

  static WaitGoal $prototype = WaitGoal();

  WaitGoal({builtin_interfaces.Duration? time})
      : time = time ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/Wait_Goal';

  @override
  String get messageDefinition => '''builtin_interfaces/Duration time''';

  @override
  int getMessageSize() {
    return time.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {'time': time.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitGoal fromJson(Map<String, dynamic> jsonMap) {
    return WaitGoal(
        time: builtin_interfaces.Duration()
            .fromJson(jsonMap['time'] as Map<String, dynamic>));
  }
}

class WaitResult extends RosMessage<WaitResult> {
  late builtin_interfaces.Duration total_elapsed_time;
  late int error_code;

  static WaitResult $prototype = WaitResult();

  WaitResult({builtin_interfaces.Duration? total_elapsed_time, int? error_code})
      : total_elapsed_time =
            total_elapsed_time ?? builtin_interfaces.Duration(),
        error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/Wait_Result';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return (total_elapsed_time.getMessageSize()) + 2;
  }

  @override
  Map<String, dynamic> toJson() => {
        'total_elapsed_time': total_elapsed_time.toJson(),
        'error_code': error_code
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitResult fromJson(Map<String, dynamic> jsonMap) {
    return WaitResult(
        total_elapsed_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['total_elapsed_time'] as Map<String, dynamic>),
        error_code: jsonMap['error_code'] as int);
  }
}

class WaitFeedback extends RosMessage<WaitFeedback> {
  late builtin_interfaces.Duration time_left;

  static WaitFeedback $prototype = WaitFeedback();

  WaitFeedback({builtin_interfaces.Duration? time_left})
      : time_left = time_left ?? builtin_interfaces.Duration();

  @override
  String get fullType => 'nav2_msgs/action/Wait_Feedback';

  @override
  String get messageDefinition => '''builtin_interfaces/Duration time_left''';

  @override
  int getMessageSize() {
    return time_left.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {'time_left': time_left.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitFeedback fromJson(Map<String, dynamic> jsonMap) {
    return WaitFeedback(
        time_left: builtin_interfaces.Duration()
            .fromJson(jsonMap['time_left'] as Map<String, dynamic>));
  }
}

class WaitActionGoal extends RosActionGoal<WaitGoal, WaitActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late WaitGoal goal;

  static WaitActionGoal $prototype = WaitActionGoal();

  WaitActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    WaitGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? WaitGoal();

  @override
  String get fullType => 'nav2_msgs/action/Wait_ActionGoal';

  @override
  String get messageDefinition => '''builtin_interfaces/Duration time''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return WaitActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: WaitGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class WaitActionResult extends RosActionResult<WaitResult, WaitActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late WaitResult result;

  static WaitActionResult $prototype = WaitActionResult();

  WaitActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    WaitResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? WaitResult();

  @override
  String get fullType => 'nav2_msgs/action/Wait_ActionResult';

  @override
  String get messageDefinition =>
      '''builtin_interfaces/Duration total_elapsed_time
uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitActionResult fromJson(Map<String, dynamic> jsonMap) {
    return WaitActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: WaitResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class WaitActionFeedback
    extends RosActionFeedback<WaitFeedback, WaitActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late WaitFeedback feedback;

  static WaitActionFeedback $prototype = WaitActionFeedback();

  WaitActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    WaitFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? WaitFeedback();

  @override
  String get fullType => 'nav2_msgs/action/Wait_ActionFeedback';

  @override
  String get messageDefinition => '''builtin_interfaces/Duration time_left''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  WaitActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return WaitActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback:
          WaitFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class Wait extends RosActionMessage<WaitGoal, WaitActionGoal, WaitFeedback,
    WaitActionFeedback, WaitResult, WaitActionResult> {
  @override
  WaitActionGoal get actionGoal => WaitActionGoal();

  @override
  WaitActionFeedback get actionFeedback => WaitActionFeedback();

  @override
  WaitActionResult get actionResult => WaitActionResult();

  @override
  WaitGoal get goal => WaitGoal();

  @override
  WaitFeedback get feedback => WaitFeedback();

  @override
  WaitResult get result => WaitResult();

  @override
  String get fullType => 'nav2_msgs/action/Wait';

  @override
  String get messageDefinition => '''
Goal:
builtin_interfaces/Duration time
---
Result:
builtin_interfaces/Duration total_elapsed_time
uint16 error_code
---
Feedback:
builtin_interfaces/Duration time_left''';
}
