// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Inertia.dart';

class InertiaStamped extends RosMessage<InertiaStamped> {
  std_msgs.Header header;
  Inertia inertia;

  static InertiaStamped $prototype = InertiaStamped();

  // Constructor
  InertiaStamped({std_msgs.Header? header, Inertia? inertia})
      : header = header ?? std_msgs.Header(),
        inertia = inertia ?? Inertia();

  @override
  String get fullType => 'geometry_msgs/msg/InertiaStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Inertia inertia''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + inertia.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'inertia': inertia.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  InertiaStamped fromJson(Map<String, dynamic> jsonMap) {
    return InertiaStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        inertia:
            Inertia().fromJson(jsonMap['inertia'] as Map<String, dynamic>));
  }
}
