// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Polygon.dart';

class PolygonStamped extends RosMessage<PolygonStamped> {
  std_msgs.Header header;
  Polygon polygon;

  static PolygonStamped $prototype = PolygonStamped();

  // Constructor
  PolygonStamped({std_msgs.Header? header, Polygon? polygon})
      : header = header ?? std_msgs.Header(),
        polygon = polygon ?? Polygon();

  @override
  String get fullType => 'geometry_msgs/msg/PolygonStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Polygon polygon''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + polygon.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'polygon': polygon.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PolygonStamped fromJson(Map<String, dynamic> jsonMap) {
    return PolygonStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        polygon:
            Polygon().fromJson(jsonMap['polygon'] as Map<String, dynamic>));
  }
}
