// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Quaternion.dart';

class QuaternionStamped extends RosMessage<QuaternionStamped> {
  std_msgs.Header header;
  Quaternion quaternion;

  static QuaternionStamped $prototype = QuaternionStamped();

  // Constructor
  QuaternionStamped({std_msgs.Header? header, Quaternion? quaternion})
      : header = header ?? std_msgs.Header(),
        quaternion = quaternion ?? Quaternion();

  @override
  String get fullType => 'geometry_msgs/msg/QuaternionStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
Quaternion quaternion''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() + quaternion.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'header': header.toJson(), 'quaternion': quaternion.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  QuaternionStamped fromJson(Map<String, dynamic> jsonMap) {
    return QuaternionStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        quaternion: Quaternion()
            .fromJson(jsonMap['quaternion'] as Map<String, dynamic>));
  }
}
