// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'Quaternion.dart';
import 'Vector3.dart';

class Transform extends RosMessage<Transform> {
  Vector3 translation;
  Quaternion rotation;

  static Transform $prototype = Transform();

  // Constructor
  Transform({Vector3? translation, Quaternion? rotation})
      : translation = translation ?? Vector3(),
        rotation = rotation ?? Quaternion();

  @override
  String get fullType => 'geometry_msgs/msg/Transform';

  @override
  String get messageDefinition => '''Vector3 translation
Quaternion rotation''';

  @override
  int getMessageSize() {
    return (translation.getMessageSize() + rotation.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'translation': translation.toJson(), 'rotation': rotation.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Transform fromJson(Map<String, dynamic> jsonMap) {
    return Transform(
        translation:
            Vector3().fromJson(jsonMap['translation'] as Map<String, dynamic>),
        rotation:
            Quaternion().fromJson(jsonMap['rotation'] as Map<String, dynamic>));
  }
}
