// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'package:std_msgs/msg.dart' as std_msgs;
import 'Transform.dart';

class TransformStamped extends RosMessage<TransformStamped> {
  std_msgs.Header header;
  String child_frame_id;
  Transform transform;

  static TransformStamped $prototype = TransformStamped();

  // Constructor
  TransformStamped(
      {std_msgs.Header? header, String? child_frame_id, Transform? transform})
      : header = header ?? std_msgs.Header(),
        child_frame_id = child_frame_id ?? '',
        transform = transform ?? Transform();

  @override
  String get fullType => 'geometry_msgs/msg/TransformStamped';

  @override
  String get messageDefinition => '''std_msgs/Header header
string child_frame_id
Transform transform''';

  @override
  int getMessageSize() {
    return (header.getMessageSize() +
            4 +
            child_frame_id.length +
            transform.getMessageSize())
        .toInt();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'child_frame_id': child_frame_id,
        'transform': transform.toJson()
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TransformStamped fromJson(Map<String, dynamic> jsonMap) {
    return TransformStamped(
        header: std_msgs.Header()
            .fromJson(jsonMap['header'] as Map<String, dynamic>),
        child_frame_id: jsonMap['child_frame_id'] as String,
        transform:
            Transform().fromJson(jsonMap['transform'] as Map<String, dynamic>));
  }
}
