// Generated by ros_to_dart_converter
// Do not edit manually

import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

import 'Vector3.dart';

class Wrench extends RosMessage<Wrench> {
  Vector3 force;
  Vector3 torque;

  static Wrench $prototype = Wrench();

  // Constructor
  Wrench({Vector3? force, Vector3? torque})
      : force = force ?? Vector3(),
        torque = torque ?? Vector3();

  @override
  String get fullType => 'geometry_msgs/msg/Wrench';

  @override
  String get messageDefinition => '''Vector3 force
Vector3 torque''';

  @override
  int getMessageSize() {
    return (force.getMessageSize() + torque.getMessageSize()).toInt();
  }

  @override
  Map<String, dynamic> toJson() =>
      {'force': force.toJson(), 'torque': torque.toJson()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  Wrench fromJson(Map<String, dynamic> jsonMap) {
    return Wrench(
        force: Vector3().fromJson(jsonMap['force'] as Map<String, dynamic>),
        torque: Vector3().fromJson(jsonMap['torque'] as Map<String, dynamic>));
  }
}
