// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class UUID extends RosMessage<UUID> {
  List<int> uuid;

  static UUID $prototype = UUID();

  // Constructor
  UUID({List<int>? uuid}) : uuid = uuid ?? const [];

  @override
  String get fullType => 'unique_identifier_msgs/msg/UUID';

  @override
  String get messageDefinition => '''uint8[16] uuid''';

  @override
  int getMessageSize() {
    return (4 + (uuid.length * 1)).toInt();
  }

  @override
  Map<String, dynamic> toJson() => {'uuid': uuid};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  UUID fromJson(Map<String, dynamic> jsonMap) {
    return UUID(uuid: (jsonMap['uuid'] as List).cast<int>());
  }
}
