// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;

class AuthGoal extends RosMessage<AuthGoal> {
  late String message;

  static AuthGoal $prototype = AuthGoal();

  AuthGoal({String? message}) : message = message ?? '';

  @override
  String get fullType => 'rio_interfaces/action/Auth_Goal';

  @override
  String get messageDefinition => '''string message''';

  @override
  int getMessageSize() {
    return 4 + message.length;
  }

  @override
  Map<String, dynamic> toJson() => {'message': message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthGoal fromJson(Map<String, dynamic> jsonMap) {
    return AuthGoal(message: jsonMap['message'] as String);
  }
}

class AuthResult extends RosMessage<AuthResult> {
  late bool success;
  late String error_message;

  static AuthResult $prototype = AuthResult();

  AuthResult({bool? success, String? error_message})
      : success = success ?? false,
        error_message = error_message ?? '';

  @override
  String get fullType => 'rio_interfaces/action/Auth_Result';

  @override
  String get messageDefinition => '''bool success
string error_message''';

  @override
  int getMessageSize() {
    return 1 + 4 + error_message.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'success': success, 'error_message': error_message};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthResult fromJson(Map<String, dynamic> jsonMap) {
    return AuthResult(
        success: jsonMap['success'] as bool,
        error_message: jsonMap['error_message'] as String);
  }
}

class AuthFeedback extends RosMessage<AuthFeedback> {
  static AuthFeedback $prototype = AuthFeedback();

  AuthFeedback();

  @override
  String get fullType => 'rio_interfaces/action/Auth_Feedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthFeedback fromJson(Map<String, dynamic> jsonMap) {
    return AuthFeedback();
  }
}

class AuthActionGoal extends RosActionGoal<AuthGoal, AuthActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late AuthGoal goal;

  static AuthActionGoal $prototype = AuthActionGoal();

  AuthActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    AuthGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? AuthGoal();

  @override
  String get fullType => 'rio_interfaces/action/Auth_ActionGoal';

  @override
  String get messageDefinition => '''string message''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return AuthActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: AuthGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class AuthActionResult extends RosActionResult<AuthResult, AuthActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late AuthResult result;

  static AuthActionResult $prototype = AuthActionResult();

  AuthActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    AuthResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? AuthResult();

  @override
  String get fullType => 'rio_interfaces/action/Auth_ActionResult';

  @override
  String get messageDefinition => '''bool success
string error_message''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthActionResult fromJson(Map<String, dynamic> jsonMap) {
    return AuthActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: AuthResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class AuthActionFeedback
    extends RosActionFeedback<AuthFeedback, AuthActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late AuthFeedback feedback;

  static AuthActionFeedback $prototype = AuthActionFeedback();

  AuthActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    AuthFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? AuthFeedback();

  @override
  String get fullType => 'rio_interfaces/action/Auth_ActionFeedback';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  AuthActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return AuthActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback:
          AuthFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class Auth extends RosActionMessage<AuthGoal, AuthActionGoal, AuthFeedback,
    AuthActionFeedback, AuthResult, AuthActionResult> {
  @override
  AuthActionGoal get actionGoal => AuthActionGoal();

  @override
  AuthActionFeedback get actionFeedback => AuthActionFeedback();

  @override
  AuthActionResult get actionResult => AuthActionResult();

  @override
  AuthGoal get goal => AuthGoal();

  @override
  AuthFeedback get feedback => AuthFeedback();

  @override
  AuthResult get result => AuthResult();

  @override
  String get fullType => 'rio_interfaces/action/Auth';

  @override
  String get messageDefinition => '''
Goal:
string message
---
Result:
bool success
string error_message
---
Feedback:
''';
}
