// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;

class TTSGoal extends RosMessage<TTSGoal> {
  late String text;
  late bool voice_output;
  late String start_expression;
  late String end_expression;
  late bool expression_sound;

  static TTSGoal $prototype = TTSGoal();

  TTSGoal(
      {String? text,
      bool? voice_output,
      String? start_expression,
      String? end_expression,
      bool? expression_sound})
      : text = text ?? '',
        voice_output = voice_output ?? false,
        start_expression = start_expression ?? '',
        end_expression = end_expression ?? '',
        expression_sound = expression_sound ?? false;

  @override
  String get fullType => 'rio_interfaces/action/TTS_Goal';

  @override
  String get messageDefinition => '''string text
bool voice_output
string start_expression
string end_expression
bool expression_sound''';

  @override
  int getMessageSize() {
    return 4 +
        text.length +
        1 +
        4 +
        start_expression.length +
        4 +
        end_expression.length +
        1;
  }

  @override
  Map<String, dynamic> toJson() => {
        'text': text,
        'voice_output': voice_output,
        'start_expression': start_expression,
        'end_expression': end_expression,
        'expression_sound': expression_sound
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSGoal fromJson(Map<String, dynamic> jsonMap) {
    return TTSGoal(
        text: jsonMap['text'] as String,
        voice_output: jsonMap['voice_output'] as bool,
        start_expression: jsonMap['start_expression'] as String,
        end_expression: jsonMap['end_expression'] as String,
        expression_sound: jsonMap['expression_sound'] as bool);
  }
}

class TTSResult extends RosMessage<TTSResult> {
  late bool success;
  late String expression;

  static TTSResult $prototype = TTSResult();

  TTSResult({bool? success, String? expression})
      : success = success ?? false,
        expression = expression ?? '';

  @override
  String get fullType => 'rio_interfaces/action/TTS_Result';

  @override
  String get messageDefinition => '''bool success
string expression''';

  @override
  int getMessageSize() {
    return 1 + 4 + expression.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'success': success, 'expression': expression};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSResult fromJson(Map<String, dynamic> jsonMap) {
    return TTSResult(
        success: jsonMap['success'] as bool,
        expression: jsonMap['expression'] as String);
  }
}

class TTSFeedback extends RosMessage<TTSFeedback> {
  late int start_idx;
  late int end_idx;
  late String word;
  late String expression;

  static TTSFeedback $prototype = TTSFeedback();

  TTSFeedback({int? start_idx, int? end_idx, String? word, String? expression})
      : start_idx = start_idx ?? 0,
        end_idx = end_idx ?? 0,
        word = word ?? '',
        expression = expression ?? '';

  @override
  String get fullType => 'rio_interfaces/action/TTS_Feedback';

  @override
  String get messageDefinition => '''uint32 start_idx
uint32 end_idx
string word
string expression''';

  @override
  int getMessageSize() {
    return 4 + 4 + 4 + word.length + 4 + expression.length;
  }

  @override
  Map<String, dynamic> toJson() => {
        'start_idx': start_idx,
        'end_idx': end_idx,
        'word': word,
        'expression': expression
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSFeedback fromJson(Map<String, dynamic> jsonMap) {
    return TTSFeedback(
        start_idx: jsonMap['start_idx'] as int,
        end_idx: jsonMap['end_idx'] as int,
        word: jsonMap['word'] as String,
        expression: jsonMap['expression'] as String);
  }
}

class TTSActionGoal extends RosActionGoal<TTSGoal, TTSActionGoal> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalID goal_id;
  @override
  late TTSGoal goal;

  static TTSActionGoal $prototype = TTSActionGoal();

  TTSActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    TTSGoal? goal,
  })  : header = header ?? std_msgs.Header(),
        goal_id = goal_id ?? actionlib_msgs.GoalID(),
        goal = goal ?? TTSGoal();

  @override
  String get fullType => 'rio_interfaces/action/TTS_ActionGoal';

  @override
  String get messageDefinition => '''string text
bool voice_output
string start_expression
string end_expression
bool expression_sound''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return TTSActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: TTSGoal().fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class TTSActionResult extends RosActionResult<TTSResult, TTSActionResult> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late TTSResult result;

  static TTSActionResult $prototype = TTSActionResult();

  TTSActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    TTSResult? result,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        result = result ?? TTSResult();

  @override
  String get fullType => 'rio_interfaces/action/TTS_ActionResult';

  @override
  String get messageDefinition => '''bool success
string expression''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSActionResult fromJson(Map<String, dynamic> jsonMap) {
    return TTSActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: TTSResult().fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class TTSActionFeedback
    extends RosActionFeedback<TTSFeedback, TTSActionFeedback> {
  @override
  late std_msgs.Header header;
  @override
  late actionlib_msgs.GoalStatus status;
  @override
  late TTSFeedback feedback;

  static TTSActionFeedback $prototype = TTSActionFeedback();

  TTSActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    TTSFeedback? feedback,
  })  : header = header ?? std_msgs.Header(),
        status = status ?? actionlib_msgs.GoalStatus(),
        feedback = feedback ?? TTSFeedback();

  @override
  String get fullType => 'rio_interfaces/action/TTS_ActionFeedback';

  @override
  String get messageDefinition => '''uint32 start_idx
uint32 end_idx
string word
string expression''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  TTSActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return TTSActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback:
          TTSFeedback().fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class TTS extends RosActionMessage<TTSGoal, TTSActionGoal, TTSFeedback,
    TTSActionFeedback, TTSResult, TTSActionResult> {
  @override
  TTSActionGoal get actionGoal => TTSActionGoal();

  @override
  TTSActionFeedback get actionFeedback => TTSActionFeedback();

  @override
  TTSActionResult get actionResult => TTSActionResult();

  @override
  TTSGoal get goal => TTSGoal();

  @override
  TTSFeedback get feedback => TTSFeedback();

  @override
  TTSResult get result => TTSResult();

  @override
  String get fullType => 'rio_interfaces/action/TTS';

  @override
  String get messageDefinition => '''
Goal:
string text
bool voice_output
string start_expression
string end_expression
bool expression_sound
---
Result:
bool success
string expression
---
Feedback:
uint32 start_idx
uint32 end_idx
string word
string expression''';
}
