// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/TypeDef.dart';

class ActionResultDetailsRequest
    extends RosMessage<ActionResultDetailsRequest> {
  late String type;

  static ActionResultDetailsRequest $prototype = ActionResultDetailsRequest();

  ActionResultDetailsRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ActionResultDetails_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionResultDetailsRequest fromJson(Map<String, dynamic> jsonMap) {
    return ActionResultDetailsRequest(type: jsonMap['type'] as String);
  }
}

class ActionResultDetailsResponse
    extends RosMessage<ActionResultDetailsResponse> {
  late List<TypeDef> typedefs;

  static ActionResultDetailsResponse $prototype = ActionResultDetailsResponse();

  ActionResultDetailsResponse({List<TypeDef>? typedefs})
      : typedefs = typedefs ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/ActionResultDetails_Response';

  @override
  String get messageDefinition => '''TypeDef[] typedefs''';

  @override
  int getMessageSize() {
    return 4 +
        typedefs.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() =>
      {'typedefs': typedefs.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionResultDetailsResponse fromJson(Map<String, dynamic> jsonMap) {
    return ActionResultDetailsResponse(
        typedefs: (jsonMap['typedefs'] as List<dynamic>)
            .map((item) => TypeDef().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class ActionResultDetails extends RosServiceMessage<ActionResultDetailsRequest,
    ActionResultDetailsResponse> {
  @override
  ActionResultDetailsRequest get request => ActionResultDetailsRequest();

  @override
  ActionResultDetailsResponse get response => ActionResultDetailsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ActionResultDetails';

  @override
  String get messageDefinition => '''
string type
---
TypeDef[] typedefs''';
}
