// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/TypeDef.dart';

class ActionGoalDetailsRequest extends RosMessage<ActionGoalDetailsRequest> {
  late String type;

  static ActionGoalDetailsRequest $prototype = ActionGoalDetailsRequest();

  ActionGoalDetailsRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ActionGoalDetails_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionGoalDetailsRequest fromJson(Map<String, dynamic> jsonMap) {
    return ActionGoalDetailsRequest(type: jsonMap['type'] as String);
  }
}

class ActionGoalDetailsResponse extends RosMessage<ActionGoalDetailsResponse> {
  late List<TypeDef> typedefs;

  static ActionGoalDetailsResponse $prototype = ActionGoalDetailsResponse();

  ActionGoalDetailsResponse({List<TypeDef>? typedefs})
      : typedefs = typedefs ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/ActionGoalDetails_Response';

  @override
  String get messageDefinition => '''TypeDef[] typedefs''';

  @override
  int getMessageSize() {
    return 4 +
        typedefs.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() =>
      {'typedefs': typedefs.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ActionGoalDetailsResponse fromJson(Map<String, dynamic> jsonMap) {
    return ActionGoalDetailsResponse(
        typedefs: (jsonMap['typedefs'] as List<dynamic>)
            .map((item) => TypeDef().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class ActionGoalDetails extends RosServiceMessage<ActionGoalDetailsRequest,
    ActionGoalDetailsResponse> {
  @override
  ActionGoalDetailsRequest get request => ActionGoalDetailsRequest();

  @override
  ActionGoalDetailsResponse get response => ActionGoalDetailsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ActionGoalDetails';

  @override
  String get messageDefinition => '''
string type
---
TypeDef[] typedefs''';
}
