// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class GetActionServersRequest extends RosMessage<GetActionServersRequest> {
  static GetActionServersRequest $prototype = GetActionServersRequest();

  GetActionServersRequest();

  @override
  String get fullType => 'rosapi_msgs/srv/GetActionServers_Request';

  @override
  String get messageDefinition => '''''';

  @override
  int getMessageSize() {
    return 0;
  }

  @override
  Map<String, dynamic> toJson() => {};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetActionServersRequest fromJson(Map<String, dynamic> jsonMap) {
    return GetActionServersRequest();
  }
}

class GetActionServersResponse extends RosMessage<GetActionServersResponse> {
  late List<String> action_servers;

  static GetActionServersResponse $prototype = GetActionServersResponse();

  GetActionServersResponse({List<String>? action_servers})
      : action_servers = action_servers ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/GetActionServers_Response';

  @override
  String get messageDefinition => '''string[] action_servers''';

  @override
  int getMessageSize() {
    return 4 + (action_servers.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'action_servers': action_servers};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  GetActionServersResponse fromJson(Map<String, dynamic> jsonMap) {
    return GetActionServersResponse(
        action_servers: (jsonMap['action_servers'] as List<dynamic>)
            .cast<String>()
            .toList());
  }
}

class GetActionServers extends RosServiceMessage<GetActionServersRequest,
    GetActionServersResponse> {
  @override
  GetActionServersRequest get request => GetActionServersRequest();

  @override
  GetActionServersResponse get response => GetActionServersResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/GetActionServers';

  @override
  String get messageDefinition => '''

---
string[] action_servers''';
}
