// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import '../msg/TypeDef.dart';

class MessageDetailsRequest extends RosMessage<MessageDetailsRequest> {
  late String type;

  static MessageDetailsRequest $prototype = MessageDetailsRequest();

  MessageDetailsRequest({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/MessageDetails_Request';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MessageDetailsRequest fromJson(Map<String, dynamic> jsonMap) {
    return MessageDetailsRequest(type: jsonMap['type'] as String);
  }
}

class MessageDetailsResponse extends RosMessage<MessageDetailsResponse> {
  late List<TypeDef> typedefs;

  static MessageDetailsResponse $prototype = MessageDetailsResponse();

  MessageDetailsResponse({List<TypeDef>? typedefs})
      : typedefs = typedefs ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/MessageDetails_Response';

  @override
  String get messageDefinition => '''TypeDef[] typedefs''';

  @override
  int getMessageSize() {
    return 4 +
        typedefs.fold<int>(0, (sum, item) => sum + (item.getMessageSize()));
  }

  @override
  Map<String, dynamic> toJson() =>
      {'typedefs': typedefs.map((item) => item.toJson()).toList()};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  MessageDetailsResponse fromJson(Map<String, dynamic> jsonMap) {
    return MessageDetailsResponse(
        typedefs: (jsonMap['typedefs'] as List<dynamic>)
            .map((item) => TypeDef().fromJson(item as Map<String, dynamic>))
            .toList());
  }
}

class MessageDetails
    extends RosServiceMessage<MessageDetailsRequest, MessageDetailsResponse> {
  @override
  MessageDetailsRequest get request => MessageDetailsRequest();

  @override
  MessageDetailsResponse get response => MessageDetailsResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/MessageDetails';

  @override
  String get messageDefinition => '''
string type
---
TypeDef[] typedefs''';
}
