// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class PublishersRequest extends RosMessage<PublishersRequest> {
  late String topic;

  static PublishersRequest $prototype = PublishersRequest();

  PublishersRequest({String? topic}) : topic = topic ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/Publishers_Request';

  @override
  String get messageDefinition => '''string topic''';

  @override
  int getMessageSize() {
    return 4 + topic.length;
  }

  @override
  Map<String, dynamic> toJson() => {'topic': topic};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PublishersRequest fromJson(Map<String, dynamic> jsonMap) {
    return PublishersRequest(topic: jsonMap['topic'] as String);
  }
}

class PublishersResponse extends RosMessage<PublishersResponse> {
  late List<String> publishers;

  static PublishersResponse $prototype = PublishersResponse();

  PublishersResponse({List<String>? publishers})
      : publishers = publishers ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Publishers_Response';

  @override
  String get messageDefinition => '''string[] publishers''';

  @override
  int getMessageSize() {
    return 4 + (publishers.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'publishers': publishers};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  PublishersResponse fromJson(Map<String, dynamic> jsonMap) {
    return PublishersResponse(
        publishers:
            (jsonMap['publishers'] as List<dynamic>).cast<String>().toList());
  }
}

class Publishers
    extends RosServiceMessage<PublishersRequest, PublishersResponse> {
  @override
  PublishersRequest get request => PublishersRequest();

  @override
  PublishersResponse get response => PublishersResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Publishers';

  @override
  String get messageDefinition => '''
string topic
---
string[] publishers''';
}
