// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class ServiceTypeRequest extends RosMessage<ServiceTypeRequest> {
  late String service;

  static ServiceTypeRequest $prototype = ServiceTypeRequest();

  ServiceTypeRequest({String? service}) : service = service ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceType_Request';

  @override
  String get messageDefinition => '''string service''';

  @override
  int getMessageSize() {
    return 4 + service.length;
  }

  @override
  Map<String, dynamic> toJson() => {'service': service};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceTypeRequest fromJson(Map<String, dynamic> jsonMap) {
    return ServiceTypeRequest(service: jsonMap['service'] as String);
  }
}

class ServiceTypeResponse extends RosMessage<ServiceTypeResponse> {
  late String type;

  static ServiceTypeResponse $prototype = ServiceTypeResponse();

  ServiceTypeResponse({String? type}) : type = type ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceType_Response';

  @override
  String get messageDefinition => '''string type''';

  @override
  int getMessageSize() {
    return 4 + type.length;
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  ServiceTypeResponse fromJson(Map<String, dynamic> jsonMap) {
    return ServiceTypeResponse(type: jsonMap['type'] as String);
  }
}

class ServiceType
    extends RosServiceMessage<ServiceTypeRequest, ServiceTypeResponse> {
  @override
  ServiceTypeRequest get request => ServiceTypeRequest();

  @override
  ServiceTypeResponse get response => ServiceTypeResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/ServiceType';

  @override
  String get messageDefinition => '''
string service
---
string type''';
}
