// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';

class SubscribersRequest extends RosMessage<SubscribersRequest> {
  late String topic;

  static SubscribersRequest $prototype = SubscribersRequest();

  SubscribersRequest({String? topic}) : topic = topic ?? '';

  @override
  String get fullType => 'rosapi_msgs/srv/Subscribers_Request';

  @override
  String get messageDefinition => '''string topic''';

  @override
  int getMessageSize() {
    return 4 + topic.length;
  }

  @override
  Map<String, dynamic> toJson() => {'topic': topic};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SubscribersRequest fromJson(Map<String, dynamic> jsonMap) {
    return SubscribersRequest(topic: jsonMap['topic'] as String);
  }
}

class SubscribersResponse extends RosMessage<SubscribersResponse> {
  late List<String> subscribers;

  static SubscribersResponse $prototype = SubscribersResponse();

  SubscribersResponse({List<String>? subscribers})
      : subscribers = subscribers ?? const [];

  @override
  String get fullType => 'rosapi_msgs/srv/Subscribers_Response';

  @override
  String get messageDefinition => '''string[] subscribers''';

  @override
  int getMessageSize() {
    return 4 + (subscribers.length * 0);
  }

  @override
  Map<String, dynamic> toJson() => {'subscribers': subscribers};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  SubscribersResponse fromJson(Map<String, dynamic> jsonMap) {
    return SubscribersResponse(
        subscribers:
            (jsonMap['subscribers'] as List<dynamic>).cast<String>().toList());
  }
}

class Subscribers
    extends RosServiceMessage<SubscribersRequest, SubscribersResponse> {
  @override
  SubscribersRequest get request => SubscribersRequest();

  @override
  SubscribersResponse get response => SubscribersResponse();

  @override
  String get fullType => 'rosapi_msgs/srv/Subscribers';

  @override
  String get messageDefinition => '''
string topic
---
string[] subscribers''';
}
